// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.netskopepublisher.provider.inputs.GuestNetworkInterfaceArgs;
import com.pulumi.netskopepublisher.provider.inputs.MetadataOptionsArgs;
import com.pulumi.netskopepublisher.provider.inputs.PublisherRegistrationInputArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AwsPublisherArgs extends com.pulumi.resources.ResourceArgs {

    public static final AwsPublisherArgs Empty = new AwsPublisherArgs();

    @Import(name="amiId")
    private @Nullable String amiId;

    public Optional<String> amiId() {
        return Optional.ofNullable(this.amiId);
    }

    @Import(name="apiToken")
    private @Nullable String apiToken;

    public Optional<String> apiToken() {
        return Optional.ofNullable(this.apiToken);
    }

    @Import(name="associatePublicIpAddress")
    private @Nullable Boolean associatePublicIpAddress;

    public Optional<Boolean> associatePublicIpAddress() {
        return Optional.ofNullable(this.associatePublicIpAddress);
    }

    @Import(name="bootstrap")
    private @Nullable Boolean bootstrap;

    public Optional<Boolean> bootstrap() {
        return Optional.ofNullable(this.bootstrap);
    }

    @Import(name="bootstrapUrl")
    private @Nullable String bootstrapUrl;

    public Optional<String> bootstrapUrl() {
        return Optional.ofNullable(this.bootstrapUrl);
    }

    @Import(name="deleteDefaultUser")
    private @Nullable Boolean deleteDefaultUser;

    public Optional<Boolean> deleteDefaultUser() {
        return Optional.ofNullable(this.deleteDefaultUser);
    }

    @Import(name="ebsOptimized")
    private @Nullable Boolean ebsOptimized;

    public Optional<Boolean> ebsOptimized() {
        return Optional.ofNullable(this.ebsOptimized);
    }

    @Import(name="guestNetworkInterface")
    private @Nullable Output<GuestNetworkInterfaceArgs> guestNetworkInterface;

    public Optional<Output<GuestNetworkInterfaceArgs>> guestNetworkInterface() {
        return Optional.ofNullable(this.guestNetworkInterface);
    }

    @Import(name="iamInstanceProfile")
    private @Nullable String iamInstanceProfile;

    public Optional<String> iamInstanceProfile() {
        return Optional.ofNullable(this.iamInstanceProfile);
    }

    @Import(name="installUser")
    private @Nullable String installUser;

    public Optional<String> installUser() {
        return Optional.ofNullable(this.installUser);
    }

    @Import(name="installUserPassword")
    private @Nullable String installUserPassword;

    public Optional<String> installUserPassword() {
        return Optional.ofNullable(this.installUserPassword);
    }

    @Import(name="installUserPasswordIsHash")
    private @Nullable Boolean installUserPasswordIsHash;

    public Optional<Boolean> installUserPasswordIsHash() {
        return Optional.ofNullable(this.installUserPasswordIsHash);
    }

    @Import(name="installUserSshAuthorizedKeys")
    private @Nullable Output<List<String>> installUserSshAuthorizedKeys;

    public Optional<Output<List<String>>> installUserSshAuthorizedKeys() {
        return Optional.ofNullable(this.installUserSshAuthorizedKeys);
    }

    @Import(name="instanceType")
    private @Nullable String instanceType;

    public Optional<String> instanceType() {
        return Optional.ofNullable(this.instanceType);
    }

    @Import(name="keyName")
    private @Nullable String keyName;

    public Optional<String> keyName() {
        return Optional.ofNullable(this.keyName);
    }

    @Import(name="metadataOptions")
    private @Nullable Output<MetadataOptionsArgs> metadataOptions;

    public Optional<Output<MetadataOptionsArgs>> metadataOptions() {
        return Optional.ofNullable(this.metadataOptions);
    }

    @Import(name="monitoring")
    private @Nullable Boolean monitoring;

    public Optional<Boolean> monitoring() {
        return Optional.ofNullable(this.monitoring);
    }

    @Import(name="namePrefix")
    private @Nullable String namePrefix;

    public Optional<String> namePrefix() {
        return Optional.ofNullable(this.namePrefix);
    }

    @Import(name="names")
    private @Nullable Output<List<String>> names;

    public Optional<Output<List<String>>> names() {
        return Optional.ofNullable(this.names);
    }

    @Import(name="nonat")
    private @Nullable Boolean nonat;

    public Optional<Boolean> nonat() {
        return Optional.ofNullable(this.nonat);
    }

    @Import(name="registrations")
    private @Nullable Output<Map<String,PublisherRegistrationInputArgs>> registrations;

    public Optional<Output<Map<String,PublisherRegistrationInputArgs>>> registrations() {
        return Optional.ofNullable(this.registrations);
    }

    @Import(name="replicas")
    private @Nullable Integer replicas;

    public Optional<Integer> replicas() {
        return Optional.ofNullable(this.replicas);
    }

    @Import(name="securityGroupIds", required=true)
    private Output<List<String>> securityGroupIds;

    public Output<List<String>> securityGroupIds() {
        return this.securityGroupIds;
    }

    @Import(name="subnetId", required=true)
    private String subnetId;

    public String subnetId() {
        return this.subnetId;
    }

    @Import(name="tags")
    private @Nullable Output<Map<String,String>> tags;

    public Optional<Output<Map<String,String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    @Import(name="tenantUrl")
    private @Nullable String tenantUrl;

    public Optional<String> tenantUrl() {
        return Optional.ofNullable(this.tenantUrl);
    }

    @Import(name="wizardPath")
    private @Nullable String wizardPath;

    public Optional<String> wizardPath() {
        return Optional.ofNullable(this.wizardPath);
    }

    private AwsPublisherArgs() {}

    private AwsPublisherArgs(AwsPublisherArgs $) {
        this.amiId = $.amiId;
        this.apiToken = $.apiToken;
        this.associatePublicIpAddress = $.associatePublicIpAddress;
        this.bootstrap = $.bootstrap;
        this.bootstrapUrl = $.bootstrapUrl;
        this.deleteDefaultUser = $.deleteDefaultUser;
        this.ebsOptimized = $.ebsOptimized;
        this.guestNetworkInterface = $.guestNetworkInterface;
        this.iamInstanceProfile = $.iamInstanceProfile;
        this.installUser = $.installUser;
        this.installUserPassword = $.installUserPassword;
        this.installUserPasswordIsHash = $.installUserPasswordIsHash;
        this.installUserSshAuthorizedKeys = $.installUserSshAuthorizedKeys;
        this.instanceType = $.instanceType;
        this.keyName = $.keyName;
        this.metadataOptions = $.metadataOptions;
        this.monitoring = $.monitoring;
        this.namePrefix = $.namePrefix;
        this.names = $.names;
        this.nonat = $.nonat;
        this.registrations = $.registrations;
        this.replicas = $.replicas;
        this.securityGroupIds = $.securityGroupIds;
        this.subnetId = $.subnetId;
        this.tags = $.tags;
        this.tenantUrl = $.tenantUrl;
        this.wizardPath = $.wizardPath;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AwsPublisherArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AwsPublisherArgs $;

        public Builder() {
            $ = new AwsPublisherArgs();
        }

        public Builder(AwsPublisherArgs defaults) {
            $ = new AwsPublisherArgs(Objects.requireNonNull(defaults));
        }

        public Builder amiId(@Nullable String amiId) {
            $.amiId = amiId;
            return this;
        }

        public Builder apiToken(@Nullable String apiToken) {
            $.apiToken = apiToken;
            return this;
        }

        public Builder associatePublicIpAddress(@Nullable Boolean associatePublicIpAddress) {
            $.associatePublicIpAddress = associatePublicIpAddress;
            return this;
        }

        public Builder bootstrap(@Nullable Boolean bootstrap) {
            $.bootstrap = bootstrap;
            return this;
        }

        public Builder bootstrapUrl(@Nullable String bootstrapUrl) {
            $.bootstrapUrl = bootstrapUrl;
            return this;
        }

        public Builder deleteDefaultUser(@Nullable Boolean deleteDefaultUser) {
            $.deleteDefaultUser = deleteDefaultUser;
            return this;
        }

        public Builder ebsOptimized(@Nullable Boolean ebsOptimized) {
            $.ebsOptimized = ebsOptimized;
            return this;
        }

        public Builder guestNetworkInterface(@Nullable Output<GuestNetworkInterfaceArgs> guestNetworkInterface) {
            $.guestNetworkInterface = guestNetworkInterface;
            return this;
        }

        public Builder guestNetworkInterface(GuestNetworkInterfaceArgs guestNetworkInterface) {
            return guestNetworkInterface(Output.of(guestNetworkInterface));
        }

        public Builder iamInstanceProfile(@Nullable String iamInstanceProfile) {
            $.iamInstanceProfile = iamInstanceProfile;
            return this;
        }

        public Builder installUser(@Nullable String installUser) {
            $.installUser = installUser;
            return this;
        }

        public Builder installUserPassword(@Nullable String installUserPassword) {
            $.installUserPassword = installUserPassword;
            return this;
        }

        public Builder installUserPasswordIsHash(@Nullable Boolean installUserPasswordIsHash) {
            $.installUserPasswordIsHash = installUserPasswordIsHash;
            return this;
        }

        public Builder installUserSshAuthorizedKeys(@Nullable Output<List<String>> installUserSshAuthorizedKeys) {
            $.installUserSshAuthorizedKeys = installUserSshAuthorizedKeys;
            return this;
        }

        public Builder installUserSshAuthorizedKeys(List<String> installUserSshAuthorizedKeys) {
            return installUserSshAuthorizedKeys(Output.of(installUserSshAuthorizedKeys));
        }

        public Builder installUserSshAuthorizedKeys(String... installUserSshAuthorizedKeys) {
            return installUserSshAuthorizedKeys(List.of(installUserSshAuthorizedKeys));
        }

        public Builder instanceType(@Nullable String instanceType) {
            $.instanceType = instanceType;
            return this;
        }

        public Builder keyName(@Nullable String keyName) {
            $.keyName = keyName;
            return this;
        }

        public Builder metadataOptions(@Nullable Output<MetadataOptionsArgs> metadataOptions) {
            $.metadataOptions = metadataOptions;
            return this;
        }

        public Builder metadataOptions(MetadataOptionsArgs metadataOptions) {
            return metadataOptions(Output.of(metadataOptions));
        }

        public Builder monitoring(@Nullable Boolean monitoring) {
            $.monitoring = monitoring;
            return this;
        }

        public Builder namePrefix(@Nullable String namePrefix) {
            $.namePrefix = namePrefix;
            return this;
        }

        public Builder names(@Nullable Output<List<String>> names) {
            $.names = names;
            return this;
        }

        public Builder names(List<String> names) {
            return names(Output.of(names));
        }

        public Builder names(String... names) {
            return names(List.of(names));
        }

        public Builder nonat(@Nullable Boolean nonat) {
            $.nonat = nonat;
            return this;
        }

        public Builder registrations(@Nullable Output<Map<String,PublisherRegistrationInputArgs>> registrations) {
            $.registrations = registrations;
            return this;
        }

        public Builder registrations(Map<String,PublisherRegistrationInputArgs> registrations) {
            return registrations(Output.of(registrations));
        }

        public Builder replicas(@Nullable Integer replicas) {
            $.replicas = replicas;
            return this;
        }

        public Builder securityGroupIds(Output<List<String>> securityGroupIds) {
            $.securityGroupIds = securityGroupIds;
            return this;
        }

        public Builder securityGroupIds(List<String> securityGroupIds) {
            return securityGroupIds(Output.of(securityGroupIds));
        }

        public Builder securityGroupIds(String... securityGroupIds) {
            return securityGroupIds(List.of(securityGroupIds));
        }

        public Builder subnetId(String subnetId) {
            $.subnetId = subnetId;
            return this;
        }

        public Builder tags(@Nullable Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        public Builder tenantUrl(@Nullable String tenantUrl) {
            $.tenantUrl = tenantUrl;
            return this;
        }

        public Builder wizardPath(@Nullable String wizardPath) {
            $.wizardPath = wizardPath;
            return this;
        }

        public AwsPublisherArgs build() {
            if ($.securityGroupIds == null) {
                throw new MissingRequiredPropertyException("AwsPublisherArgs", "securityGroupIds");
            }
            if ($.subnetId == null) {
                throw new MissingRequiredPropertyException("AwsPublisherArgs", "subnetId");
            }
            return $;
        }
    }

}
