// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.netskopepublisher.OciPublisherArgs;
import com.pulumi.netskopepublisher.Utilities;
import com.pulumi.netskopepublisher.provider.outputs.GuestNetworkInterface;
import com.pulumi.netskopepublisher.provider.outputs.PublisherRegistrationInput;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="netskope-publisher:index:OciPublisher")
public class OciPublisher extends com.pulumi.resources.ComponentResource {
    @Export(name="apiToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> apiToken;

    public Output<Optional<String>> apiToken() {
        return Codegen.optional(this.apiToken);
    }
    @Export(name="assignPublicIp", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> assignPublicIp;

    public Output<Optional<Boolean>> assignPublicIp() {
        return Codegen.optional(this.assignPublicIp);
    }
    @Export(name="availabilityDomain", refs={String.class}, tree="[0]")
    private Output<String> availabilityDomain;

    public Output<String> availabilityDomain() {
        return this.availabilityDomain;
    }
    @Export(name="bootstrap", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> bootstrap;

    public Output<Optional<Boolean>> bootstrap() {
        return Codegen.optional(this.bootstrap);
    }
    @Export(name="bootstrapUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> bootstrapUrl;

    public Output<Optional<String>> bootstrapUrl() {
        return Codegen.optional(this.bootstrapUrl);
    }
    @Export(name="compartmentId", refs={String.class}, tree="[0]")
    private Output<String> compartmentId;

    public Output<String> compartmentId() {
        return this.compartmentId;
    }
    @Export(name="deleteDefaultUser", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> deleteDefaultUser;

    public Output<Optional<Boolean>> deleteDefaultUser() {
        return Codegen.optional(this.deleteDefaultUser);
    }
    @Export(name="guestNetworkInterface", refs={GuestNetworkInterface.class}, tree="[0]")
    private Output</* @Nullable */ GuestNetworkInterface> guestNetworkInterface;

    public Output<Optional<GuestNetworkInterface>> guestNetworkInterface() {
        return Codegen.optional(this.guestNetworkInterface);
    }
    @Export(name="imageId", refs={String.class}, tree="[0]")
    private Output<String> imageId;

    public Output<String> imageId() {
        return this.imageId;
    }
    @Export(name="installUser", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUser;

    public Output<Optional<String>> installUser() {
        return Codegen.optional(this.installUser);
    }
    @Export(name="installUserPassword", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUserPassword;

    public Output<Optional<String>> installUserPassword() {
        return Codegen.optional(this.installUserPassword);
    }
    @Export(name="installUserPasswordIsHash", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> installUserPasswordIsHash;

    public Output<Optional<Boolean>> installUserPasswordIsHash() {
        return Codegen.optional(this.installUserPasswordIsHash);
    }
    @Export(name="installUserSshAuthorizedKeys", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> installUserSshAuthorizedKeys;

    public Output<Optional<List<String>>> installUserSshAuthorizedKeys() {
        return Codegen.optional(this.installUserSshAuthorizedKeys);
    }
    @Export(name="namePrefix", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namePrefix;

    public Output<Optional<String>> namePrefix() {
        return Codegen.optional(this.namePrefix);
    }
    @Export(name="names", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> names;

    public Output<Optional<List<String>>> names() {
        return Codegen.optional(this.names);
    }
    @Export(name="nonat", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> nonat;

    public Output<Optional<Boolean>> nonat() {
        return Codegen.optional(this.nonat);
    }
    @Export(name="publisherNames", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> publisherNames;

    public Output<List<String>> publisherNames() {
        return this.publisherNames;
    }
    @Export(name="publishers", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> publishers;

    public Output<Map<String,Object>> publishers() {
        return this.publishers;
    }
    @Export(name="registrations", refs={Map.class,String.class,PublisherRegistrationInput.class}, tree="[0,1,2]")
    private Output</* @Nullable */ Map<String,PublisherRegistrationInput>> registrations;

    public Output<Optional<Map<String,PublisherRegistrationInput>>> registrations() {
        return Codegen.optional(this.registrations);
    }
    @Export(name="replicas", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> replicas;

    public Output<Optional<Integer>> replicas() {
        return Codegen.optional(this.replicas);
    }
    @Export(name="shape", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> shape;

    public Output<Optional<String>> shape() {
        return Codegen.optional(this.shape);
    }
    @Export(name="sshPublicKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> sshPublicKey;

    public Output<Optional<String>> sshPublicKey() {
        return Codegen.optional(this.sshPublicKey);
    }
    @Export(name="subnetId", refs={String.class}, tree="[0]")
    private Output<String> subnetId;

    public Output<String> subnetId() {
        return this.subnetId;
    }
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    @Export(name="tenantUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenantUrl;

    public Output<Optional<String>> tenantUrl() {
        return Codegen.optional(this.tenantUrl);
    }
    @Export(name="wizardPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> wizardPath;

    public Output<Optional<String>> wizardPath() {
        return Codegen.optional(this.wizardPath);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public OciPublisher(java.lang.String name) {
        this(name, OciPublisherArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public OciPublisher(java.lang.String name, OciPublisherArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public OciPublisher(java.lang.String name, OciPublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("netskope-publisher:index:OciPublisher", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static OciPublisherArgs makeArgs(OciPublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? OciPublisherArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/johnneerdael/pulumi-netskope-publisher")
            .additionalSecretOutputs(List.of(
                "apiToken",
                "installUserPassword",
                "publishers"
            ))
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
