// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.netskopepublisher.ProxmoxvePublisherArgs;
import com.pulumi.netskopepublisher.Utilities;
import com.pulumi.netskopepublisher.provider.outputs.GuestNetworkInterface;
import com.pulumi.netskopepublisher.provider.outputs.NetskopeOAuth2Args;
import com.pulumi.netskopepublisher.provider.outputs.PublisherRegistrationInput;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="netskope-publisher:index:ProxmoxvePublisher")
public class ProxmoxvePublisher extends com.pulumi.resources.ComponentResource {
    @Export(name="apiToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> apiToken;

    public Output<Optional<String>> apiToken() {
        return Codegen.optional(this.apiToken);
    }
    @Export(name="authMode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> authMode;

    public Output<Optional<String>> authMode() {
        return Codegen.optional(this.authMode);
    }
    @Export(name="bearerToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> bearerToken;

    public Output<Optional<String>> bearerToken() {
        return Codegen.optional(this.bearerToken);
    }
    @Export(name="bootstrap", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> bootstrap;

    public Output<Optional<Boolean>> bootstrap() {
        return Codegen.optional(this.bootstrap);
    }
    @Export(name="bootstrapUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> bootstrapUrl;

    public Output<Optional<String>> bootstrapUrl() {
        return Codegen.optional(this.bootstrapUrl);
    }
    @Export(name="cloneNodeName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cloneNodeName;

    public Output<Optional<String>> cloneNodeName() {
        return Codegen.optional(this.cloneNodeName);
    }
    @Export(name="cpuCores", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> cpuCores;

    public Output<Optional<Integer>> cpuCores() {
        return Codegen.optional(this.cpuCores);
    }
    @Export(name="datastoreId", refs={String.class}, tree="[0]")
    private Output<String> datastoreId;

    public Output<String> datastoreId() {
        return this.datastoreId;
    }
    @Export(name="deleteDefaultUser", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> deleteDefaultUser;

    public Output<Optional<Boolean>> deleteDefaultUser() {
        return Codegen.optional(this.deleteDefaultUser);
    }
    @Export(name="diskSize", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> diskSize;

    public Output<Optional<Integer>> diskSize() {
        return Codegen.optional(this.diskSize);
    }
    @Export(name="fullClone", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> fullClone;

    public Output<Optional<Boolean>> fullClone() {
        return Codegen.optional(this.fullClone);
    }
    @Export(name="gateway", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> gateway;

    public Output<Optional<String>> gateway() {
        return Codegen.optional(this.gateway);
    }
    @Export(name="guestNetworkInterface", refs={GuestNetworkInterface.class}, tree="[0]")
    private Output</* @Nullable */ GuestNetworkInterface> guestNetworkInterface;

    public Output<Optional<GuestNetworkInterface>> guestNetworkInterface() {
        return Codegen.optional(this.guestNetworkInterface);
    }
    @Export(name="installUser", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUser;

    public Output<Optional<String>> installUser() {
        return Codegen.optional(this.installUser);
    }
    @Export(name="installUserPassword", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUserPassword;

    public Output<Optional<String>> installUserPassword() {
        return Codegen.optional(this.installUserPassword);
    }
    @Export(name="installUserPasswordIsHash", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> installUserPasswordIsHash;

    public Output<Optional<Boolean>> installUserPasswordIsHash() {
        return Codegen.optional(this.installUserPasswordIsHash);
    }
    @Export(name="installUserSshAuthorizedKeys", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> installUserSshAuthorizedKeys;

    public Output<Optional<List<String>>> installUserSshAuthorizedKeys() {
        return Codegen.optional(this.installUserSshAuthorizedKeys);
    }
    @Export(name="ipAddress", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ipAddress;

    public Output<Optional<String>> ipAddress() {
        return Codegen.optional(this.ipAddress);
    }
    @Export(name="memory", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> memory;

    public Output<Optional<Integer>> memory() {
        return Codegen.optional(this.memory);
    }
    @Export(name="namePrefix", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namePrefix;

    public Output<Optional<String>> namePrefix() {
        return Codegen.optional(this.namePrefix);
    }
    @Export(name="names", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> names;

    public Output<Optional<List<String>>> names() {
        return Codegen.optional(this.names);
    }
    @Export(name="nameservers", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> nameservers;

    public Output<Optional<List<String>>> nameservers() {
        return Codegen.optional(this.nameservers);
    }
    @Export(name="networkBridge", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> networkBridge;

    public Output<Optional<String>> networkBridge() {
        return Codegen.optional(this.networkBridge);
    }
    @Export(name="networkModel", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> networkModel;

    public Output<Optional<String>> networkModel() {
        return Codegen.optional(this.networkModel);
    }
    @Export(name="nodeName", refs={String.class}, tree="[0]")
    private Output<String> nodeName;

    public Output<String> nodeName() {
        return this.nodeName;
    }
    @Export(name="nonat", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> nonat;

    public Output<Optional<Boolean>> nonat() {
        return Codegen.optional(this.nonat);
    }
    @Export(name="oauth2", refs={NetskopeOAuth2Args.class}, tree="[0]")
    private Output</* @Nullable */ NetskopeOAuth2Args> oauth2;

    public Output<Optional<NetskopeOAuth2Args>> oauth2() {
        return Codegen.optional(this.oauth2);
    }
    @Export(name="onBoot", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> onBoot;

    public Output<Optional<Boolean>> onBoot() {
        return Codegen.optional(this.onBoot);
    }
    @Export(name="placementLabels", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> placementLabels;

    public Output<Optional<List<String>>> placementLabels() {
        return Codegen.optional(this.placementLabels);
    }
    @Export(name="poolId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> poolId;

    public Output<Optional<String>> poolId() {
        return Codegen.optional(this.poolId);
    }
    @Export(name="publisherNames", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> publisherNames;

    public Output<List<String>> publisherNames() {
        return this.publisherNames;
    }
    @Export(name="publishers", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> publishers;

    public Output<Map<String,Object>> publishers() {
        return this.publishers;
    }
    @Export(name="registrations", refs={Map.class,String.class,PublisherRegistrationInput.class}, tree="[0,1,2]")
    private Output</* @Nullable */ Map<String,PublisherRegistrationInput>> registrations;

    public Output<Optional<Map<String,PublisherRegistrationInput>>> registrations() {
        return Codegen.optional(this.registrations);
    }
    @Export(name="replicas", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> replicas;

    public Output<Optional<Integer>> replicas() {
        return Codegen.optional(this.replicas);
    }
    @Export(name="started", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> started;

    public Output<Optional<Boolean>> started() {
        return Codegen.optional(this.started);
    }
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    @Export(name="templateVmId", refs={Integer.class}, tree="[0]")
    private Output<Integer> templateVmId;

    public Output<Integer> templateVmId() {
        return this.templateVmId;
    }
    @Export(name="tenantUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenantUrl;

    public Output<Optional<String>> tenantUrl() {
        return Codegen.optional(this.tenantUrl);
    }
    @Export(name="vlanId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> vlanId;

    public Output<Optional<Integer>> vlanId() {
        return Codegen.optional(this.vlanId);
    }
    @Export(name="vmId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> vmId;

    public Output<Optional<Integer>> vmId() {
        return Codegen.optional(this.vmId);
    }
    @Export(name="wizardPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> wizardPath;

    public Output<Optional<String>> wizardPath() {
        return Codegen.optional(this.wizardPath);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ProxmoxvePublisher(java.lang.String name) {
        this(name, ProxmoxvePublisherArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ProxmoxvePublisher(java.lang.String name, ProxmoxvePublisherArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ProxmoxvePublisher(java.lang.String name, ProxmoxvePublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("netskope-publisher:index:ProxmoxvePublisher", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static ProxmoxvePublisherArgs makeArgs(ProxmoxvePublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProxmoxvePublisherArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/johnneerdael/pulumi-netskope-publisher")
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
