// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.netskopepublisher.provider.inputs.NetskopeOAuth2ArgsArgs;
import com.pulumi.netskopepublisher.provider.inputs.PublisherAssignmentInputArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TagPublisherAssignmentArgs extends com.pulumi.resources.ResourceArgs {

    public static final TagPublisherAssignmentArgs Empty = new TagPublisherAssignmentArgs();

    @Import(name="apiToken")
    private @Nullable Output<String> apiToken;

    public Optional<Output<String>> apiToken() {
        return Optional.ofNullable(this.apiToken);
    }

    @Import(name="appTags", required=true)
    private Output<List<String>> appTags;

    public Output<List<String>> appTags() {
        return this.appTags;
    }

    @Import(name="authMode")
    private @Nullable Output<String> authMode;

    public Optional<Output<String>> authMode() {
        return Optional.ofNullable(this.authMode);
    }

    @Import(name="bearerToken")
    private @Nullable Output<String> bearerToken;

    public Optional<Output<String>> bearerToken() {
        return Optional.ofNullable(this.bearerToken);
    }

    @Import(name="matchMode")
    private @Nullable Output<String> matchMode;

    public Optional<Output<String>> matchMode() {
        return Optional.ofNullable(this.matchMode);
    }

    @Import(name="oauth2")
    private @Nullable Output<NetskopeOAuth2ArgsArgs> oauth2;

    public Optional<Output<NetskopeOAuth2ArgsArgs>> oauth2() {
        return Optional.ofNullable(this.oauth2);
    }

    @Import(name="publisherPlacementLabels", required=true)
    private Output<List<String>> publisherPlacementLabels;

    public Output<List<String>> publisherPlacementLabels() {
        return this.publisherPlacementLabels;
    }

    @Import(name="publishers", required=true)
    private Output<Map<String,PublisherAssignmentInputArgs>> publishers;

    public Output<Map<String,PublisherAssignmentInputArgs>> publishers() {
        return this.publishers;
    }

    @Import(name="tenantUrl", required=true)
    private Output<String> tenantUrl;

    public Output<String> tenantUrl() {
        return this.tenantUrl;
    }

    private TagPublisherAssignmentArgs() {}

    private TagPublisherAssignmentArgs(TagPublisherAssignmentArgs $) {
        this.apiToken = $.apiToken;
        this.appTags = $.appTags;
        this.authMode = $.authMode;
        this.bearerToken = $.bearerToken;
        this.matchMode = $.matchMode;
        this.oauth2 = $.oauth2;
        this.publisherPlacementLabels = $.publisherPlacementLabels;
        this.publishers = $.publishers;
        this.tenantUrl = $.tenantUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TagPublisherAssignmentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TagPublisherAssignmentArgs $;

        public Builder() {
            $ = new TagPublisherAssignmentArgs();
        }

        public Builder(TagPublisherAssignmentArgs defaults) {
            $ = new TagPublisherAssignmentArgs(Objects.requireNonNull(defaults));
        }

        public Builder apiToken(@Nullable Output<String> apiToken) {
            $.apiToken = apiToken;
            return this;
        }

        public Builder apiToken(String apiToken) {
            return apiToken(Output.of(apiToken));
        }

        public Builder appTags(Output<List<String>> appTags) {
            $.appTags = appTags;
            return this;
        }

        public Builder appTags(List<String> appTags) {
            return appTags(Output.of(appTags));
        }

        public Builder appTags(String... appTags) {
            return appTags(List.of(appTags));
        }

        public Builder authMode(@Nullable Output<String> authMode) {
            $.authMode = authMode;
            return this;
        }

        public Builder authMode(String authMode) {
            return authMode(Output.of(authMode));
        }

        public Builder bearerToken(@Nullable Output<String> bearerToken) {
            $.bearerToken = bearerToken;
            return this;
        }

        public Builder bearerToken(String bearerToken) {
            return bearerToken(Output.of(bearerToken));
        }

        public Builder matchMode(@Nullable Output<String> matchMode) {
            $.matchMode = matchMode;
            return this;
        }

        public Builder matchMode(String matchMode) {
            return matchMode(Output.of(matchMode));
        }

        public Builder oauth2(@Nullable Output<NetskopeOAuth2ArgsArgs> oauth2) {
            $.oauth2 = oauth2;
            return this;
        }

        public Builder oauth2(NetskopeOAuth2ArgsArgs oauth2) {
            return oauth2(Output.of(oauth2));
        }

        public Builder publisherPlacementLabels(Output<List<String>> publisherPlacementLabels) {
            $.publisherPlacementLabels = publisherPlacementLabels;
            return this;
        }

        public Builder publisherPlacementLabels(List<String> publisherPlacementLabels) {
            return publisherPlacementLabels(Output.of(publisherPlacementLabels));
        }

        public Builder publisherPlacementLabels(String... publisherPlacementLabels) {
            return publisherPlacementLabels(List.of(publisherPlacementLabels));
        }

        public Builder publishers(Output<Map<String,PublisherAssignmentInputArgs>> publishers) {
            $.publishers = publishers;
            return this;
        }

        public Builder publishers(Map<String,PublisherAssignmentInputArgs> publishers) {
            return publishers(Output.of(publishers));
        }

        public Builder tenantUrl(Output<String> tenantUrl) {
            $.tenantUrl = tenantUrl;
            return this;
        }

        public Builder tenantUrl(String tenantUrl) {
            return tenantUrl(Output.of(tenantUrl));
        }

        public TagPublisherAssignmentArgs build() {
            if ($.appTags == null) {
                throw new MissingRequiredPropertyException("TagPublisherAssignmentArgs", "appTags");
            }
            if ($.publisherPlacementLabels == null) {
                throw new MissingRequiredPropertyException("TagPublisherAssignmentArgs", "publisherPlacementLabels");
            }
            if ($.publishers == null) {
                throw new MissingRequiredPropertyException("TagPublisherAssignmentArgs", "publishers");
            }
            if ($.tenantUrl == null) {
                throw new MissingRequiredPropertyException("TagPublisherAssignmentArgs", "tenantUrl");
            }
            return $;
        }
    }

}
