// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.netskopepublisher.Utilities;
import com.pulumi.netskopepublisher.VultrPublisherArgs;
import com.pulumi.netskopepublisher.provider.outputs.GuestNetworkInterface;
import com.pulumi.netskopepublisher.provider.outputs.NetskopeOAuth2Args;
import com.pulumi.netskopepublisher.provider.outputs.PublisherRegistrationInput;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="netskope-publisher:index:VultrPublisher")
public class VultrPublisher extends com.pulumi.resources.ComponentResource {
    @Export(name="apiToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> apiToken;

    public Output<Optional<String>> apiToken() {
        return Codegen.optional(this.apiToken);
    }
    @Export(name="authMode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> authMode;

    public Output<Optional<String>> authMode() {
        return Codegen.optional(this.authMode);
    }
    @Export(name="bearerToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> bearerToken;

    public Output<Optional<String>> bearerToken() {
        return Codegen.optional(this.bearerToken);
    }
    @Export(name="bootstrap", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> bootstrap;

    public Output<Optional<Boolean>> bootstrap() {
        return Codegen.optional(this.bootstrap);
    }
    @Export(name="bootstrapUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> bootstrapUrl;

    public Output<Optional<String>> bootstrapUrl() {
        return Codegen.optional(this.bootstrapUrl);
    }
    @Export(name="deleteDefaultUser", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> deleteDefaultUser;

    public Output<Optional<Boolean>> deleteDefaultUser() {
        return Codegen.optional(this.deleteDefaultUser);
    }
    @Export(name="enableIpv6", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableIpv6;

    public Output<Optional<Boolean>> enableIpv6() {
        return Codegen.optional(this.enableIpv6);
    }
    @Export(name="firewallGroupId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> firewallGroupId;

    public Output<Optional<String>> firewallGroupId() {
        return Codegen.optional(this.firewallGroupId);
    }
    @Export(name="guestNetworkInterface", refs={GuestNetworkInterface.class}, tree="[0]")
    private Output</* @Nullable */ GuestNetworkInterface> guestNetworkInterface;

    public Output<Optional<GuestNetworkInterface>> guestNetworkInterface() {
        return Codegen.optional(this.guestNetworkInterface);
    }
    @Export(name="imageId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> imageId;

    public Output<Optional<String>> imageId() {
        return Codegen.optional(this.imageId);
    }
    @Export(name="installUser", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUser;

    public Output<Optional<String>> installUser() {
        return Codegen.optional(this.installUser);
    }
    @Export(name="installUserPassword", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> installUserPassword;

    public Output<Optional<String>> installUserPassword() {
        return Codegen.optional(this.installUserPassword);
    }
    @Export(name="installUserPasswordIsHash", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> installUserPasswordIsHash;

    public Output<Optional<Boolean>> installUserPasswordIsHash() {
        return Codegen.optional(this.installUserPasswordIsHash);
    }
    @Export(name="installUserSshAuthorizedKeys", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> installUserSshAuthorizedKeys;

    public Output<Optional<List<String>>> installUserSshAuthorizedKeys() {
        return Codegen.optional(this.installUserSshAuthorizedKeys);
    }
    @Export(name="namePrefix", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namePrefix;

    public Output<Optional<String>> namePrefix() {
        return Codegen.optional(this.namePrefix);
    }
    @Export(name="names", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> names;

    public Output<Optional<List<String>>> names() {
        return Codegen.optional(this.names);
    }
    @Export(name="nonat", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> nonat;

    public Output<Optional<Boolean>> nonat() {
        return Codegen.optional(this.nonat);
    }
    @Export(name="oauth2", refs={NetskopeOAuth2Args.class}, tree="[0]")
    private Output</* @Nullable */ NetskopeOAuth2Args> oauth2;

    public Output<Optional<NetskopeOAuth2Args>> oauth2() {
        return Codegen.optional(this.oauth2);
    }
    @Export(name="osId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> osId;

    public Output<Optional<Integer>> osId() {
        return Codegen.optional(this.osId);
    }
    @Export(name="plan", refs={String.class}, tree="[0]")
    private Output<String> plan;

    public Output<String> plan() {
        return this.plan;
    }
    @Export(name="publisherNames", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> publisherNames;

    public Output<List<String>> publisherNames() {
        return this.publisherNames;
    }
    @Export(name="publishers", refs={Map.class,String.class,Object.class}, tree="[0,1,2]")
    private Output<Map<String,Object>> publishers;

    public Output<Map<String,Object>> publishers() {
        return this.publishers;
    }
    @Export(name="region", refs={String.class}, tree="[0]")
    private Output<String> region;

    public Output<String> region() {
        return this.region;
    }
    @Export(name="registrations", refs={Map.class,String.class,PublisherRegistrationInput.class}, tree="[0,1,2]")
    private Output</* @Nullable */ Map<String,PublisherRegistrationInput>> registrations;

    public Output<Optional<Map<String,PublisherRegistrationInput>>> registrations() {
        return Codegen.optional(this.registrations);
    }
    @Export(name="replicas", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> replicas;

    public Output<Optional<Integer>> replicas() {
        return Codegen.optional(this.replicas);
    }
    @Export(name="sshKeyIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> sshKeyIds;

    public Output<Optional<List<String>>> sshKeyIds() {
        return Codegen.optional(this.sshKeyIds);
    }
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    @Export(name="tenantUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenantUrl;

    public Output<Optional<String>> tenantUrl() {
        return Codegen.optional(this.tenantUrl);
    }
    @Export(name="vpc2Ids", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> vpc2Ids;

    public Output<Optional<List<String>>> vpc2Ids() {
        return Codegen.optional(this.vpc2Ids);
    }
    @Export(name="wizardPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> wizardPath;

    public Output<Optional<String>> wizardPath() {
        return Codegen.optional(this.wizardPath);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public VultrPublisher(java.lang.String name) {
        this(name, VultrPublisherArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public VultrPublisher(java.lang.String name, VultrPublisherArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public VultrPublisher(java.lang.String name, VultrPublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("netskope-publisher:index:VultrPublisher", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static VultrPublisherArgs makeArgs(VultrPublisherArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? VultrPublisherArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/johnneerdael/pulumi-netskope-publisher")
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
