// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher.Types.Inputs
{

    public sealed class NetskopeOAuth2ArgsArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        [Input("clientSecret", required: true)]
        private Input<string>? _clientSecret;
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("scope")]
        public Input<string>? Scope { get; set; }

        [Input("tokenUrl", required: true)]
        public Input<string> TokenUrl { get; set; } = null!;

        public NetskopeOAuth2ArgsArgs()
        {
        }
        public static new NetskopeOAuth2ArgsArgs Empty => new NetskopeOAuth2ArgsArgs();
    }
}
