// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"context"
	"reflect"

	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AzureMarketplaceImage struct {
	Offer     string  `pulumi:"offer"`
	Publisher string  `pulumi:"publisher"`
	Sku       string  `pulumi:"sku"`
	Version   *string `pulumi:"version"`
}

// AzureMarketplaceImageInput is an input type that accepts AzureMarketplaceImageArgs and AzureMarketplaceImageOutput values.
// You can construct a concrete instance of `AzureMarketplaceImageInput` via:
//
//	AzureMarketplaceImageArgs{...}
type AzureMarketplaceImageInput interface {
	pulumi.Input

	ToAzureMarketplaceImageOutput() AzureMarketplaceImageOutput
	ToAzureMarketplaceImageOutputWithContext(context.Context) AzureMarketplaceImageOutput
}

type AzureMarketplaceImageArgs struct {
	Offer     pulumi.StringInput    `pulumi:"offer"`
	Publisher pulumi.StringInput    `pulumi:"publisher"`
	Sku       pulumi.StringInput    `pulumi:"sku"`
	Version   pulumi.StringPtrInput `pulumi:"version"`
}

func (AzureMarketplaceImageArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureMarketplaceImage)(nil)).Elem()
}

func (i AzureMarketplaceImageArgs) ToAzureMarketplaceImageOutput() AzureMarketplaceImageOutput {
	return i.ToAzureMarketplaceImageOutputWithContext(context.Background())
}

func (i AzureMarketplaceImageArgs) ToAzureMarketplaceImageOutputWithContext(ctx context.Context) AzureMarketplaceImageOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMarketplaceImageOutput)
}

func (i AzureMarketplaceImageArgs) ToAzureMarketplaceImagePtrOutput() AzureMarketplaceImagePtrOutput {
	return i.ToAzureMarketplaceImagePtrOutputWithContext(context.Background())
}

func (i AzureMarketplaceImageArgs) ToAzureMarketplaceImagePtrOutputWithContext(ctx context.Context) AzureMarketplaceImagePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMarketplaceImageOutput).ToAzureMarketplaceImagePtrOutputWithContext(ctx)
}

// AzureMarketplaceImagePtrInput is an input type that accepts AzureMarketplaceImageArgs, AzureMarketplaceImagePtr and AzureMarketplaceImagePtrOutput values.
// You can construct a concrete instance of `AzureMarketplaceImagePtrInput` via:
//
//	        AzureMarketplaceImageArgs{...}
//
//	or:
//
//	        nil
type AzureMarketplaceImagePtrInput interface {
	pulumi.Input

	ToAzureMarketplaceImagePtrOutput() AzureMarketplaceImagePtrOutput
	ToAzureMarketplaceImagePtrOutputWithContext(context.Context) AzureMarketplaceImagePtrOutput
}

type azureMarketplaceImagePtrType AzureMarketplaceImageArgs

func AzureMarketplaceImagePtr(v *AzureMarketplaceImageArgs) AzureMarketplaceImagePtrInput {
	return (*azureMarketplaceImagePtrType)(v)
}

func (*azureMarketplaceImagePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMarketplaceImage)(nil)).Elem()
}

func (i *azureMarketplaceImagePtrType) ToAzureMarketplaceImagePtrOutput() AzureMarketplaceImagePtrOutput {
	return i.ToAzureMarketplaceImagePtrOutputWithContext(context.Background())
}

func (i *azureMarketplaceImagePtrType) ToAzureMarketplaceImagePtrOutputWithContext(ctx context.Context) AzureMarketplaceImagePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureMarketplaceImagePtrOutput)
}

type AzureMarketplaceImageOutput struct{ *pulumi.OutputState }

func (AzureMarketplaceImageOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureMarketplaceImage)(nil)).Elem()
}

func (o AzureMarketplaceImageOutput) ToAzureMarketplaceImageOutput() AzureMarketplaceImageOutput {
	return o
}

func (o AzureMarketplaceImageOutput) ToAzureMarketplaceImageOutputWithContext(ctx context.Context) AzureMarketplaceImageOutput {
	return o
}

func (o AzureMarketplaceImageOutput) ToAzureMarketplaceImagePtrOutput() AzureMarketplaceImagePtrOutput {
	return o.ToAzureMarketplaceImagePtrOutputWithContext(context.Background())
}

func (o AzureMarketplaceImageOutput) ToAzureMarketplaceImagePtrOutputWithContext(ctx context.Context) AzureMarketplaceImagePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AzureMarketplaceImage) *AzureMarketplaceImage {
		return &v
	}).(AzureMarketplaceImagePtrOutput)
}

func (o AzureMarketplaceImageOutput) Offer() pulumi.StringOutput {
	return o.ApplyT(func(v AzureMarketplaceImage) string { return v.Offer }).(pulumi.StringOutput)
}

func (o AzureMarketplaceImageOutput) Publisher() pulumi.StringOutput {
	return o.ApplyT(func(v AzureMarketplaceImage) string { return v.Publisher }).(pulumi.StringOutput)
}

func (o AzureMarketplaceImageOutput) Sku() pulumi.StringOutput {
	return o.ApplyT(func(v AzureMarketplaceImage) string { return v.Sku }).(pulumi.StringOutput)
}

func (o AzureMarketplaceImageOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AzureMarketplaceImage) *string { return v.Version }).(pulumi.StringPtrOutput)
}

type AzureMarketplaceImagePtrOutput struct{ *pulumi.OutputState }

func (AzureMarketplaceImagePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureMarketplaceImage)(nil)).Elem()
}

func (o AzureMarketplaceImagePtrOutput) ToAzureMarketplaceImagePtrOutput() AzureMarketplaceImagePtrOutput {
	return o
}

func (o AzureMarketplaceImagePtrOutput) ToAzureMarketplaceImagePtrOutputWithContext(ctx context.Context) AzureMarketplaceImagePtrOutput {
	return o
}

func (o AzureMarketplaceImagePtrOutput) Elem() AzureMarketplaceImageOutput {
	return o.ApplyT(func(v *AzureMarketplaceImage) AzureMarketplaceImage {
		if v != nil {
			return *v
		}
		var ret AzureMarketplaceImage
		return ret
	}).(AzureMarketplaceImageOutput)
}

func (o AzureMarketplaceImagePtrOutput) Offer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMarketplaceImage) *string {
		if v == nil {
			return nil
		}
		return &v.Offer
	}).(pulumi.StringPtrOutput)
}

func (o AzureMarketplaceImagePtrOutput) Publisher() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMarketplaceImage) *string {
		if v == nil {
			return nil
		}
		return &v.Publisher
	}).(pulumi.StringPtrOutput)
}

func (o AzureMarketplaceImagePtrOutput) Sku() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMarketplaceImage) *string {
		if v == nil {
			return nil
		}
		return &v.Sku
	}).(pulumi.StringPtrOutput)
}

func (o AzureMarketplaceImagePtrOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureMarketplaceImage) *string {
		if v == nil {
			return nil
		}
		return v.Version
	}).(pulumi.StringPtrOutput)
}

type AzureOsDisk struct {
	SizeGb *int    `pulumi:"sizeGb"`
	Type   *string `pulumi:"type"`
}

// AzureOsDiskInput is an input type that accepts AzureOsDiskArgs and AzureOsDiskOutput values.
// You can construct a concrete instance of `AzureOsDiskInput` via:
//
//	AzureOsDiskArgs{...}
type AzureOsDiskInput interface {
	pulumi.Input

	ToAzureOsDiskOutput() AzureOsDiskOutput
	ToAzureOsDiskOutputWithContext(context.Context) AzureOsDiskOutput
}

type AzureOsDiskArgs struct {
	SizeGb pulumi.IntPtrInput    `pulumi:"sizeGb"`
	Type   pulumi.StringPtrInput `pulumi:"type"`
}

func (AzureOsDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureOsDisk)(nil)).Elem()
}

func (i AzureOsDiskArgs) ToAzureOsDiskOutput() AzureOsDiskOutput {
	return i.ToAzureOsDiskOutputWithContext(context.Background())
}

func (i AzureOsDiskArgs) ToAzureOsDiskOutputWithContext(ctx context.Context) AzureOsDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOsDiskOutput)
}

func (i AzureOsDiskArgs) ToAzureOsDiskPtrOutput() AzureOsDiskPtrOutput {
	return i.ToAzureOsDiskPtrOutputWithContext(context.Background())
}

func (i AzureOsDiskArgs) ToAzureOsDiskPtrOutputWithContext(ctx context.Context) AzureOsDiskPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOsDiskOutput).ToAzureOsDiskPtrOutputWithContext(ctx)
}

// AzureOsDiskPtrInput is an input type that accepts AzureOsDiskArgs, AzureOsDiskPtr and AzureOsDiskPtrOutput values.
// You can construct a concrete instance of `AzureOsDiskPtrInput` via:
//
//	        AzureOsDiskArgs{...}
//
//	or:
//
//	        nil
type AzureOsDiskPtrInput interface {
	pulumi.Input

	ToAzureOsDiskPtrOutput() AzureOsDiskPtrOutput
	ToAzureOsDiskPtrOutputWithContext(context.Context) AzureOsDiskPtrOutput
}

type azureOsDiskPtrType AzureOsDiskArgs

func AzureOsDiskPtr(v *AzureOsDiskArgs) AzureOsDiskPtrInput {
	return (*azureOsDiskPtrType)(v)
}

func (*azureOsDiskPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOsDisk)(nil)).Elem()
}

func (i *azureOsDiskPtrType) ToAzureOsDiskPtrOutput() AzureOsDiskPtrOutput {
	return i.ToAzureOsDiskPtrOutputWithContext(context.Background())
}

func (i *azureOsDiskPtrType) ToAzureOsDiskPtrOutputWithContext(ctx context.Context) AzureOsDiskPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AzureOsDiskPtrOutput)
}

type AzureOsDiskOutput struct{ *pulumi.OutputState }

func (AzureOsDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AzureOsDisk)(nil)).Elem()
}

func (o AzureOsDiskOutput) ToAzureOsDiskOutput() AzureOsDiskOutput {
	return o
}

func (o AzureOsDiskOutput) ToAzureOsDiskOutputWithContext(ctx context.Context) AzureOsDiskOutput {
	return o
}

func (o AzureOsDiskOutput) ToAzureOsDiskPtrOutput() AzureOsDiskPtrOutput {
	return o.ToAzureOsDiskPtrOutputWithContext(context.Background())
}

func (o AzureOsDiskOutput) ToAzureOsDiskPtrOutputWithContext(ctx context.Context) AzureOsDiskPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AzureOsDisk) *AzureOsDisk {
		return &v
	}).(AzureOsDiskPtrOutput)
}

func (o AzureOsDiskOutput) SizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v AzureOsDisk) *int { return v.SizeGb }).(pulumi.IntPtrOutput)
}

func (o AzureOsDiskOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AzureOsDisk) *string { return v.Type }).(pulumi.StringPtrOutput)
}

type AzureOsDiskPtrOutput struct{ *pulumi.OutputState }

func (AzureOsDiskPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AzureOsDisk)(nil)).Elem()
}

func (o AzureOsDiskPtrOutput) ToAzureOsDiskPtrOutput() AzureOsDiskPtrOutput {
	return o
}

func (o AzureOsDiskPtrOutput) ToAzureOsDiskPtrOutputWithContext(ctx context.Context) AzureOsDiskPtrOutput {
	return o
}

func (o AzureOsDiskPtrOutput) Elem() AzureOsDiskOutput {
	return o.ApplyT(func(v *AzureOsDisk) AzureOsDisk {
		if v != nil {
			return *v
		}
		var ret AzureOsDisk
		return ret
	}).(AzureOsDiskOutput)
}

func (o AzureOsDiskPtrOutput) SizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AzureOsDisk) *int {
		if v == nil {
			return nil
		}
		return v.SizeGb
	}).(pulumi.IntPtrOutput)
}

func (o AzureOsDiskPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AzureOsDisk) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

type GcpServiceAccount struct {
	Email  string   `pulumi:"email"`
	Scopes []string `pulumi:"scopes"`
}

// GcpServiceAccountInput is an input type that accepts GcpServiceAccountArgs and GcpServiceAccountOutput values.
// You can construct a concrete instance of `GcpServiceAccountInput` via:
//
//	GcpServiceAccountArgs{...}
type GcpServiceAccountInput interface {
	pulumi.Input

	ToGcpServiceAccountOutput() GcpServiceAccountOutput
	ToGcpServiceAccountOutputWithContext(context.Context) GcpServiceAccountOutput
}

type GcpServiceAccountArgs struct {
	Email  pulumi.StringInput      `pulumi:"email"`
	Scopes pulumi.StringArrayInput `pulumi:"scopes"`
}

func (GcpServiceAccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GcpServiceAccount)(nil)).Elem()
}

func (i GcpServiceAccountArgs) ToGcpServiceAccountOutput() GcpServiceAccountOutput {
	return i.ToGcpServiceAccountOutputWithContext(context.Background())
}

func (i GcpServiceAccountArgs) ToGcpServiceAccountOutputWithContext(ctx context.Context) GcpServiceAccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpServiceAccountOutput)
}

func (i GcpServiceAccountArgs) ToGcpServiceAccountPtrOutput() GcpServiceAccountPtrOutput {
	return i.ToGcpServiceAccountPtrOutputWithContext(context.Background())
}

func (i GcpServiceAccountArgs) ToGcpServiceAccountPtrOutputWithContext(ctx context.Context) GcpServiceAccountPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpServiceAccountOutput).ToGcpServiceAccountPtrOutputWithContext(ctx)
}

// GcpServiceAccountPtrInput is an input type that accepts GcpServiceAccountArgs, GcpServiceAccountPtr and GcpServiceAccountPtrOutput values.
// You can construct a concrete instance of `GcpServiceAccountPtrInput` via:
//
//	        GcpServiceAccountArgs{...}
//
//	or:
//
//	        nil
type GcpServiceAccountPtrInput interface {
	pulumi.Input

	ToGcpServiceAccountPtrOutput() GcpServiceAccountPtrOutput
	ToGcpServiceAccountPtrOutputWithContext(context.Context) GcpServiceAccountPtrOutput
}

type gcpServiceAccountPtrType GcpServiceAccountArgs

func GcpServiceAccountPtr(v *GcpServiceAccountArgs) GcpServiceAccountPtrInput {
	return (*gcpServiceAccountPtrType)(v)
}

func (*gcpServiceAccountPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GcpServiceAccount)(nil)).Elem()
}

func (i *gcpServiceAccountPtrType) ToGcpServiceAccountPtrOutput() GcpServiceAccountPtrOutput {
	return i.ToGcpServiceAccountPtrOutputWithContext(context.Background())
}

func (i *gcpServiceAccountPtrType) ToGcpServiceAccountPtrOutputWithContext(ctx context.Context) GcpServiceAccountPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GcpServiceAccountPtrOutput)
}

type GcpServiceAccountOutput struct{ *pulumi.OutputState }

func (GcpServiceAccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GcpServiceAccount)(nil)).Elem()
}

func (o GcpServiceAccountOutput) ToGcpServiceAccountOutput() GcpServiceAccountOutput {
	return o
}

func (o GcpServiceAccountOutput) ToGcpServiceAccountOutputWithContext(ctx context.Context) GcpServiceAccountOutput {
	return o
}

func (o GcpServiceAccountOutput) ToGcpServiceAccountPtrOutput() GcpServiceAccountPtrOutput {
	return o.ToGcpServiceAccountPtrOutputWithContext(context.Background())
}

func (o GcpServiceAccountOutput) ToGcpServiceAccountPtrOutputWithContext(ctx context.Context) GcpServiceAccountPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GcpServiceAccount) *GcpServiceAccount {
		return &v
	}).(GcpServiceAccountPtrOutput)
}

func (o GcpServiceAccountOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v GcpServiceAccount) string { return v.Email }).(pulumi.StringOutput)
}

func (o GcpServiceAccountOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GcpServiceAccount) []string { return v.Scopes }).(pulumi.StringArrayOutput)
}

type GcpServiceAccountPtrOutput struct{ *pulumi.OutputState }

func (GcpServiceAccountPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GcpServiceAccount)(nil)).Elem()
}

func (o GcpServiceAccountPtrOutput) ToGcpServiceAccountPtrOutput() GcpServiceAccountPtrOutput {
	return o
}

func (o GcpServiceAccountPtrOutput) ToGcpServiceAccountPtrOutputWithContext(ctx context.Context) GcpServiceAccountPtrOutput {
	return o
}

func (o GcpServiceAccountPtrOutput) Elem() GcpServiceAccountOutput {
	return o.ApplyT(func(v *GcpServiceAccount) GcpServiceAccount {
		if v != nil {
			return *v
		}
		var ret GcpServiceAccount
		return ret
	}).(GcpServiceAccountOutput)
}

func (o GcpServiceAccountPtrOutput) Email() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GcpServiceAccount) *string {
		if v == nil {
			return nil
		}
		return &v.Email
	}).(pulumi.StringPtrOutput)
}

func (o GcpServiceAccountPtrOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GcpServiceAccount) []string {
		if v == nil {
			return nil
		}
		return v.Scopes
	}).(pulumi.StringArrayOutput)
}

type GuestNetworkInterface struct {
	Addresses   []string `pulumi:"addresses"`
	Dhcp4       *bool    `pulumi:"dhcp4"`
	Gateway4    *string  `pulumi:"gateway4"`
	Mtu         *int     `pulumi:"mtu"`
	Name        string   `pulumi:"name"`
	Nameservers []string `pulumi:"nameservers"`
}

// GuestNetworkInterfaceInput is an input type that accepts GuestNetworkInterfaceArgs and GuestNetworkInterfaceOutput values.
// You can construct a concrete instance of `GuestNetworkInterfaceInput` via:
//
//	GuestNetworkInterfaceArgs{...}
type GuestNetworkInterfaceInput interface {
	pulumi.Input

	ToGuestNetworkInterfaceOutput() GuestNetworkInterfaceOutput
	ToGuestNetworkInterfaceOutputWithContext(context.Context) GuestNetworkInterfaceOutput
}

type GuestNetworkInterfaceArgs struct {
	Addresses   pulumi.StringArrayInput `pulumi:"addresses"`
	Dhcp4       pulumi.BoolPtrInput     `pulumi:"dhcp4"`
	Gateway4    pulumi.StringPtrInput   `pulumi:"gateway4"`
	Mtu         pulumi.IntPtrInput      `pulumi:"mtu"`
	Name        pulumi.StringInput      `pulumi:"name"`
	Nameservers pulumi.StringArrayInput `pulumi:"nameservers"`
}

func (GuestNetworkInterfaceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GuestNetworkInterface)(nil)).Elem()
}

func (i GuestNetworkInterfaceArgs) ToGuestNetworkInterfaceOutput() GuestNetworkInterfaceOutput {
	return i.ToGuestNetworkInterfaceOutputWithContext(context.Background())
}

func (i GuestNetworkInterfaceArgs) ToGuestNetworkInterfaceOutputWithContext(ctx context.Context) GuestNetworkInterfaceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GuestNetworkInterfaceOutput)
}

func (i GuestNetworkInterfaceArgs) ToGuestNetworkInterfacePtrOutput() GuestNetworkInterfacePtrOutput {
	return i.ToGuestNetworkInterfacePtrOutputWithContext(context.Background())
}

func (i GuestNetworkInterfaceArgs) ToGuestNetworkInterfacePtrOutputWithContext(ctx context.Context) GuestNetworkInterfacePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GuestNetworkInterfaceOutput).ToGuestNetworkInterfacePtrOutputWithContext(ctx)
}

// GuestNetworkInterfacePtrInput is an input type that accepts GuestNetworkInterfaceArgs, GuestNetworkInterfacePtr and GuestNetworkInterfacePtrOutput values.
// You can construct a concrete instance of `GuestNetworkInterfacePtrInput` via:
//
//	        GuestNetworkInterfaceArgs{...}
//
//	or:
//
//	        nil
type GuestNetworkInterfacePtrInput interface {
	pulumi.Input

	ToGuestNetworkInterfacePtrOutput() GuestNetworkInterfacePtrOutput
	ToGuestNetworkInterfacePtrOutputWithContext(context.Context) GuestNetworkInterfacePtrOutput
}

type guestNetworkInterfacePtrType GuestNetworkInterfaceArgs

func GuestNetworkInterfacePtr(v *GuestNetworkInterfaceArgs) GuestNetworkInterfacePtrInput {
	return (*guestNetworkInterfacePtrType)(v)
}

func (*guestNetworkInterfacePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**GuestNetworkInterface)(nil)).Elem()
}

func (i *guestNetworkInterfacePtrType) ToGuestNetworkInterfacePtrOutput() GuestNetworkInterfacePtrOutput {
	return i.ToGuestNetworkInterfacePtrOutputWithContext(context.Background())
}

func (i *guestNetworkInterfacePtrType) ToGuestNetworkInterfacePtrOutputWithContext(ctx context.Context) GuestNetworkInterfacePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GuestNetworkInterfacePtrOutput)
}

type GuestNetworkInterfaceOutput struct{ *pulumi.OutputState }

func (GuestNetworkInterfaceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GuestNetworkInterface)(nil)).Elem()
}

func (o GuestNetworkInterfaceOutput) ToGuestNetworkInterfaceOutput() GuestNetworkInterfaceOutput {
	return o
}

func (o GuestNetworkInterfaceOutput) ToGuestNetworkInterfaceOutputWithContext(ctx context.Context) GuestNetworkInterfaceOutput {
	return o
}

func (o GuestNetworkInterfaceOutput) ToGuestNetworkInterfacePtrOutput() GuestNetworkInterfacePtrOutput {
	return o.ToGuestNetworkInterfacePtrOutputWithContext(context.Background())
}

func (o GuestNetworkInterfaceOutput) ToGuestNetworkInterfacePtrOutputWithContext(ctx context.Context) GuestNetworkInterfacePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v GuestNetworkInterface) *GuestNetworkInterface {
		return &v
	}).(GuestNetworkInterfacePtrOutput)
}

func (o GuestNetworkInterfaceOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GuestNetworkInterface) []string { return v.Addresses }).(pulumi.StringArrayOutput)
}

func (o GuestNetworkInterfaceOutput) Dhcp4() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GuestNetworkInterface) *bool { return v.Dhcp4 }).(pulumi.BoolPtrOutput)
}

func (o GuestNetworkInterfaceOutput) Gateway4() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GuestNetworkInterface) *string { return v.Gateway4 }).(pulumi.StringPtrOutput)
}

func (o GuestNetworkInterfaceOutput) Mtu() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GuestNetworkInterface) *int { return v.Mtu }).(pulumi.IntPtrOutput)
}

func (o GuestNetworkInterfaceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GuestNetworkInterface) string { return v.Name }).(pulumi.StringOutput)
}

func (o GuestNetworkInterfaceOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GuestNetworkInterface) []string { return v.Nameservers }).(pulumi.StringArrayOutput)
}

type GuestNetworkInterfacePtrOutput struct{ *pulumi.OutputState }

func (GuestNetworkInterfacePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GuestNetworkInterface)(nil)).Elem()
}

func (o GuestNetworkInterfacePtrOutput) ToGuestNetworkInterfacePtrOutput() GuestNetworkInterfacePtrOutput {
	return o
}

func (o GuestNetworkInterfacePtrOutput) ToGuestNetworkInterfacePtrOutputWithContext(ctx context.Context) GuestNetworkInterfacePtrOutput {
	return o
}

func (o GuestNetworkInterfacePtrOutput) Elem() GuestNetworkInterfaceOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) GuestNetworkInterface {
		if v != nil {
			return *v
		}
		var ret GuestNetworkInterface
		return ret
	}).(GuestNetworkInterfaceOutput)
}

func (o GuestNetworkInterfacePtrOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) []string {
		if v == nil {
			return nil
		}
		return v.Addresses
	}).(pulumi.StringArrayOutput)
}

func (o GuestNetworkInterfacePtrOutput) Dhcp4() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) *bool {
		if v == nil {
			return nil
		}
		return v.Dhcp4
	}).(pulumi.BoolPtrOutput)
}

func (o GuestNetworkInterfacePtrOutput) Gateway4() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) *string {
		if v == nil {
			return nil
		}
		return v.Gateway4
	}).(pulumi.StringPtrOutput)
}

func (o GuestNetworkInterfacePtrOutput) Mtu() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) *int {
		if v == nil {
			return nil
		}
		return v.Mtu
	}).(pulumi.IntPtrOutput)
}

func (o GuestNetworkInterfacePtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

func (o GuestNetworkInterfacePtrOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *GuestNetworkInterface) []string {
		if v == nil {
			return nil
		}
		return v.Nameservers
	}).(pulumi.StringArrayOutput)
}

type HypervHardDrive struct {
	ControllerLocation *int    `pulumi:"controllerLocation"`
	ControllerNumber   *int    `pulumi:"controllerNumber"`
	ControllerType     *string `pulumi:"controllerType"`
	Path               string  `pulumi:"path"`
}

// HypervHardDriveInput is an input type that accepts HypervHardDriveArgs and HypervHardDriveOutput values.
// You can construct a concrete instance of `HypervHardDriveInput` via:
//
//	HypervHardDriveArgs{...}
type HypervHardDriveInput interface {
	pulumi.Input

	ToHypervHardDriveOutput() HypervHardDriveOutput
	ToHypervHardDriveOutputWithContext(context.Context) HypervHardDriveOutput
}

type HypervHardDriveArgs struct {
	ControllerLocation pulumi.IntPtrInput    `pulumi:"controllerLocation"`
	ControllerNumber   pulumi.IntPtrInput    `pulumi:"controllerNumber"`
	ControllerType     pulumi.StringPtrInput `pulumi:"controllerType"`
	Path               pulumi.StringInput    `pulumi:"path"`
}

func (HypervHardDriveArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*HypervHardDrive)(nil)).Elem()
}

func (i HypervHardDriveArgs) ToHypervHardDriveOutput() HypervHardDriveOutput {
	return i.ToHypervHardDriveOutputWithContext(context.Background())
}

func (i HypervHardDriveArgs) ToHypervHardDriveOutputWithContext(ctx context.Context) HypervHardDriveOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HypervHardDriveOutput)
}

// HypervHardDriveArrayInput is an input type that accepts HypervHardDriveArray and HypervHardDriveArrayOutput values.
// You can construct a concrete instance of `HypervHardDriveArrayInput` via:
//
//	HypervHardDriveArray{ HypervHardDriveArgs{...} }
type HypervHardDriveArrayInput interface {
	pulumi.Input

	ToHypervHardDriveArrayOutput() HypervHardDriveArrayOutput
	ToHypervHardDriveArrayOutputWithContext(context.Context) HypervHardDriveArrayOutput
}

type HypervHardDriveArray []HypervHardDriveInput

func (HypervHardDriveArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]HypervHardDrive)(nil)).Elem()
}

func (i HypervHardDriveArray) ToHypervHardDriveArrayOutput() HypervHardDriveArrayOutput {
	return i.ToHypervHardDriveArrayOutputWithContext(context.Background())
}

func (i HypervHardDriveArray) ToHypervHardDriveArrayOutputWithContext(ctx context.Context) HypervHardDriveArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HypervHardDriveArrayOutput)
}

type HypervHardDriveOutput struct{ *pulumi.OutputState }

func (HypervHardDriveOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*HypervHardDrive)(nil)).Elem()
}

func (o HypervHardDriveOutput) ToHypervHardDriveOutput() HypervHardDriveOutput {
	return o
}

func (o HypervHardDriveOutput) ToHypervHardDriveOutputWithContext(ctx context.Context) HypervHardDriveOutput {
	return o
}

func (o HypervHardDriveOutput) ControllerLocation() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HypervHardDrive) *int { return v.ControllerLocation }).(pulumi.IntPtrOutput)
}

func (o HypervHardDriveOutput) ControllerNumber() pulumi.IntPtrOutput {
	return o.ApplyT(func(v HypervHardDrive) *int { return v.ControllerNumber }).(pulumi.IntPtrOutput)
}

func (o HypervHardDriveOutput) ControllerType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v HypervHardDrive) *string { return v.ControllerType }).(pulumi.StringPtrOutput)
}

func (o HypervHardDriveOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v HypervHardDrive) string { return v.Path }).(pulumi.StringOutput)
}

type HypervHardDriveArrayOutput struct{ *pulumi.OutputState }

func (HypervHardDriveArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]HypervHardDrive)(nil)).Elem()
}

func (o HypervHardDriveArrayOutput) ToHypervHardDriveArrayOutput() HypervHardDriveArrayOutput {
	return o
}

func (o HypervHardDriveArrayOutput) ToHypervHardDriveArrayOutputWithContext(ctx context.Context) HypervHardDriveArrayOutput {
	return o
}

func (o HypervHardDriveArrayOutput) Index(i pulumi.IntInput) HypervHardDriveOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) HypervHardDrive {
		return vs[0].([]HypervHardDrive)[vs[1].(int)]
	}).(HypervHardDriveOutput)
}

type MetadataOptions struct {
	HttpEndpoint *string `pulumi:"httpEndpoint"`
	HttpTokens   *string `pulumi:"httpTokens"`
}

// MetadataOptionsInput is an input type that accepts MetadataOptionsArgs and MetadataOptionsOutput values.
// You can construct a concrete instance of `MetadataOptionsInput` via:
//
//	MetadataOptionsArgs{...}
type MetadataOptionsInput interface {
	pulumi.Input

	ToMetadataOptionsOutput() MetadataOptionsOutput
	ToMetadataOptionsOutputWithContext(context.Context) MetadataOptionsOutput
}

type MetadataOptionsArgs struct {
	HttpEndpoint pulumi.StringPtrInput `pulumi:"httpEndpoint"`
	HttpTokens   pulumi.StringPtrInput `pulumi:"httpTokens"`
}

func (MetadataOptionsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*MetadataOptions)(nil)).Elem()
}

func (i MetadataOptionsArgs) ToMetadataOptionsOutput() MetadataOptionsOutput {
	return i.ToMetadataOptionsOutputWithContext(context.Background())
}

func (i MetadataOptionsArgs) ToMetadataOptionsOutputWithContext(ctx context.Context) MetadataOptionsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetadataOptionsOutput)
}

func (i MetadataOptionsArgs) ToMetadataOptionsPtrOutput() MetadataOptionsPtrOutput {
	return i.ToMetadataOptionsPtrOutputWithContext(context.Background())
}

func (i MetadataOptionsArgs) ToMetadataOptionsPtrOutputWithContext(ctx context.Context) MetadataOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetadataOptionsOutput).ToMetadataOptionsPtrOutputWithContext(ctx)
}

// MetadataOptionsPtrInput is an input type that accepts MetadataOptionsArgs, MetadataOptionsPtr and MetadataOptionsPtrOutput values.
// You can construct a concrete instance of `MetadataOptionsPtrInput` via:
//
//	        MetadataOptionsArgs{...}
//
//	or:
//
//	        nil
type MetadataOptionsPtrInput interface {
	pulumi.Input

	ToMetadataOptionsPtrOutput() MetadataOptionsPtrOutput
	ToMetadataOptionsPtrOutputWithContext(context.Context) MetadataOptionsPtrOutput
}

type metadataOptionsPtrType MetadataOptionsArgs

func MetadataOptionsPtr(v *MetadataOptionsArgs) MetadataOptionsPtrInput {
	return (*metadataOptionsPtrType)(v)
}

func (*metadataOptionsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**MetadataOptions)(nil)).Elem()
}

func (i *metadataOptionsPtrType) ToMetadataOptionsPtrOutput() MetadataOptionsPtrOutput {
	return i.ToMetadataOptionsPtrOutputWithContext(context.Background())
}

func (i *metadataOptionsPtrType) ToMetadataOptionsPtrOutputWithContext(ctx context.Context) MetadataOptionsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetadataOptionsPtrOutput)
}

type MetadataOptionsOutput struct{ *pulumi.OutputState }

func (MetadataOptionsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MetadataOptions)(nil)).Elem()
}

func (o MetadataOptionsOutput) ToMetadataOptionsOutput() MetadataOptionsOutput {
	return o
}

func (o MetadataOptionsOutput) ToMetadataOptionsOutputWithContext(ctx context.Context) MetadataOptionsOutput {
	return o
}

func (o MetadataOptionsOutput) ToMetadataOptionsPtrOutput() MetadataOptionsPtrOutput {
	return o.ToMetadataOptionsPtrOutputWithContext(context.Background())
}

func (o MetadataOptionsOutput) ToMetadataOptionsPtrOutputWithContext(ctx context.Context) MetadataOptionsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v MetadataOptions) *MetadataOptions {
		return &v
	}).(MetadataOptionsPtrOutput)
}

func (o MetadataOptionsOutput) HttpEndpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MetadataOptions) *string { return v.HttpEndpoint }).(pulumi.StringPtrOutput)
}

func (o MetadataOptionsOutput) HttpTokens() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MetadataOptions) *string { return v.HttpTokens }).(pulumi.StringPtrOutput)
}

type MetadataOptionsPtrOutput struct{ *pulumi.OutputState }

func (MetadataOptionsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MetadataOptions)(nil)).Elem()
}

func (o MetadataOptionsPtrOutput) ToMetadataOptionsPtrOutput() MetadataOptionsPtrOutput {
	return o
}

func (o MetadataOptionsPtrOutput) ToMetadataOptionsPtrOutputWithContext(ctx context.Context) MetadataOptionsPtrOutput {
	return o
}

func (o MetadataOptionsPtrOutput) Elem() MetadataOptionsOutput {
	return o.ApplyT(func(v *MetadataOptions) MetadataOptions {
		if v != nil {
			return *v
		}
		var ret MetadataOptions
		return ret
	}).(MetadataOptionsOutput)
}

func (o MetadataOptionsPtrOutput) HttpEndpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MetadataOptions) *string {
		if v == nil {
			return nil
		}
		return v.HttpEndpoint
	}).(pulumi.StringPtrOutput)
}

func (o MetadataOptionsPtrOutput) HttpTokens() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MetadataOptions) *string {
		if v == nil {
			return nil
		}
		return v.HttpTokens
	}).(pulumi.StringPtrOutput)
}

type PublisherRegistrationInput struct {
	ExistedBefore     *bool  `pulumi:"existedBefore"`
	PublisherId       int    `pulumi:"publisherId"`
	RegistrationToken string `pulumi:"registrationToken"`
}

// PublisherRegistrationInputInput is an input type that accepts PublisherRegistrationInputArgs and PublisherRegistrationInputOutput values.
// You can construct a concrete instance of `PublisherRegistrationInputInput` via:
//
//	PublisherRegistrationInputArgs{...}
type PublisherRegistrationInputInput interface {
	pulumi.Input

	ToPublisherRegistrationInputOutput() PublisherRegistrationInputOutput
	ToPublisherRegistrationInputOutputWithContext(context.Context) PublisherRegistrationInputOutput
}

type PublisherRegistrationInputArgs struct {
	ExistedBefore     pulumi.BoolPtrInput `pulumi:"existedBefore"`
	PublisherId       pulumi.IntInput     `pulumi:"publisherId"`
	RegistrationToken pulumi.StringInput  `pulumi:"registrationToken"`
}

func (PublisherRegistrationInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PublisherRegistrationInput)(nil)).Elem()
}

func (i PublisherRegistrationInputArgs) ToPublisherRegistrationInputOutput() PublisherRegistrationInputOutput {
	return i.ToPublisherRegistrationInputOutputWithContext(context.Background())
}

func (i PublisherRegistrationInputArgs) ToPublisherRegistrationInputOutputWithContext(ctx context.Context) PublisherRegistrationInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PublisherRegistrationInputOutput)
}

// PublisherRegistrationInputMapInput is an input type that accepts PublisherRegistrationInputMap and PublisherRegistrationInputMapOutput values.
// You can construct a concrete instance of `PublisherRegistrationInputMapInput` via:
//
//	PublisherRegistrationInputMap{ "key": PublisherRegistrationInputArgs{...} }
type PublisherRegistrationInputMapInput interface {
	pulumi.Input

	ToPublisherRegistrationInputMapOutput() PublisherRegistrationInputMapOutput
	ToPublisherRegistrationInputMapOutputWithContext(context.Context) PublisherRegistrationInputMapOutput
}

type PublisherRegistrationInputMap map[string]PublisherRegistrationInputInput

func (PublisherRegistrationInputMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]PublisherRegistrationInput)(nil)).Elem()
}

func (i PublisherRegistrationInputMap) ToPublisherRegistrationInputMapOutput() PublisherRegistrationInputMapOutput {
	return i.ToPublisherRegistrationInputMapOutputWithContext(context.Background())
}

func (i PublisherRegistrationInputMap) ToPublisherRegistrationInputMapOutputWithContext(ctx context.Context) PublisherRegistrationInputMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PublisherRegistrationInputMapOutput)
}

type PublisherRegistrationInputOutput struct{ *pulumi.OutputState }

func (PublisherRegistrationInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PublisherRegistrationInput)(nil)).Elem()
}

func (o PublisherRegistrationInputOutput) ToPublisherRegistrationInputOutput() PublisherRegistrationInputOutput {
	return o
}

func (o PublisherRegistrationInputOutput) ToPublisherRegistrationInputOutputWithContext(ctx context.Context) PublisherRegistrationInputOutput {
	return o
}

func (o PublisherRegistrationInputOutput) ExistedBefore() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PublisherRegistrationInput) *bool { return v.ExistedBefore }).(pulumi.BoolPtrOutput)
}

func (o PublisherRegistrationInputOutput) PublisherId() pulumi.IntOutput {
	return o.ApplyT(func(v PublisherRegistrationInput) int { return v.PublisherId }).(pulumi.IntOutput)
}

func (o PublisherRegistrationInputOutput) RegistrationToken() pulumi.StringOutput {
	return o.ApplyT(func(v PublisherRegistrationInput) string { return v.RegistrationToken }).(pulumi.StringOutput)
}

type PublisherRegistrationInputMapOutput struct{ *pulumi.OutputState }

func (PublisherRegistrationInputMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]PublisherRegistrationInput)(nil)).Elem()
}

func (o PublisherRegistrationInputMapOutput) ToPublisherRegistrationInputMapOutput() PublisherRegistrationInputMapOutput {
	return o
}

func (o PublisherRegistrationInputMapOutput) ToPublisherRegistrationInputMapOutputWithContext(ctx context.Context) PublisherRegistrationInputMapOutput {
	return o
}

func (o PublisherRegistrationInputMapOutput) MapIndex(k pulumi.StringInput) PublisherRegistrationInputOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) PublisherRegistrationInput {
		return vs[0].(map[string]PublisherRegistrationInput)[vs[1].(string)]
	}).(PublisherRegistrationInputOutput)
}

type RegistrationRecord struct {
	ExistedBefore     bool   `pulumi:"existedBefore"`
	PublisherId       int    `pulumi:"publisherId"`
	RegistrationToken string `pulumi:"registrationToken"`
}

type RegistrationRecordOutput struct{ *pulumi.OutputState }

func (RegistrationRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RegistrationRecord)(nil)).Elem()
}

func (o RegistrationRecordOutput) ToRegistrationRecordOutput() RegistrationRecordOutput {
	return o
}

func (o RegistrationRecordOutput) ToRegistrationRecordOutputWithContext(ctx context.Context) RegistrationRecordOutput {
	return o
}

func (o RegistrationRecordOutput) ExistedBefore() pulumi.BoolOutput {
	return o.ApplyT(func(v RegistrationRecord) bool { return v.ExistedBefore }).(pulumi.BoolOutput)
}

func (o RegistrationRecordOutput) PublisherId() pulumi.IntOutput {
	return o.ApplyT(func(v RegistrationRecord) int { return v.PublisherId }).(pulumi.IntOutput)
}

func (o RegistrationRecordOutput) RegistrationToken() pulumi.StringOutput {
	return o.ApplyT(func(v RegistrationRecord) string { return v.RegistrationToken }).(pulumi.StringOutput)
}

type RegistrationRecordMapOutput struct{ *pulumi.OutputState }

func (RegistrationRecordMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]RegistrationRecord)(nil)).Elem()
}

func (o RegistrationRecordMapOutput) ToRegistrationRecordMapOutput() RegistrationRecordMapOutput {
	return o
}

func (o RegistrationRecordMapOutput) ToRegistrationRecordMapOutputWithContext(ctx context.Context) RegistrationRecordMapOutput {
	return o
}

func (o RegistrationRecordMapOutput) MapIndex(k pulumi.StringInput) RegistrationRecordOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) RegistrationRecord {
		return vs[0].(map[string]RegistrationRecord)[vs[1].(string)]
	}).(RegistrationRecordOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMarketplaceImageInput)(nil)).Elem(), AzureMarketplaceImageArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureMarketplaceImagePtrInput)(nil)).Elem(), AzureMarketplaceImageArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOsDiskInput)(nil)).Elem(), AzureOsDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AzureOsDiskPtrInput)(nil)).Elem(), AzureOsDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GcpServiceAccountInput)(nil)).Elem(), GcpServiceAccountArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GcpServiceAccountPtrInput)(nil)).Elem(), GcpServiceAccountArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GuestNetworkInterfaceInput)(nil)).Elem(), GuestNetworkInterfaceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GuestNetworkInterfacePtrInput)(nil)).Elem(), GuestNetworkInterfaceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*HypervHardDriveInput)(nil)).Elem(), HypervHardDriveArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*HypervHardDriveArrayInput)(nil)).Elem(), HypervHardDriveArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MetadataOptionsInput)(nil)).Elem(), MetadataOptionsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*MetadataOptionsPtrInput)(nil)).Elem(), MetadataOptionsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PublisherRegistrationInputInput)(nil)).Elem(), PublisherRegistrationInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PublisherRegistrationInputMapInput)(nil)).Elem(), PublisherRegistrationInputMap{})
	pulumi.RegisterOutputType(AzureMarketplaceImageOutput{})
	pulumi.RegisterOutputType(AzureMarketplaceImagePtrOutput{})
	pulumi.RegisterOutputType(AzureOsDiskOutput{})
	pulumi.RegisterOutputType(AzureOsDiskPtrOutput{})
	pulumi.RegisterOutputType(GcpServiceAccountOutput{})
	pulumi.RegisterOutputType(GcpServiceAccountPtrOutput{})
	pulumi.RegisterOutputType(GuestNetworkInterfaceOutput{})
	pulumi.RegisterOutputType(GuestNetworkInterfacePtrOutput{})
	pulumi.RegisterOutputType(HypervHardDriveOutput{})
	pulumi.RegisterOutputType(HypervHardDriveArrayOutput{})
	pulumi.RegisterOutputType(MetadataOptionsOutput{})
	pulumi.RegisterOutputType(MetadataOptionsPtrOutput{})
	pulumi.RegisterOutputType(PublisherRegistrationInputOutput{})
	pulumi.RegisterOutputType(PublisherRegistrationInputMapOutput{})
	pulumi.RegisterOutputType(RegistrationRecordOutput{})
	pulumi.RegisterOutputType(RegistrationRecordMapOutput{})
}
