// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher
{
    [NetskopePublisherResourceType("netskope-publisher:index:GcpPublisher")]
    public partial class GcpPublisher : global::Pulumi.ComponentResource
    {
        [Output("apiToken")]
        public Output<string?> ApiToken { get; private set; } = null!;

        [Output("assignPublicIp")]
        public Output<bool?> AssignPublicIp { get; private set; } = null!;

        [Output("bootstrap")]
        public Output<bool?> Bootstrap { get; private set; } = null!;

        [Output("bootstrapUrl")]
        public Output<string?> BootstrapUrl { get; private set; } = null!;

        [Output("deleteDefaultUser")]
        public Output<bool?> DeleteDefaultUser { get; private set; } = null!;

        [Output("guestNetworkInterface")]
        public Output<Pulumi.NetskopePublisher.Provider.Outputs.GuestNetworkInterface?> GuestNetworkInterface { get; private set; } = null!;

        [Output("image")]
        public Output<string> Image { get; private set; } = null!;

        [Output("installUser")]
        public Output<string?> InstallUser { get; private set; } = null!;

        [Output("installUserPassword")]
        public Output<string?> InstallUserPassword { get; private set; } = null!;

        [Output("installUserPasswordIsHash")]
        public Output<bool?> InstallUserPasswordIsHash { get; private set; } = null!;

        [Output("installUserSshAuthorizedKeys")]
        public Output<ImmutableArray<string>> InstallUserSshAuthorizedKeys { get; private set; } = null!;

        [Output("machineType")]
        public Output<string?> MachineType { get; private set; } = null!;

        [Output("namePrefix")]
        public Output<string?> NamePrefix { get; private set; } = null!;

        [Output("names")]
        public Output<ImmutableArray<string>> Names { get; private set; } = null!;

        [Output("network")]
        public Output<string> Network { get; private set; } = null!;

        [Output("networkTags")]
        public Output<ImmutableArray<string>> NetworkTags { get; private set; } = null!;

        [Output("nonat")]
        public Output<bool?> Nonat { get; private set; } = null!;

        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        [Output("publisherNames")]
        public Output<ImmutableArray<string>> PublisherNames { get; private set; } = null!;

        [Output("publishers")]
        public Output<ImmutableDictionary<string, object>> Publishers { get; private set; } = null!;

        [Output("registrations")]
        public Output<ImmutableDictionary<string, Pulumi.NetskopePublisher.Provider.Outputs.PublisherRegistrationInput>?> Registrations { get; private set; } = null!;

        [Output("replicas")]
        public Output<int?> Replicas { get; private set; } = null!;

        [Output("serviceAccount")]
        public Output<Pulumi.NetskopePublisher.Provider.Outputs.GcpServiceAccount?> ServiceAccount { get; private set; } = null!;

        [Output("subnetwork")]
        public Output<string> Subnetwork { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        [Output("tenantUrl")]
        public Output<string?> TenantUrl { get; private set; } = null!;

        [Output("wizardPath")]
        public Output<string?> WizardPath { get; private set; } = null!;

        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a GcpPublisher resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GcpPublisher(string name, GcpPublisherArgs args, ComponentResourceOptions? options = null)
            : base("netskope-publisher:index:GcpPublisher", name, args ?? new GcpPublisherArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/johnneerdael/pulumi-netskope-publisher",
                AdditionalSecretOutputs =
                {
                    "apiToken",
                    "installUserPassword",
                    "publishers",
                },
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class GcpPublisherArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiToken")]
        private string? _apiToken;
        public string? ApiToken
        {
            get => _apiToken;
            set => _apiToken = value;
        }

        [Input("assignPublicIp")]
        public bool? AssignPublicIp { get; set; }

        [Input("bootstrap")]
        public bool? Bootstrap { get; set; }

        [Input("bootstrapUrl")]
        public string? BootstrapUrl { get; set; }

        [Input("deleteDefaultUser")]
        public bool? DeleteDefaultUser { get; set; }

        [Input("guestNetworkInterface")]
        public Input<Pulumi.NetskopePublisher.Provider.Inputs.GuestNetworkInterfaceArgs>? GuestNetworkInterface { get; set; }

        [Input("image", required: true)]
        public string Image { get; set; } = null!;

        [Input("installUser")]
        public string? InstallUser { get; set; }

        [Input("installUserPassword")]
        private string? _installUserPassword;
        public string? InstallUserPassword
        {
            get => _installUserPassword;
            set => _installUserPassword = value;
        }

        [Input("installUserPasswordIsHash")]
        public bool? InstallUserPasswordIsHash { get; set; }

        [Input("installUserSshAuthorizedKeys")]
        private InputList<string>? _installUserSshAuthorizedKeys;
        public InputList<string> InstallUserSshAuthorizedKeys
        {
            get => _installUserSshAuthorizedKeys ?? (_installUserSshAuthorizedKeys = new InputList<string>());
            set => _installUserSshAuthorizedKeys = value;
        }

        [Input("machineType")]
        public string? MachineType { get; set; }

        [Input("namePrefix")]
        public string? NamePrefix { get; set; }

        [Input("names")]
        private InputList<string>? _names;
        public InputList<string> Names
        {
            get => _names ?? (_names = new InputList<string>());
            set => _names = value;
        }

        [Input("network", required: true)]
        public string Network { get; set; } = null!;

        [Input("networkTags")]
        private InputList<string>? _networkTags;
        public InputList<string> NetworkTags
        {
            get => _networkTags ?? (_networkTags = new InputList<string>());
            set => _networkTags = value;
        }

        [Input("nonat")]
        public bool? Nonat { get; set; }

        [Input("project", required: true)]
        public string Project { get; set; } = null!;

        [Input("registrations")]
        private InputMap<Pulumi.NetskopePublisher.Provider.Inputs.PublisherRegistrationInputArgs>? _registrations;
        public InputMap<Pulumi.NetskopePublisher.Provider.Inputs.PublisherRegistrationInputArgs> Registrations
        {
            get => _registrations ?? (_registrations = new InputMap<Pulumi.NetskopePublisher.Provider.Inputs.PublisherRegistrationInputArgs>());
            set => _registrations = value;
        }

        [Input("replicas")]
        public int? Replicas { get; set; }

        [Input("serviceAccount")]
        public Input<Pulumi.NetskopePublisher.Provider.Inputs.GcpServiceAccountArgs>? ServiceAccount { get; set; }

        [Input("subnetwork", required: true)]
        public string Subnetwork { get; set; } = null!;

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("tenantUrl")]
        public string? TenantUrl { get; set; }

        [Input("wizardPath")]
        public string? WizardPath { get; set; }

        [Input("zone", required: true)]
        public string Zone { get; set; } = null!;

        public GcpPublisherArgs()
        {
        }
        public static new GcpPublisherArgs Empty => new GcpPublisherArgs();
    }
}
