// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher
{
    [NetskopePublisherResourceType("netskope-publisher:index:NetskopeRegistration")]
    public partial class NetskopeRegistration : global::Pulumi.CustomResource
    {
        [Output("apiToken")]
        public Output<string?> ApiToken { get; private set; } = null!;

        [Output("authMode")]
        public Output<string?> AuthMode { get; private set; } = null!;

        [Output("bearerToken")]
        public Output<string?> BearerToken { get; private set; } = null!;

        [Output("oauth2")]
        public Output<Pulumi.NetskopePublisher.Provider.Outputs.NetskopeOAuth2Args?> Oauth2 { get; private set; } = null!;

        [Output("publisherNames")]
        public Output<ImmutableArray<string>> PublisherNames { get; private set; } = null!;

        [Output("registrations")]
        public Output<ImmutableDictionary<string, Pulumi.NetskopePublisher.Provider.Outputs.RegistrationRecord>> Registrations { get; private set; } = null!;

        [Output("tenantUrl")]
        public Output<string> TenantUrl { get; private set; } = null!;


        /// <summary>
        /// Create a NetskopeRegistration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetskopeRegistration(string name, NetskopeRegistrationArgs args, CustomResourceOptions? options = null)
            : base("netskope-publisher:index:NetskopeRegistration", name, args ?? new NetskopeRegistrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetskopeRegistration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("netskope-publisher:index:NetskopeRegistration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/johnneerdael/pulumi-netskope-publisher",
                AdditionalSecretOutputs =
                {
                    "apiToken",
                    "bearerToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetskopeRegistration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetskopeRegistration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new NetskopeRegistration(name, id, options);
        }
    }

    public sealed class NetskopeRegistrationArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiToken")]
        private Input<string>? _apiToken;
        public Input<string>? ApiToken
        {
            get => _apiToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("authMode")]
        public Input<string>? AuthMode { get; set; }

        [Input("bearerToken")]
        private Input<string>? _bearerToken;
        public Input<string>? BearerToken
        {
            get => _bearerToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _bearerToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("oauth2")]
        public Input<Pulumi.NetskopePublisher.Provider.Inputs.NetskopeOAuth2ArgsArgs>? Oauth2 { get; set; }

        [Input("publisherNames", required: true)]
        private InputList<string>? _publisherNames;
        public InputList<string> PublisherNames
        {
            get => _publisherNames ?? (_publisherNames = new InputList<string>());
            set => _publisherNames = value;
        }

        [Input("tenantUrl", required: true)]
        public Input<string> TenantUrl { get; set; } = null!;

        public NetskopeRegistrationArgs()
        {
        }
        public static new NetskopeRegistrationArgs Empty => new NetskopeRegistrationArgs();
    }
}
