// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher
{
    [NetskopePublisherResourceType("netskope-publisher:index:NutanixPublisher")]
    public partial class NutanixPublisher : global::Pulumi.ComponentResource
    {
        [Output("apiToken")]
        public Output<string?> ApiToken { get; private set; } = null!;

        [Output("authMode")]
        public Output<string?> AuthMode { get; private set; } = null!;

        [Output("bearerToken")]
        public Output<string?> BearerToken { get; private set; } = null!;

        [Output("bootstrap")]
        public Output<bool?> Bootstrap { get; private set; } = null!;

        [Output("bootstrapUrl")]
        public Output<string?> BootstrapUrl { get; private set; } = null!;

        [Output("clusterUuid")]
        public Output<string> ClusterUuid { get; private set; } = null!;

        [Output("deleteDefaultUser")]
        public Output<bool?> DeleteDefaultUser { get; private set; } = null!;

        [Output("guestNetworkInterface")]
        public Output<Pulumi.NetskopePublisher.Types.Outputs.GuestNetworkInterface?> GuestNetworkInterface { get; private set; } = null!;

        [Output("imageUuid")]
        public Output<string?> ImageUuid { get; private set; } = null!;

        [Output("installUser")]
        public Output<string?> InstallUser { get; private set; } = null!;

        [Output("installUserPassword")]
        public Output<string?> InstallUserPassword { get; private set; } = null!;

        [Output("installUserPasswordIsHash")]
        public Output<bool?> InstallUserPasswordIsHash { get; private set; } = null!;

        [Output("installUserSshAuthorizedKeys")]
        public Output<ImmutableArray<string>> InstallUserSshAuthorizedKeys { get; private set; } = null!;

        [Output("memorySizeMib")]
        public Output<int?> MemorySizeMib { get; private set; } = null!;

        [Output("namePrefix")]
        public Output<string?> NamePrefix { get; private set; } = null!;

        [Output("names")]
        public Output<ImmutableArray<string>> Names { get; private set; } = null!;

        [Output("nonat")]
        public Output<bool?> Nonat { get; private set; } = null!;

        [Output("numCoresPerVcpu")]
        public Output<int?> NumCoresPerVcpu { get; private set; } = null!;

        [Output("numVCpus")]
        public Output<int?> NumVCpus { get; private set; } = null!;

        [Output("oauth2")]
        public Output<Pulumi.NetskopePublisher.Types.Outputs.NetskopeOAuth2Args?> Oauth2 { get; private set; } = null!;

        [Output("publisherNames")]
        public Output<ImmutableArray<string>> PublisherNames { get; private set; } = null!;

        [Output("publishers")]
        public Output<ImmutableDictionary<string, object>> Publishers { get; private set; } = null!;

        [Output("registrations")]
        public Output<ImmutableDictionary<string, Pulumi.NetskopePublisher.Types.Outputs.PublisherRegistrationInput>?> Registrations { get; private set; } = null!;

        [Output("replicas")]
        public Output<int?> Replicas { get; private set; } = null!;

        [Output("subnetUuid")]
        public Output<string?> SubnetUuid { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        [Output("tenantUrl")]
        public Output<string?> TenantUrl { get; private set; } = null!;

        [Output("wizardPath")]
        public Output<string?> WizardPath { get; private set; } = null!;


        /// <summary>
        /// Create a NutanixPublisher resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NutanixPublisher(string name, NutanixPublisherArgs args, ComponentResourceOptions? options = null)
            : base("netskope-publisher:index:NutanixPublisher", name, args ?? new NutanixPublisherArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/johnneerdael/pulumi-netskope-publisher",
                AdditionalSecretOutputs =
                {
                    "apiToken",
                    "bearerToken",
                    "installUserPassword",
                    "publishers",
                },
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class NutanixPublisherArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiToken")]
        private string? _apiToken;
        public string? ApiToken
        {
            get => _apiToken;
            set => _apiToken = value;
        }

        [Input("authMode")]
        public string? AuthMode { get; set; }

        [Input("bearerToken")]
        private string? _bearerToken;
        public string? BearerToken
        {
            get => _bearerToken;
            set => _bearerToken = value;
        }

        [Input("bootstrap")]
        public bool? Bootstrap { get; set; }

        [Input("bootstrapUrl")]
        public string? BootstrapUrl { get; set; }

        [Input("clusterUuid", required: true)]
        public string ClusterUuid { get; set; } = null!;

        [Input("deleteDefaultUser")]
        public bool? DeleteDefaultUser { get; set; }

        [Input("guestNetworkInterface")]
        public Input<Pulumi.NetskopePublisher.Types.Inputs.GuestNetworkInterfaceArgs>? GuestNetworkInterface { get; set; }

        [Input("imageUuid")]
        public string? ImageUuid { get; set; }

        [Input("installUser")]
        public string? InstallUser { get; set; }

        [Input("installUserPassword")]
        private string? _installUserPassword;
        public string? InstallUserPassword
        {
            get => _installUserPassword;
            set => _installUserPassword = value;
        }

        [Input("installUserPasswordIsHash")]
        public bool? InstallUserPasswordIsHash { get; set; }

        [Input("installUserSshAuthorizedKeys")]
        private InputList<string>? _installUserSshAuthorizedKeys;
        public InputList<string> InstallUserSshAuthorizedKeys
        {
            get => _installUserSshAuthorizedKeys ?? (_installUserSshAuthorizedKeys = new InputList<string>());
            set => _installUserSshAuthorizedKeys = value;
        }

        [Input("memorySizeMib")]
        public int? MemorySizeMib { get; set; }

        [Input("namePrefix")]
        public string? NamePrefix { get; set; }

        [Input("names")]
        private InputList<string>? _names;
        public InputList<string> Names
        {
            get => _names ?? (_names = new InputList<string>());
            set => _names = value;
        }

        [Input("nonat")]
        public bool? Nonat { get; set; }

        [Input("numCoresPerVcpu")]
        public int? NumCoresPerVcpu { get; set; }

        [Input("numVCpus")]
        public int? NumVCpus { get; set; }

        [Input("oauth2")]
        public Input<Pulumi.NetskopePublisher.Types.Inputs.NetskopeOAuth2ArgsArgs>? Oauth2 { get; set; }

        [Input("registrations")]
        private InputMap<Pulumi.NetskopePublisher.Types.Inputs.PublisherRegistrationInputArgs>? _registrations;
        public InputMap<Pulumi.NetskopePublisher.Types.Inputs.PublisherRegistrationInputArgs> Registrations
        {
            get => _registrations ?? (_registrations = new InputMap<Pulumi.NetskopePublisher.Types.Inputs.PublisherRegistrationInputArgs>());
            set => _registrations = value;
        }

        [Input("replicas")]
        public int? Replicas { get; set; }

        [Input("subnetUuid")]
        public string? SubnetUuid { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        [Input("tenantUrl")]
        public string? TenantUrl { get; set; }

        [Input("wizardPath")]
        public string? WizardPath { get; set; }

        public NutanixPublisherArgs()
        {
        }
        public static new NutanixPublisherArgs Empty => new NutanixPublisherArgs();
    }
}
