// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"errors"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/provider"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AlicloudPublisher struct {
	pulumi.ResourceState

	AllocatePublicIp             pulumi.BoolPtrOutput                         `pulumi:"allocatePublicIp"`
	ApiToken                     pulumi.StringPtrOutput                       `pulumi:"apiToken"`
	AuthMode                     pulumi.StringPtrOutput                       `pulumi:"authMode"`
	BearerToken                  pulumi.StringPtrOutput                       `pulumi:"bearerToken"`
	Bootstrap                    pulumi.BoolPtrOutput                         `pulumi:"bootstrap"`
	BootstrapUrl                 pulumi.StringPtrOutput                       `pulumi:"bootstrapUrl"`
	DeleteDefaultUser            pulumi.BoolPtrOutput                         `pulumi:"deleteDefaultUser"`
	GuestNetworkInterface        provider.GuestNetworkInterfacePtrOutput      `pulumi:"guestNetworkInterface"`
	ImageId                      pulumi.StringOutput                          `pulumi:"imageId"`
	InstallUser                  pulumi.StringPtrOutput                       `pulumi:"installUser"`
	InstallUserPassword          pulumi.StringPtrOutput                       `pulumi:"installUserPassword"`
	InstallUserPasswordIsHash    pulumi.BoolPtrOutput                         `pulumi:"installUserPasswordIsHash"`
	InstallUserSshAuthorizedKeys pulumi.StringArrayOutput                     `pulumi:"installUserSshAuthorizedKeys"`
	InstanceType                 pulumi.StringPtrOutput                       `pulumi:"instanceType"`
	KeyName                      pulumi.StringPtrOutput                       `pulumi:"keyName"`
	NamePrefix                   pulumi.StringPtrOutput                       `pulumi:"namePrefix"`
	Names                        pulumi.StringArrayOutput                     `pulumi:"names"`
	Nonat                        pulumi.BoolPtrOutput                         `pulumi:"nonat"`
	Oauth2                       provider.NetskopeOAuth2ArgsPtrOutput         `pulumi:"oauth2"`
	PlacementLabels              pulumi.StringArrayOutput                     `pulumi:"placementLabels"`
	PublisherNames               pulumi.StringArrayOutput                     `pulumi:"publisherNames"`
	Publishers                   pulumi.MapOutput                             `pulumi:"publishers"`
	Registrations                provider.PublisherRegistrationInputMapOutput `pulumi:"registrations"`
	Replicas                     pulumi.IntPtrOutput                          `pulumi:"replicas"`
	SecurityGroupIds             pulumi.StringArrayOutput                     `pulumi:"securityGroupIds"`
	Tags                         pulumi.StringMapOutput                       `pulumi:"tags"`
	TenantUrl                    pulumi.StringPtrOutput                       `pulumi:"tenantUrl"`
	VswitchId                    pulumi.StringOutput                          `pulumi:"vswitchId"`
	WizardPath                   pulumi.StringPtrOutput                       `pulumi:"wizardPath"`
}

// NewAlicloudPublisher registers a new resource with the given unique name, arguments, and options.
func NewAlicloudPublisher(ctx *pulumi.Context,
	name string, args *AlicloudPublisherArgs, opts ...pulumi.ResourceOption) (*AlicloudPublisher, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SecurityGroupIds == nil {
		return nil, errors.New("invalid value for required argument 'SecurityGroupIds'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
		"bearerToken",
		"installUserPassword",
		"publishers",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AlicloudPublisher
	err := ctx.RegisterRemoteComponentResource("netskope-publisher:index:AlicloudPublisher", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type alicloudPublisherArgs struct {
	AllocatePublicIp             *bool                                          `pulumi:"allocatePublicIp"`
	ApiToken                     *string                                        `pulumi:"apiToken"`
	AuthMode                     *string                                        `pulumi:"authMode"`
	BearerToken                  *string                                        `pulumi:"bearerToken"`
	Bootstrap                    *bool                                          `pulumi:"bootstrap"`
	BootstrapUrl                 *string                                        `pulumi:"bootstrapUrl"`
	DeleteDefaultUser            *bool                                          `pulumi:"deleteDefaultUser"`
	GuestNetworkInterface        *provider.GuestNetworkInterface                `pulumi:"guestNetworkInterface"`
	ImageId                      string                                         `pulumi:"imageId"`
	InstallUser                  *string                                        `pulumi:"installUser"`
	InstallUserPassword          *string                                        `pulumi:"installUserPassword"`
	InstallUserPasswordIsHash    *bool                                          `pulumi:"installUserPasswordIsHash"`
	InstallUserSshAuthorizedKeys []string                                       `pulumi:"installUserSshAuthorizedKeys"`
	InstanceType                 *string                                        `pulumi:"instanceType"`
	KeyName                      *string                                        `pulumi:"keyName"`
	NamePrefix                   *string                                        `pulumi:"namePrefix"`
	Names                        []string                                       `pulumi:"names"`
	Nonat                        *bool                                          `pulumi:"nonat"`
	Oauth2                       *provider.NetskopeOAuth2Args                   `pulumi:"oauth2"`
	PlacementLabels              []string                                       `pulumi:"placementLabels"`
	Registrations                map[string]provider.PublisherRegistrationInput `pulumi:"registrations"`
	Replicas                     *int                                           `pulumi:"replicas"`
	SecurityGroupIds             []string                                       `pulumi:"securityGroupIds"`
	Tags                         map[string]string                              `pulumi:"tags"`
	TenantUrl                    *string                                        `pulumi:"tenantUrl"`
	VswitchId                    string                                         `pulumi:"vswitchId"`
	WizardPath                   *string                                        `pulumi:"wizardPath"`
}

// The set of arguments for constructing a AlicloudPublisher resource.
type AlicloudPublisherArgs struct {
	AllocatePublicIp             *bool
	ApiToken                     *string
	AuthMode                     *string
	BearerToken                  *string
	Bootstrap                    *bool
	BootstrapUrl                 *string
	DeleteDefaultUser            *bool
	GuestNetworkInterface        provider.GuestNetworkInterfacePtrInput
	ImageId                      string
	InstallUser                  *string
	InstallUserPassword          *string
	InstallUserPasswordIsHash    *bool
	InstallUserSshAuthorizedKeys pulumi.StringArrayInput
	InstanceType                 *string
	KeyName                      *string
	NamePrefix                   *string
	Names                        pulumi.StringArrayInput
	Nonat                        *bool
	Oauth2                       provider.NetskopeOAuth2ArgsPtrInput
	PlacementLabels              pulumi.StringArrayInput
	Registrations                provider.PublisherRegistrationInputMapInput
	Replicas                     *int
	SecurityGroupIds             pulumi.StringArrayInput
	Tags                         pulumi.StringMapInput
	TenantUrl                    *string
	VswitchId                    string
	WizardPath                   *string
}

func (AlicloudPublisherArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*alicloudPublisherArgs)(nil)).Elem()
}

type AlicloudPublisherInput interface {
	pulumi.Input

	ToAlicloudPublisherOutput() AlicloudPublisherOutput
	ToAlicloudPublisherOutputWithContext(ctx context.Context) AlicloudPublisherOutput
}

func (*AlicloudPublisher) ElementType() reflect.Type {
	return reflect.TypeOf((**AlicloudPublisher)(nil)).Elem()
}

func (i *AlicloudPublisher) ToAlicloudPublisherOutput() AlicloudPublisherOutput {
	return i.ToAlicloudPublisherOutputWithContext(context.Background())
}

func (i *AlicloudPublisher) ToAlicloudPublisherOutputWithContext(ctx context.Context) AlicloudPublisherOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AlicloudPublisherOutput)
}

type AlicloudPublisherOutput struct{ *pulumi.OutputState }

func (AlicloudPublisherOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AlicloudPublisher)(nil)).Elem()
}

func (o AlicloudPublisherOutput) ToAlicloudPublisherOutput() AlicloudPublisherOutput {
	return o
}

func (o AlicloudPublisherOutput) ToAlicloudPublisherOutputWithContext(ctx context.Context) AlicloudPublisherOutput {
	return o
}

func (o AlicloudPublisherOutput) AllocatePublicIp() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.BoolPtrOutput { return v.AllocatePublicIp }).(pulumi.BoolPtrOutput)
}

func (o AlicloudPublisherOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) AuthMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.AuthMode }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) BearerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.BearerToken }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) Bootstrap() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.BoolPtrOutput { return v.Bootstrap }).(pulumi.BoolPtrOutput)
}

func (o AlicloudPublisherOutput) BootstrapUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.BootstrapUrl }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) DeleteDefaultUser() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.BoolPtrOutput { return v.DeleteDefaultUser }).(pulumi.BoolPtrOutput)
}

func (o AlicloudPublisherOutput) GuestNetworkInterface() provider.GuestNetworkInterfacePtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) provider.GuestNetworkInterfacePtrOutput { return v.GuestNetworkInterface }).(provider.GuestNetworkInterfacePtrOutput)
}

func (o AlicloudPublisherOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

func (o AlicloudPublisherOutput) InstallUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.InstallUser }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) InstallUserPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.InstallUserPassword }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) InstallUserPasswordIsHash() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.BoolPtrOutput { return v.InstallUserPasswordIsHash }).(pulumi.BoolPtrOutput)
}

func (o AlicloudPublisherOutput) InstallUserSshAuthorizedKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringArrayOutput { return v.InstallUserSshAuthorizedKeys }).(pulumi.StringArrayOutput)
}

func (o AlicloudPublisherOutput) InstanceType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.InstanceType }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) KeyName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.KeyName }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) NamePrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.NamePrefix }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringArrayOutput { return v.Names }).(pulumi.StringArrayOutput)
}

func (o AlicloudPublisherOutput) Nonat() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.BoolPtrOutput { return v.Nonat }).(pulumi.BoolPtrOutput)
}

func (o AlicloudPublisherOutput) Oauth2() provider.NetskopeOAuth2ArgsPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) provider.NetskopeOAuth2ArgsPtrOutput { return v.Oauth2 }).(provider.NetskopeOAuth2ArgsPtrOutput)
}

func (o AlicloudPublisherOutput) PlacementLabels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringArrayOutput { return v.PlacementLabels }).(pulumi.StringArrayOutput)
}

func (o AlicloudPublisherOutput) PublisherNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringArrayOutput { return v.PublisherNames }).(pulumi.StringArrayOutput)
}

func (o AlicloudPublisherOutput) Publishers() pulumi.MapOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.MapOutput { return v.Publishers }).(pulumi.MapOutput)
}

func (o AlicloudPublisherOutput) Registrations() provider.PublisherRegistrationInputMapOutput {
	return o.ApplyT(func(v *AlicloudPublisher) provider.PublisherRegistrationInputMapOutput { return v.Registrations }).(provider.PublisherRegistrationInputMapOutput)
}

func (o AlicloudPublisherOutput) Replicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.IntPtrOutput { return v.Replicas }).(pulumi.IntPtrOutput)
}

func (o AlicloudPublisherOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o AlicloudPublisherOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

func (o AlicloudPublisherOutput) TenantUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.TenantUrl }).(pulumi.StringPtrOutput)
}

func (o AlicloudPublisherOutput) VswitchId() pulumi.StringOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringOutput { return v.VswitchId }).(pulumi.StringOutput)
}

func (o AlicloudPublisherOutput) WizardPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AlicloudPublisher) pulumi.StringPtrOutput { return v.WizardPath }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AlicloudPublisherInput)(nil)).Elem(), &AlicloudPublisher{})
	pulumi.RegisterOutputType(AlicloudPublisherOutput{})
}
