// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/provider"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type HcloudPublisher struct {
	pulumi.ResourceState

	ApiToken                     pulumi.StringPtrOutput                       `pulumi:"apiToken"`
	AssignPublicIp               pulumi.BoolPtrOutput                         `pulumi:"assignPublicIp"`
	AuthMode                     pulumi.StringPtrOutput                       `pulumi:"authMode"`
	BearerToken                  pulumi.StringPtrOutput                       `pulumi:"bearerToken"`
	Bootstrap                    pulumi.BoolPtrOutput                         `pulumi:"bootstrap"`
	BootstrapUrl                 pulumi.StringPtrOutput                       `pulumi:"bootstrapUrl"`
	Datacenter                   pulumi.StringPtrOutput                       `pulumi:"datacenter"`
	DeleteDefaultUser            pulumi.BoolPtrOutput                         `pulumi:"deleteDefaultUser"`
	FirewallIds                  pulumi.IntArrayOutput                        `pulumi:"firewallIds"`
	GuestNetworkInterface        provider.GuestNetworkInterfacePtrOutput      `pulumi:"guestNetworkInterface"`
	Image                        pulumi.StringPtrOutput                       `pulumi:"image"`
	InstallUser                  pulumi.StringPtrOutput                       `pulumi:"installUser"`
	InstallUserPassword          pulumi.StringPtrOutput                       `pulumi:"installUserPassword"`
	InstallUserPasswordIsHash    pulumi.BoolPtrOutput                         `pulumi:"installUserPasswordIsHash"`
	InstallUserSshAuthorizedKeys pulumi.StringArrayOutput                     `pulumi:"installUserSshAuthorizedKeys"`
	Location                     pulumi.StringPtrOutput                       `pulumi:"location"`
	NamePrefix                   pulumi.StringPtrOutput                       `pulumi:"namePrefix"`
	Names                        pulumi.StringArrayOutput                     `pulumi:"names"`
	NetworkId                    pulumi.IntPtrOutput                          `pulumi:"networkId"`
	Nonat                        pulumi.BoolPtrOutput                         `pulumi:"nonat"`
	Oauth2                       provider.NetskopeOAuth2ArgsPtrOutput         `pulumi:"oauth2"`
	PublisherNames               pulumi.StringArrayOutput                     `pulumi:"publisherNames"`
	Publishers                   pulumi.MapOutput                             `pulumi:"publishers"`
	Registrations                provider.PublisherRegistrationInputMapOutput `pulumi:"registrations"`
	Replicas                     pulumi.IntPtrOutput                          `pulumi:"replicas"`
	ServerType                   pulumi.StringPtrOutput                       `pulumi:"serverType"`
	SshKeys                      pulumi.StringArrayOutput                     `pulumi:"sshKeys"`
	Tags                         pulumi.StringMapOutput                       `pulumi:"tags"`
	TenantUrl                    pulumi.StringPtrOutput                       `pulumi:"tenantUrl"`
	WizardPath                   pulumi.StringPtrOutput                       `pulumi:"wizardPath"`
}

// NewHcloudPublisher registers a new resource with the given unique name, arguments, and options.
func NewHcloudPublisher(ctx *pulumi.Context,
	name string, args *HcloudPublisherArgs, opts ...pulumi.ResourceOption) (*HcloudPublisher, error) {
	if args == nil {
		args = &HcloudPublisherArgs{}
	}

	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(*string)
	}
	if args.BearerToken != nil {
		args.BearerToken = pulumi.ToSecret(args.BearerToken).(*string)
	}
	if args.InstallUserPassword != nil {
		args.InstallUserPassword = pulumi.ToSecret(args.InstallUserPassword).(*string)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
		"bearerToken",
		"installUserPassword",
		"publishers",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource HcloudPublisher
	err := ctx.RegisterRemoteComponentResource("netskope-publisher:index:HcloudPublisher", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type hcloudPublisherArgs struct {
	ApiToken                     *string                                        `pulumi:"apiToken"`
	AssignPublicIp               *bool                                          `pulumi:"assignPublicIp"`
	AuthMode                     *string                                        `pulumi:"authMode"`
	BearerToken                  *string                                        `pulumi:"bearerToken"`
	Bootstrap                    *bool                                          `pulumi:"bootstrap"`
	BootstrapUrl                 *string                                        `pulumi:"bootstrapUrl"`
	Datacenter                   *string                                        `pulumi:"datacenter"`
	DeleteDefaultUser            *bool                                          `pulumi:"deleteDefaultUser"`
	FirewallIds                  []int                                          `pulumi:"firewallIds"`
	GuestNetworkInterface        *provider.GuestNetworkInterface                `pulumi:"guestNetworkInterface"`
	Image                        *string                                        `pulumi:"image"`
	InstallUser                  *string                                        `pulumi:"installUser"`
	InstallUserPassword          *string                                        `pulumi:"installUserPassword"`
	InstallUserPasswordIsHash    *bool                                          `pulumi:"installUserPasswordIsHash"`
	InstallUserSshAuthorizedKeys []string                                       `pulumi:"installUserSshAuthorizedKeys"`
	Location                     *string                                        `pulumi:"location"`
	NamePrefix                   *string                                        `pulumi:"namePrefix"`
	Names                        []string                                       `pulumi:"names"`
	NetworkId                    *int                                           `pulumi:"networkId"`
	Nonat                        *bool                                          `pulumi:"nonat"`
	Oauth2                       *provider.NetskopeOAuth2Args                   `pulumi:"oauth2"`
	Registrations                map[string]provider.PublisherRegistrationInput `pulumi:"registrations"`
	Replicas                     *int                                           `pulumi:"replicas"`
	ServerType                   *string                                        `pulumi:"serverType"`
	SshKeys                      []string                                       `pulumi:"sshKeys"`
	Tags                         map[string]string                              `pulumi:"tags"`
	TenantUrl                    *string                                        `pulumi:"tenantUrl"`
	WizardPath                   *string                                        `pulumi:"wizardPath"`
}

// The set of arguments for constructing a HcloudPublisher resource.
type HcloudPublisherArgs struct {
	ApiToken                     *string
	AssignPublicIp               *bool
	AuthMode                     *string
	BearerToken                  *string
	Bootstrap                    *bool
	BootstrapUrl                 *string
	Datacenter                   *string
	DeleteDefaultUser            *bool
	FirewallIds                  pulumi.IntArrayInput
	GuestNetworkInterface        provider.GuestNetworkInterfacePtrInput
	Image                        *string
	InstallUser                  *string
	InstallUserPassword          *string
	InstallUserPasswordIsHash    *bool
	InstallUserSshAuthorizedKeys pulumi.StringArrayInput
	Location                     *string
	NamePrefix                   *string
	Names                        pulumi.StringArrayInput
	NetworkId                    *int
	Nonat                        *bool
	Oauth2                       provider.NetskopeOAuth2ArgsPtrInput
	Registrations                provider.PublisherRegistrationInputMapInput
	Replicas                     *int
	ServerType                   *string
	SshKeys                      pulumi.StringArrayInput
	Tags                         pulumi.StringMapInput
	TenantUrl                    *string
	WizardPath                   *string
}

func (HcloudPublisherArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hcloudPublisherArgs)(nil)).Elem()
}

type HcloudPublisherInput interface {
	pulumi.Input

	ToHcloudPublisherOutput() HcloudPublisherOutput
	ToHcloudPublisherOutputWithContext(ctx context.Context) HcloudPublisherOutput
}

func (*HcloudPublisher) ElementType() reflect.Type {
	return reflect.TypeOf((**HcloudPublisher)(nil)).Elem()
}

func (i *HcloudPublisher) ToHcloudPublisherOutput() HcloudPublisherOutput {
	return i.ToHcloudPublisherOutputWithContext(context.Background())
}

func (i *HcloudPublisher) ToHcloudPublisherOutputWithContext(ctx context.Context) HcloudPublisherOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HcloudPublisherOutput)
}

type HcloudPublisherOutput struct{ *pulumi.OutputState }

func (HcloudPublisherOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HcloudPublisher)(nil)).Elem()
}

func (o HcloudPublisherOutput) ToHcloudPublisherOutput() HcloudPublisherOutput {
	return o
}

func (o HcloudPublisherOutput) ToHcloudPublisherOutputWithContext(ctx context.Context) HcloudPublisherOutput {
	return o
}

func (o HcloudPublisherOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) AssignPublicIp() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.BoolPtrOutput { return v.AssignPublicIp }).(pulumi.BoolPtrOutput)
}

func (o HcloudPublisherOutput) AuthMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.AuthMode }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) BearerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.BearerToken }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) Bootstrap() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.BoolPtrOutput { return v.Bootstrap }).(pulumi.BoolPtrOutput)
}

func (o HcloudPublisherOutput) BootstrapUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.BootstrapUrl }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) Datacenter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.Datacenter }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) DeleteDefaultUser() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.BoolPtrOutput { return v.DeleteDefaultUser }).(pulumi.BoolPtrOutput)
}

func (o HcloudPublisherOutput) FirewallIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.IntArrayOutput { return v.FirewallIds }).(pulumi.IntArrayOutput)
}

func (o HcloudPublisherOutput) GuestNetworkInterface() provider.GuestNetworkInterfacePtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) provider.GuestNetworkInterfacePtrOutput { return v.GuestNetworkInterface }).(provider.GuestNetworkInterfacePtrOutput)
}

func (o HcloudPublisherOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.Image }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) InstallUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.InstallUser }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) InstallUserPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.InstallUserPassword }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) InstallUserPasswordIsHash() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.BoolPtrOutput { return v.InstallUserPasswordIsHash }).(pulumi.BoolPtrOutput)
}

func (o HcloudPublisherOutput) InstallUserSshAuthorizedKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringArrayOutput { return v.InstallUserSshAuthorizedKeys }).(pulumi.StringArrayOutput)
}

func (o HcloudPublisherOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.Location }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) NamePrefix() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.NamePrefix }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) Names() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringArrayOutput { return v.Names }).(pulumi.StringArrayOutput)
}

func (o HcloudPublisherOutput) NetworkId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.IntPtrOutput { return v.NetworkId }).(pulumi.IntPtrOutput)
}

func (o HcloudPublisherOutput) Nonat() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.BoolPtrOutput { return v.Nonat }).(pulumi.BoolPtrOutput)
}

func (o HcloudPublisherOutput) Oauth2() provider.NetskopeOAuth2ArgsPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) provider.NetskopeOAuth2ArgsPtrOutput { return v.Oauth2 }).(provider.NetskopeOAuth2ArgsPtrOutput)
}

func (o HcloudPublisherOutput) PublisherNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringArrayOutput { return v.PublisherNames }).(pulumi.StringArrayOutput)
}

func (o HcloudPublisherOutput) Publishers() pulumi.MapOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.MapOutput { return v.Publishers }).(pulumi.MapOutput)
}

func (o HcloudPublisherOutput) Registrations() provider.PublisherRegistrationInputMapOutput {
	return o.ApplyT(func(v *HcloudPublisher) provider.PublisherRegistrationInputMapOutput { return v.Registrations }).(provider.PublisherRegistrationInputMapOutput)
}

func (o HcloudPublisherOutput) Replicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.IntPtrOutput { return v.Replicas }).(pulumi.IntPtrOutput)
}

func (o HcloudPublisherOutput) ServerType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.ServerType }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) SshKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringArrayOutput { return v.SshKeys }).(pulumi.StringArrayOutput)
}

func (o HcloudPublisherOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

func (o HcloudPublisherOutput) TenantUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.TenantUrl }).(pulumi.StringPtrOutput)
}

func (o HcloudPublisherOutput) WizardPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HcloudPublisher) pulumi.StringPtrOutput { return v.WizardPath }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HcloudPublisherInput)(nil)).Elem(), &HcloudPublisher{})
	pulumi.RegisterOutputType(HcloudPublisherOutput{})
}
