// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"errors"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Experimental component for creating one or more Netskope Private Access Publisher Hyper-V virtual machines.
type HypervPublisher struct {
	pulumi.ResourceState

	// Created publisher names.
	PublisherNames pulumi.StringArrayOutput `pulumi:"publisherNames"`
	// Publisher registration and VM details keyed by name.
	Publishers PublisherOutputMapPtrOutput `pulumi:"publishers"`
}

// NewHypervPublisher registers a new resource with the given unique name, arguments, and options.
func NewHypervPublisher(ctx *pulumi.Context,
	name string, args *HypervPublisherArgs, opts ...pulumi.ResourceOption) (*HypervPublisher, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.HardDrives == nil {
		return nil, errors.New("invalid value for required argument 'HardDrives'")
	}
	if args.SwitchName == nil {
		return nil, errors.New("invalid value for required argument 'SwitchName'")
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource HypervPublisher
	err := ctx.RegisterRemoteComponentResource("netskope-publisher:index:HypervPublisher", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type hypervPublisherArgs struct {
	// Netskope API token used for publisher registration.
	ApiToken *string `pulumi:"apiToken"`
	// Hyper-V automatic start action.
	AutoStartAction *string `pulumi:"autoStartAction"`
	// Hyper-V automatic stop action.
	AutoStopAction *string `pulumi:"autoStopAction"`
	// Whether to enable dynamic memory.
	DynamicMemory *bool `pulumi:"dynamicMemory"`
	// Required opt-in gate for the experimental Hyper-V component.
	EnableExperimentalHyperv *bool `pulumi:"enableExperimentalHyperv"`
	// Hyper-V VM generation.
	Generation *int `pulumi:"generation"`
	// Virtual hard disks attached to each VM.
	HardDrives []HypervHardDrive `pulumi:"hardDrives"`
	// Maximum dynamic memory in bytes.
	MaximumMemory *int `pulumi:"maximumMemory"`
	// Startup memory in bytes.
	MemorySize *int `pulumi:"memorySize"`
	// Minimum dynamic memory in bytes.
	MinimumMemory *int `pulumi:"minimumMemory"`
	// Prefix used to derive publisher names when explicit names are not supplied.
	NamePrefix *string `pulumi:"namePrefix"`
	// Explicit publisher names to create.
	Names []string `pulumi:"names"`
	// Virtual processor count.
	ProcessorCount *int `pulumi:"processorCount"`
	// Pre-created Netskope publisher registrations keyed by publisher name.
	Registrations *PublisherRegistrationMap `pulumi:"registrations"`
	// Number of publishers to create when names are not supplied.
	Replicas *int `pulumi:"replicas"`
	// Hyper-V virtual switch name.
	SwitchName string `pulumi:"switchName"`
	// Netskope tenant URL used for publisher registration.
	TenantUrl *string `pulumi:"tenantUrl"`
	// Netskope publisher registration wizard API path.
	WizardPath *string `pulumi:"wizardPath"`
}

// The set of arguments for constructing a HypervPublisher resource.
type HypervPublisherArgs struct {
	// Netskope API token used for publisher registration.
	ApiToken pulumi.StringPtrInput
	// Hyper-V automatic start action.
	AutoStartAction pulumi.StringPtrInput
	// Hyper-V automatic stop action.
	AutoStopAction pulumi.StringPtrInput
	// Whether to enable dynamic memory.
	DynamicMemory pulumi.BoolPtrInput
	// Required opt-in gate for the experimental Hyper-V component.
	EnableExperimentalHyperv pulumi.BoolPtrInput
	// Hyper-V VM generation.
	Generation pulumi.IntPtrInput
	// Virtual hard disks attached to each VM.
	HardDrives HypervHardDriveArrayInput
	// Maximum dynamic memory in bytes.
	MaximumMemory pulumi.IntPtrInput
	// Startup memory in bytes.
	MemorySize pulumi.IntPtrInput
	// Minimum dynamic memory in bytes.
	MinimumMemory pulumi.IntPtrInput
	// Prefix used to derive publisher names when explicit names are not supplied.
	NamePrefix pulumi.StringPtrInput
	// Explicit publisher names to create.
	Names pulumi.StringArrayInput
	// Virtual processor count.
	ProcessorCount pulumi.IntPtrInput
	// Pre-created Netskope publisher registrations keyed by publisher name.
	Registrations PublisherRegistrationMapPtrInput
	// Number of publishers to create when names are not supplied.
	Replicas pulumi.IntPtrInput
	// Hyper-V virtual switch name.
	SwitchName pulumi.StringInput
	// Netskope tenant URL used for publisher registration.
	TenantUrl pulumi.StringPtrInput
	// Netskope publisher registration wizard API path.
	WizardPath pulumi.StringPtrInput
}

func (HypervPublisherArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hypervPublisherArgs)(nil)).Elem()
}

type HypervPublisherInput interface {
	pulumi.Input

	ToHypervPublisherOutput() HypervPublisherOutput
	ToHypervPublisherOutputWithContext(ctx context.Context) HypervPublisherOutput
}

func (*HypervPublisher) ElementType() reflect.Type {
	return reflect.TypeOf((**HypervPublisher)(nil)).Elem()
}

func (i *HypervPublisher) ToHypervPublisherOutput() HypervPublisherOutput {
	return i.ToHypervPublisherOutputWithContext(context.Background())
}

func (i *HypervPublisher) ToHypervPublisherOutputWithContext(ctx context.Context) HypervPublisherOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HypervPublisherOutput)
}

type HypervPublisherOutput struct{ *pulumi.OutputState }

func (HypervPublisherOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HypervPublisher)(nil)).Elem()
}

func (o HypervPublisherOutput) ToHypervPublisherOutput() HypervPublisherOutput {
	return o
}

func (o HypervPublisherOutput) ToHypervPublisherOutputWithContext(ctx context.Context) HypervPublisherOutput {
	return o
}

// Created publisher names.
func (o HypervPublisherOutput) PublisherNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *HypervPublisher) pulumi.StringArrayOutput { return v.PublisherNames }).(pulumi.StringArrayOutput)
}

// Publisher registration and VM details keyed by name.
func (o HypervPublisherOutput) Publishers() PublisherOutputMapPtrOutput {
	return o.ApplyT(func(v *HypervPublisher) PublisherOutputMapPtrOutput { return v.Publishers }).(PublisherOutputMapPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HypervPublisherInput)(nil)).Elem(), &HypervPublisher{})
	pulumi.RegisterOutputType(HypervPublisherOutput{})
}
