// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "netskope-publisher:index:AlicloudPublisher":
		r = &AlicloudPublisher{}
	case "netskope-publisher:index:AwsPublisher":
		r = &AwsPublisher{}
	case "netskope-publisher:index:AzurePublisher":
		r = &AzurePublisher{}
	case "netskope-publisher:index:EsxiPublisher":
		r = &EsxiPublisher{}
	case "netskope-publisher:index:GcpPublisher":
		r = &GcpPublisher{}
	case "netskope-publisher:index:HcloudPublisher":
		r = &HcloudPublisher{}
	case "netskope-publisher:index:HypervPublisher":
		r = &HypervPublisher{}
	case "netskope-publisher:index:KubernetesPublisher":
		r = &KubernetesPublisher{}
	case "netskope-publisher:index:NetskopeRegistration":
		r = &NetskopeRegistration{}
	case "netskope-publisher:index:NutanixPublisher":
		r = &NutanixPublisher{}
	case "netskope-publisher:index:OciPublisher":
		r = &OciPublisher{}
	case "netskope-publisher:index:OpenstackPublisher":
		r = &OpenstackPublisher{}
	case "netskope-publisher:index:OvhPublisher":
		r = &OvhPublisher{}
	case "netskope-publisher:index:ProxmoxvePublisher":
		r = &ProxmoxvePublisher{}
	case "netskope-publisher:index:ScalewayPublisher":
		r = &ScalewayPublisher{}
	case "netskope-publisher:index:VspherePublisher":
		r = &VspherePublisher{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:netskope-publisher" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"netskope-publisher",
		"index",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"netskope-publisher",
		&pkg{version},
	)
}
