// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"errors"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Stateful Netskope publisher registration resource.
type NetskopeRegistration struct {
	pulumi.CustomResourceState

	// Netskope API token used for publisher registration.
	ApiToken pulumi.StringOutput `pulumi:"apiToken"`
	// Publisher names registered or reused in Netskope.
	PublisherNames pulumi.StringArrayOutput `pulumi:"publisherNames"`
	// Netskope publisher registrations keyed by publisher name.
	Registrations PublisherRegistrationMapOutput `pulumi:"registrations"`
	// Netskope tenant URL used for publisher registration.
	TenantUrl pulumi.StringOutput `pulumi:"tenantUrl"`
}

// NewNetskopeRegistration registers a new resource with the given unique name, arguments, and options.
func NewNetskopeRegistration(ctx *pulumi.Context,
	name string, args *NetskopeRegistrationArgs, opts ...pulumi.ResourceOption) (*NetskopeRegistration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiToken == nil {
		return nil, errors.New("invalid value for required argument 'ApiToken'")
	}
	if args.PublisherNames == nil {
		return nil, errors.New("invalid value for required argument 'PublisherNames'")
	}
	if args.TenantUrl == nil {
		return nil, errors.New("invalid value for required argument 'TenantUrl'")
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetskopeRegistration
	err := ctx.RegisterResource("netskope-publisher:index:NetskopeRegistration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetskopeRegistration gets an existing NetskopeRegistration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetskopeRegistration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetskopeRegistrationState, opts ...pulumi.ResourceOption) (*NetskopeRegistration, error) {
	var resource NetskopeRegistration
	err := ctx.ReadResource("netskope-publisher:index:NetskopeRegistration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetskopeRegistration resources.
type netskopeRegistrationState struct {
}

type NetskopeRegistrationState struct {
}

func (NetskopeRegistrationState) ElementType() reflect.Type {
	return reflect.TypeOf((*netskopeRegistrationState)(nil)).Elem()
}

type netskopeRegistrationArgs struct {
	// Netskope API token used for publisher registration.
	ApiToken string `pulumi:"apiToken"`
	// Publisher names to register or reuse in Netskope.
	PublisherNames []string `pulumi:"publisherNames"`
	// Netskope tenant URL used for publisher registration.
	TenantUrl string `pulumi:"tenantUrl"`
}

// The set of arguments for constructing a NetskopeRegistration resource.
type NetskopeRegistrationArgs struct {
	// Netskope API token used for publisher registration.
	ApiToken pulumi.StringInput
	// Publisher names to register or reuse in Netskope.
	PublisherNames pulumi.StringArrayInput
	// Netskope tenant URL used for publisher registration.
	TenantUrl pulumi.StringInput
}

func (NetskopeRegistrationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netskopeRegistrationArgs)(nil)).Elem()
}

type NetskopeRegistrationInput interface {
	pulumi.Input

	ToNetskopeRegistrationOutput() NetskopeRegistrationOutput
	ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput
}

func (*NetskopeRegistration) ElementType() reflect.Type {
	return reflect.TypeOf((**NetskopeRegistration)(nil)).Elem()
}

func (i *NetskopeRegistration) ToNetskopeRegistrationOutput() NetskopeRegistrationOutput {
	return i.ToNetskopeRegistrationOutputWithContext(context.Background())
}

func (i *NetskopeRegistration) ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetskopeRegistrationOutput)
}

type NetskopeRegistrationOutput struct{ *pulumi.OutputState }

func (NetskopeRegistrationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetskopeRegistration)(nil)).Elem()
}

func (o NetskopeRegistrationOutput) ToNetskopeRegistrationOutput() NetskopeRegistrationOutput {
	return o
}

func (o NetskopeRegistrationOutput) ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput {
	return o
}

// Netskope API token used for publisher registration.
func (o NetskopeRegistrationOutput) ApiToken() pulumi.StringOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringOutput { return v.ApiToken }).(pulumi.StringOutput)
}

// Publisher names registered or reused in Netskope.
func (o NetskopeRegistrationOutput) PublisherNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringArrayOutput { return v.PublisherNames }).(pulumi.StringArrayOutput)
}

// Netskope publisher registrations keyed by publisher name.
func (o NetskopeRegistrationOutput) Registrations() PublisherRegistrationMapOutput {
	return o.ApplyT(func(v *NetskopeRegistration) PublisherRegistrationMapOutput { return v.Registrations }).(PublisherRegistrationMapOutput)
}

// Netskope tenant URL used for publisher registration.
func (o NetskopeRegistrationOutput) TenantUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringOutput { return v.TenantUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetskopeRegistrationInput)(nil)).Elem(), &NetskopeRegistration{})
	pulumi.RegisterOutputType(NetskopeRegistrationOutput{})
}
