// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"errors"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/provider"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetskopeRegistration struct {
	pulumi.CustomResourceState

	ApiToken       pulumi.StringPtrOutput               `pulumi:"apiToken"`
	AuthMode       pulumi.StringPtrOutput               `pulumi:"authMode"`
	BearerToken    pulumi.StringPtrOutput               `pulumi:"bearerToken"`
	Oauth2         provider.NetskopeOAuth2ArgsPtrOutput `pulumi:"oauth2"`
	PublisherNames pulumi.StringArrayOutput             `pulumi:"publisherNames"`
	Registrations  provider.RegistrationRecordMapOutput `pulumi:"registrations"`
	TenantUrl      pulumi.StringOutput                  `pulumi:"tenantUrl"`
}

// NewNetskopeRegistration registers a new resource with the given unique name, arguments, and options.
func NewNetskopeRegistration(ctx *pulumi.Context,
	name string, args *NetskopeRegistrationArgs, opts ...pulumi.ResourceOption) (*NetskopeRegistration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PublisherNames == nil {
		return nil, errors.New("invalid value for required argument 'PublisherNames'")
	}
	if args.TenantUrl == nil {
		return nil, errors.New("invalid value for required argument 'TenantUrl'")
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	if args.BearerToken != nil {
		args.BearerToken = pulumi.ToSecret(args.BearerToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
		"bearerToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetskopeRegistration
	err := ctx.RegisterResource("netskope-publisher:index:NetskopeRegistration", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetskopeRegistration gets an existing NetskopeRegistration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetskopeRegistration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetskopeRegistrationState, opts ...pulumi.ResourceOption) (*NetskopeRegistration, error) {
	var resource NetskopeRegistration
	err := ctx.ReadResource("netskope-publisher:index:NetskopeRegistration", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetskopeRegistration resources.
type netskopeRegistrationState struct {
}

type NetskopeRegistrationState struct {
}

func (NetskopeRegistrationState) ElementType() reflect.Type {
	return reflect.TypeOf((*netskopeRegistrationState)(nil)).Elem()
}

type netskopeRegistrationArgs struct {
	ApiToken       *string                      `pulumi:"apiToken"`
	AuthMode       *string                      `pulumi:"authMode"`
	BearerToken    *string                      `pulumi:"bearerToken"`
	Oauth2         *provider.NetskopeOAuth2Args `pulumi:"oauth2"`
	PublisherNames []string                     `pulumi:"publisherNames"`
	TenantUrl      string                       `pulumi:"tenantUrl"`
}

// The set of arguments for constructing a NetskopeRegistration resource.
type NetskopeRegistrationArgs struct {
	ApiToken       pulumi.StringPtrInput
	AuthMode       pulumi.StringPtrInput
	BearerToken    pulumi.StringPtrInput
	Oauth2         provider.NetskopeOAuth2ArgsPtrInput
	PublisherNames pulumi.StringArrayInput
	TenantUrl      pulumi.StringInput
}

func (NetskopeRegistrationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netskopeRegistrationArgs)(nil)).Elem()
}

type NetskopeRegistrationInput interface {
	pulumi.Input

	ToNetskopeRegistrationOutput() NetskopeRegistrationOutput
	ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput
}

func (*NetskopeRegistration) ElementType() reflect.Type {
	return reflect.TypeOf((**NetskopeRegistration)(nil)).Elem()
}

func (i *NetskopeRegistration) ToNetskopeRegistrationOutput() NetskopeRegistrationOutput {
	return i.ToNetskopeRegistrationOutputWithContext(context.Background())
}

func (i *NetskopeRegistration) ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetskopeRegistrationOutput)
}

type NetskopeRegistrationOutput struct{ *pulumi.OutputState }

func (NetskopeRegistrationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetskopeRegistration)(nil)).Elem()
}

func (o NetskopeRegistrationOutput) ToNetskopeRegistrationOutput() NetskopeRegistrationOutput {
	return o
}

func (o NetskopeRegistrationOutput) ToNetskopeRegistrationOutputWithContext(ctx context.Context) NetskopeRegistrationOutput {
	return o
}

func (o NetskopeRegistrationOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

func (o NetskopeRegistrationOutput) AuthMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringPtrOutput { return v.AuthMode }).(pulumi.StringPtrOutput)
}

func (o NetskopeRegistrationOutput) BearerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringPtrOutput { return v.BearerToken }).(pulumi.StringPtrOutput)
}

func (o NetskopeRegistrationOutput) Oauth2() provider.NetskopeOAuth2ArgsPtrOutput {
	return o.ApplyT(func(v *NetskopeRegistration) provider.NetskopeOAuth2ArgsPtrOutput { return v.Oauth2 }).(provider.NetskopeOAuth2ArgsPtrOutput)
}

func (o NetskopeRegistrationOutput) PublisherNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringArrayOutput { return v.PublisherNames }).(pulumi.StringArrayOutput)
}

func (o NetskopeRegistrationOutput) Registrations() provider.RegistrationRecordMapOutput {
	return o.ApplyT(func(v *NetskopeRegistration) provider.RegistrationRecordMapOutput { return v.Registrations }).(provider.RegistrationRecordMapOutput)
}

func (o NetskopeRegistrationOutput) TenantUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *NetskopeRegistration) pulumi.StringOutput { return v.TenantUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetskopeRegistrationInput)(nil)).Elem(), &NetskopeRegistration{})
	pulumi.RegisterOutputType(NetskopeRegistrationOutput{})
}
