// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package netskopepublisher

import (
	"context"
	"reflect"

	"errors"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/internal"
	"github.com/johnneerdael/pulumi-netskope-publisher/sdk/go/netskopepublisher/provider"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TagPublisherAssignment struct {
	pulumi.CustomResourceState

	ApiToken                 pulumi.StringPtrOutput                     `pulumi:"apiToken"`
	AppTags                  pulumi.StringArrayOutput                   `pulumi:"appTags"`
	AuthMode                 pulumi.StringPtrOutput                     `pulumi:"authMode"`
	BearerToken              pulumi.StringPtrOutput                     `pulumi:"bearerToken"`
	MatchMode                pulumi.StringPtrOutput                     `pulumi:"matchMode"`
	MatchedApps              pulumi.StringArrayOutput                   `pulumi:"matchedApps"`
	Oauth2                   provider.NetskopeOAuth2ArgsPtrOutput       `pulumi:"oauth2"`
	PublisherPlacementLabels pulumi.StringArrayOutput                   `pulumi:"publisherPlacementLabels"`
	Publishers               provider.PublisherAssignmentInputMapOutput `pulumi:"publishers"`
	SelectedPublishers       pulumi.IntArrayOutput                      `pulumi:"selectedPublishers"`
	TenantUrl                pulumi.StringOutput                        `pulumi:"tenantUrl"`
}

// NewTagPublisherAssignment registers a new resource with the given unique name, arguments, and options.
func NewTagPublisherAssignment(ctx *pulumi.Context,
	name string, args *TagPublisherAssignmentArgs, opts ...pulumi.ResourceOption) (*TagPublisherAssignment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AppTags == nil {
		return nil, errors.New("invalid value for required argument 'AppTags'")
	}
	if args.PublisherPlacementLabels == nil {
		return nil, errors.New("invalid value for required argument 'PublisherPlacementLabels'")
	}
	if args.Publishers == nil {
		return nil, errors.New("invalid value for required argument 'Publishers'")
	}
	if args.TenantUrl == nil {
		return nil, errors.New("invalid value for required argument 'TenantUrl'")
	}
	if args.ApiToken != nil {
		args.ApiToken = pulumi.ToSecret(args.ApiToken).(pulumi.StringPtrInput)
	}
	if args.BearerToken != nil {
		args.BearerToken = pulumi.ToSecret(args.BearerToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiToken",
		"bearerToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TagPublisherAssignment
	err := ctx.RegisterResource("netskope-publisher:index:TagPublisherAssignment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTagPublisherAssignment gets an existing TagPublisherAssignment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTagPublisherAssignment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TagPublisherAssignmentState, opts ...pulumi.ResourceOption) (*TagPublisherAssignment, error) {
	var resource TagPublisherAssignment
	err := ctx.ReadResource("netskope-publisher:index:TagPublisherAssignment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TagPublisherAssignment resources.
type tagPublisherAssignmentState struct {
}

type TagPublisherAssignmentState struct {
}

func (TagPublisherAssignmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*tagPublisherAssignmentState)(nil)).Elem()
}

type tagPublisherAssignmentArgs struct {
	ApiToken                 *string                                      `pulumi:"apiToken"`
	AppTags                  []string                                     `pulumi:"appTags"`
	AuthMode                 *string                                      `pulumi:"authMode"`
	BearerToken              *string                                      `pulumi:"bearerToken"`
	MatchMode                *string                                      `pulumi:"matchMode"`
	Oauth2                   *provider.NetskopeOAuth2Args                 `pulumi:"oauth2"`
	PublisherPlacementLabels []string                                     `pulumi:"publisherPlacementLabels"`
	Publishers               map[string]provider.PublisherAssignmentInput `pulumi:"publishers"`
	TenantUrl                string                                       `pulumi:"tenantUrl"`
}

// The set of arguments for constructing a TagPublisherAssignment resource.
type TagPublisherAssignmentArgs struct {
	ApiToken                 pulumi.StringPtrInput
	AppTags                  pulumi.StringArrayInput
	AuthMode                 pulumi.StringPtrInput
	BearerToken              pulumi.StringPtrInput
	MatchMode                pulumi.StringPtrInput
	Oauth2                   provider.NetskopeOAuth2ArgsPtrInput
	PublisherPlacementLabels pulumi.StringArrayInput
	Publishers               provider.PublisherAssignmentInputMapInput
	TenantUrl                pulumi.StringInput
}

func (TagPublisherAssignmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tagPublisherAssignmentArgs)(nil)).Elem()
}

type TagPublisherAssignmentInput interface {
	pulumi.Input

	ToTagPublisherAssignmentOutput() TagPublisherAssignmentOutput
	ToTagPublisherAssignmentOutputWithContext(ctx context.Context) TagPublisherAssignmentOutput
}

func (*TagPublisherAssignment) ElementType() reflect.Type {
	return reflect.TypeOf((**TagPublisherAssignment)(nil)).Elem()
}

func (i *TagPublisherAssignment) ToTagPublisherAssignmentOutput() TagPublisherAssignmentOutput {
	return i.ToTagPublisherAssignmentOutputWithContext(context.Background())
}

func (i *TagPublisherAssignment) ToTagPublisherAssignmentOutputWithContext(ctx context.Context) TagPublisherAssignmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TagPublisherAssignmentOutput)
}

type TagPublisherAssignmentOutput struct{ *pulumi.OutputState }

func (TagPublisherAssignmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TagPublisherAssignment)(nil)).Elem()
}

func (o TagPublisherAssignmentOutput) ToTagPublisherAssignmentOutput() TagPublisherAssignmentOutput {
	return o
}

func (o TagPublisherAssignmentOutput) ToTagPublisherAssignmentOutputWithContext(ctx context.Context) TagPublisherAssignmentOutput {
	return o
}

func (o TagPublisherAssignmentOutput) ApiToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringPtrOutput { return v.ApiToken }).(pulumi.StringPtrOutput)
}

func (o TagPublisherAssignmentOutput) AppTags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringArrayOutput { return v.AppTags }).(pulumi.StringArrayOutput)
}

func (o TagPublisherAssignmentOutput) AuthMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringPtrOutput { return v.AuthMode }).(pulumi.StringPtrOutput)
}

func (o TagPublisherAssignmentOutput) BearerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringPtrOutput { return v.BearerToken }).(pulumi.StringPtrOutput)
}

func (o TagPublisherAssignmentOutput) MatchMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringPtrOutput { return v.MatchMode }).(pulumi.StringPtrOutput)
}

func (o TagPublisherAssignmentOutput) MatchedApps() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringArrayOutput { return v.MatchedApps }).(pulumi.StringArrayOutput)
}

func (o TagPublisherAssignmentOutput) Oauth2() provider.NetskopeOAuth2ArgsPtrOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) provider.NetskopeOAuth2ArgsPtrOutput { return v.Oauth2 }).(provider.NetskopeOAuth2ArgsPtrOutput)
}

func (o TagPublisherAssignmentOutput) PublisherPlacementLabels() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringArrayOutput { return v.PublisherPlacementLabels }).(pulumi.StringArrayOutput)
}

func (o TagPublisherAssignmentOutput) Publishers() provider.PublisherAssignmentInputMapOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) provider.PublisherAssignmentInputMapOutput { return v.Publishers }).(provider.PublisherAssignmentInputMapOutput)
}

func (o TagPublisherAssignmentOutput) SelectedPublishers() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.IntArrayOutput { return v.SelectedPublishers }).(pulumi.IntArrayOutput)
}

func (o TagPublisherAssignmentOutput) TenantUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *TagPublisherAssignment) pulumi.StringOutput { return v.TenantUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TagPublisherAssignmentInput)(nil)).Elem(), &TagPublisherAssignment{})
	pulumi.RegisterOutputType(TagPublisherAssignmentOutput{})
}
