// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AzureMarketplaceImage {
    private String offer;
    private String publisher;
    private String sku;
    private @Nullable String version;

    private AzureMarketplaceImage() {}
    public String offer() {
        return this.offer;
    }
    public String publisher() {
        return this.publisher;
    }
    public String sku() {
        return this.sku;
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AzureMarketplaceImage defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String offer;
        private String publisher;
        private String sku;
        private @Nullable String version;
        public Builder() {}
        public Builder(AzureMarketplaceImage defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.offer = defaults.offer;
    	      this.publisher = defaults.publisher;
    	      this.sku = defaults.sku;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder offer(String offer) {
            if (offer == null) {
              throw new MissingRequiredPropertyException("AzureMarketplaceImage", "offer");
            }
            this.offer = offer;
            return this;
        }
        @CustomType.Setter
        public Builder publisher(String publisher) {
            if (publisher == null) {
              throw new MissingRequiredPropertyException("AzureMarketplaceImage", "publisher");
            }
            this.publisher = publisher;
            return this;
        }
        @CustomType.Setter
        public Builder sku(String sku) {
            if (sku == null) {
              throw new MissingRequiredPropertyException("AzureMarketplaceImage", "sku");
            }
            this.sku = sku;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public AzureMarketplaceImage build() {
            final var _resultValue = new AzureMarketplaceImage();
            _resultValue.offer = offer;
            _resultValue.publisher = publisher;
            _resultValue.sku = sku;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
