// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class HypervHardDrive {
    private @Nullable Integer controllerLocation;
    private @Nullable Integer controllerNumber;
    private @Nullable String controllerType;
    private String path;

    private HypervHardDrive() {}
    public Optional<Integer> controllerLocation() {
        return Optional.ofNullable(this.controllerLocation);
    }
    public Optional<Integer> controllerNumber() {
        return Optional.ofNullable(this.controllerNumber);
    }
    public Optional<String> controllerType() {
        return Optional.ofNullable(this.controllerType);
    }
    public String path() {
        return this.path;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(HypervHardDrive defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer controllerLocation;
        private @Nullable Integer controllerNumber;
        private @Nullable String controllerType;
        private String path;
        public Builder() {}
        public Builder(HypervHardDrive defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.controllerLocation = defaults.controllerLocation;
    	      this.controllerNumber = defaults.controllerNumber;
    	      this.controllerType = defaults.controllerType;
    	      this.path = defaults.path;
        }

        @CustomType.Setter
        public Builder controllerLocation(@Nullable Integer controllerLocation) {

            this.controllerLocation = controllerLocation;
            return this;
        }
        @CustomType.Setter
        public Builder controllerNumber(@Nullable Integer controllerNumber) {

            this.controllerNumber = controllerNumber;
            return this;
        }
        @CustomType.Setter
        public Builder controllerType(@Nullable String controllerType) {

            this.controllerType = controllerType;
            return this;
        }
        @CustomType.Setter
        public Builder path(String path) {
            if (path == null) {
              throw new MissingRequiredPropertyException("HypervHardDrive", "path");
            }
            this.path = path;
            return this;
        }
        public HypervHardDrive build() {
            final var _resultValue = new HypervHardDrive();
            _resultValue.controllerLocation = controllerLocation;
            _resultValue.controllerNumber = controllerNumber;
            _resultValue.controllerType = controllerType;
            _resultValue.path = path;
            return _resultValue;
        }
    }
}
