// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.provider.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PrivateAppPublisher {
    private Integer publisherId;
    private @Nullable String publisherName;

    private PrivateAppPublisher() {}
    public Integer publisherId() {
        return this.publisherId;
    }
    public Optional<String> publisherName() {
        return Optional.ofNullable(this.publisherName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PrivateAppPublisher defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer publisherId;
        private @Nullable String publisherName;
        public Builder() {}
        public Builder(PrivateAppPublisher defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.publisherId = defaults.publisherId;
    	      this.publisherName = defaults.publisherName;
        }

        @CustomType.Setter
        public Builder publisherId(Integer publisherId) {
            if (publisherId == null) {
              throw new MissingRequiredPropertyException("PrivateAppPublisher", "publisherId");
            }
            this.publisherId = publisherId;
            return this;
        }
        @CustomType.Setter
        public Builder publisherName(@Nullable String publisherName) {

            this.publisherName = publisherName;
            return this;
        }
        public PrivateAppPublisher build() {
            final var _resultValue = new PrivateAppPublisher();
            _resultValue.publisherId = publisherId;
            _resultValue.publisherName = publisherName;
            return _resultValue;
        }
    }
}
