// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Azure marketplace image reference.
 * 
 */
public final class AzureMarketplaceImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final AzureMarketplaceImageArgs Empty = new AzureMarketplaceImageArgs();

    /**
     * Marketplace offer.
     * 
     */
    @Import(name="offer", required=true)
    private Output<String> offer;

    /**
     * @return Marketplace offer.
     * 
     */
    public Output<String> offer() {
        return this.offer;
    }

    /**
     * Marketplace publisher.
     * 
     */
    @Import(name="publisher", required=true)
    private Output<String> publisher;

    /**
     * @return Marketplace publisher.
     * 
     */
    public Output<String> publisher() {
        return this.publisher;
    }

    /**
     * Marketplace SKU.
     * 
     */
    @Import(name="sku", required=true)
    private Output<String> sku;

    /**
     * @return Marketplace SKU.
     * 
     */
    public Output<String> sku() {
        return this.sku;
    }

    /**
     * Marketplace image version.
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return Marketplace image version.
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private AzureMarketplaceImageArgs() {}

    private AzureMarketplaceImageArgs(AzureMarketplaceImageArgs $) {
        this.offer = $.offer;
        this.publisher = $.publisher;
        this.sku = $.sku;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AzureMarketplaceImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AzureMarketplaceImageArgs $;

        public Builder() {
            $ = new AzureMarketplaceImageArgs();
        }

        public Builder(AzureMarketplaceImageArgs defaults) {
            $ = new AzureMarketplaceImageArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param offer Marketplace offer.
         * 
         * @return builder
         * 
         */
        public Builder offer(Output<String> offer) {
            $.offer = offer;
            return this;
        }

        /**
         * @param offer Marketplace offer.
         * 
         * @return builder
         * 
         */
        public Builder offer(String offer) {
            return offer(Output.of(offer));
        }

        /**
         * @param publisher Marketplace publisher.
         * 
         * @return builder
         * 
         */
        public Builder publisher(Output<String> publisher) {
            $.publisher = publisher;
            return this;
        }

        /**
         * @param publisher Marketplace publisher.
         * 
         * @return builder
         * 
         */
        public Builder publisher(String publisher) {
            return publisher(Output.of(publisher));
        }

        /**
         * @param sku Marketplace SKU.
         * 
         * @return builder
         * 
         */
        public Builder sku(Output<String> sku) {
            $.sku = sku;
            return this;
        }

        /**
         * @param sku Marketplace SKU.
         * 
         * @return builder
         * 
         */
        public Builder sku(String sku) {
            return sku(Output.of(sku));
        }

        /**
         * @param version Marketplace image version.
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Marketplace image version.
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public AzureMarketplaceImageArgs build() {
            if ($.offer == null) {
                throw new MissingRequiredPropertyException("AzureMarketplaceImageArgs", "offer");
            }
            if ($.publisher == null) {
                throw new MissingRequiredPropertyException("AzureMarketplaceImageArgs", "publisher");
            }
            if ($.sku == null) {
                throw new MissingRequiredPropertyException("AzureMarketplaceImageArgs", "sku");
            }
            return $;
        }
    }

}
