# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'AzureMarketplaceImageArgs',
    'AzureMarketplaceImageArgsDict',
    'AzureOsDiskArgs',
    'AzureOsDiskArgsDict',
    'GcpServiceAccountArgs',
    'GcpServiceAccountArgsDict',
    'HypervHardDriveArgs',
    'HypervHardDriveArgsDict',
    'MetadataOptionsArgs',
    'MetadataOptionsArgsDict',
    'PublisherRegistrationMapArgs',
    'PublisherRegistrationMapArgsDict',
]

class AzureMarketplaceImageArgsDict(TypedDict):
    """
    Azure marketplace image reference.
    """
    offer: pulumi.Input[_builtins.str]
    """
    Marketplace offer.
    """
    publisher: pulumi.Input[_builtins.str]
    """
    Marketplace publisher.
    """
    sku: pulumi.Input[_builtins.str]
    """
    Marketplace SKU.
    """
    version: NotRequired[pulumi.Input[_builtins.str]]
    """
    Marketplace image version.
    """

@pulumi.input_type
class AzureMarketplaceImageArgs:
    def __init__(__self__, *,
                 offer: pulumi.Input[_builtins.str],
                 publisher: pulumi.Input[_builtins.str],
                 sku: pulumi.Input[_builtins.str],
                 version: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Azure marketplace image reference.

        :param pulumi.Input[_builtins.str] offer: Marketplace offer.
        :param pulumi.Input[_builtins.str] publisher: Marketplace publisher.
        :param pulumi.Input[_builtins.str] sku: Marketplace SKU.
        :param pulumi.Input[_builtins.str] version: Marketplace image version.
        """
        pulumi.set(__self__, "offer", offer)
        pulumi.set(__self__, "publisher", publisher)
        pulumi.set(__self__, "sku", sku)
        if version is not None:
            pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def offer(self) -> pulumi.Input[_builtins.str]:
        """
        Marketplace offer.
        """
        return pulumi.get(self, "offer")

    @offer.setter
    def offer(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "offer", value)

    @_builtins.property
    @pulumi.getter
    def publisher(self) -> pulumi.Input[_builtins.str]:
        """
        Marketplace publisher.
        """
        return pulumi.get(self, "publisher")

    @publisher.setter
    def publisher(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "publisher", value)

    @_builtins.property
    @pulumi.getter
    def sku(self) -> pulumi.Input[_builtins.str]:
        """
        Marketplace SKU.
        """
        return pulumi.get(self, "sku")

    @sku.setter
    def sku(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "sku", value)

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Marketplace image version.
        """
        return pulumi.get(self, "version")

    @version.setter
    def version(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "version", value)


class AzureOsDiskArgsDict(TypedDict):
    """
    Azure managed OS disk options.
    """
    size_gb: NotRequired[pulumi.Input[_builtins.int]]
    """
    OS disk size in GiB.
    """
    type: NotRequired[pulumi.Input[_builtins.str]]
    """
    Managed disk storage account type.
    """

@pulumi.input_type
class AzureOsDiskArgs:
    def __init__(__self__, *,
                 size_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Azure managed OS disk options.

        :param pulumi.Input[_builtins.int] size_gb: OS disk size in GiB.
        :param pulumi.Input[_builtins.str] type: Managed disk storage account type.
        """
        if size_gb is not None:
            pulumi.set(__self__, "size_gb", size_gb)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="sizeGb")
    def size_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        OS disk size in GiB.
        """
        return pulumi.get(self, "size_gb")

    @size_gb.setter
    def size_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "size_gb", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Managed disk storage account type.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


class GcpServiceAccountArgsDict(TypedDict):
    """
    GCP service account assignment.
    """
    email: pulumi.Input[_builtins.str]
    """
    Service account email.
    """
    scopes: NotRequired[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]
    """
    OAuth scopes.
    """

@pulumi.input_type
class GcpServiceAccountArgs:
    def __init__(__self__, *,
                 email: pulumi.Input[_builtins.str],
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        GCP service account assignment.

        :param pulumi.Input[_builtins.str] email: Service account email.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] scopes: OAuth scopes.
        """
        pulumi.set(__self__, "email", email)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[_builtins.str]:
        """
        Service account email.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter
    def scopes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        OAuth scopes.
        """
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "scopes", value)


class HypervHardDriveArgsDict(TypedDict):
    """
    Hyper-V virtual hard disk attachment.
    """
    path: pulumi.Input[_builtins.str]
    """
    VHDX path.
    """
    controller_location: NotRequired[pulumi.Input[_builtins.int]]
    """
    Controller location.
    """
    controller_number: NotRequired[pulumi.Input[_builtins.int]]
    """
    Controller number.
    """
    controller_type: NotRequired[pulumi.Input[_builtins.str]]
    """
    Controller type.
    """

@pulumi.input_type
class HypervHardDriveArgs:
    def __init__(__self__, *,
                 path: pulumi.Input[_builtins.str],
                 controller_location: Optional[pulumi.Input[_builtins.int]] = None,
                 controller_number: Optional[pulumi.Input[_builtins.int]] = None,
                 controller_type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Hyper-V virtual hard disk attachment.

        :param pulumi.Input[_builtins.str] path: VHDX path.
        :param pulumi.Input[_builtins.int] controller_location: Controller location.
        :param pulumi.Input[_builtins.int] controller_number: Controller number.
        :param pulumi.Input[_builtins.str] controller_type: Controller type.
        """
        pulumi.set(__self__, "path", path)
        if controller_location is not None:
            pulumi.set(__self__, "controller_location", controller_location)
        if controller_number is not None:
            pulumi.set(__self__, "controller_number", controller_number)
        if controller_type is not None:
            pulumi.set(__self__, "controller_type", controller_type)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        """
        VHDX path.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="controllerLocation")
    def controller_location(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Controller location.
        """
        return pulumi.get(self, "controller_location")

    @controller_location.setter
    def controller_location(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "controller_location", value)

    @_builtins.property
    @pulumi.getter(name="controllerNumber")
    def controller_number(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Controller number.
        """
        return pulumi.get(self, "controller_number")

    @controller_number.setter
    def controller_number(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "controller_number", value)

    @_builtins.property
    @pulumi.getter(name="controllerType")
    def controller_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Controller type.
        """
        return pulumi.get(self, "controller_type")

    @controller_type.setter
    def controller_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "controller_type", value)


class MetadataOptionsArgsDict(TypedDict):
    """
    AWS EC2 instance metadata service options.
    """
    http_endpoint: NotRequired[pulumi.Input[_builtins.str]]
    """
    Whether the metadata service endpoint is enabled.
    """
    http_tokens: NotRequired[pulumi.Input[_builtins.str]]
    """
    Whether IMDSv2 tokens are required.
    """

@pulumi.input_type
class MetadataOptionsArgs:
    def __init__(__self__, *,
                 http_endpoint: Optional[pulumi.Input[_builtins.str]] = None,
                 http_tokens: Optional[pulumi.Input[_builtins.str]] = None):
        """
        AWS EC2 instance metadata service options.

        :param pulumi.Input[_builtins.str] http_endpoint: Whether the metadata service endpoint is enabled.
        :param pulumi.Input[_builtins.str] http_tokens: Whether IMDSv2 tokens are required.
        """
        if http_endpoint is not None:
            pulumi.set(__self__, "http_endpoint", http_endpoint)
        if http_tokens is not None:
            pulumi.set(__self__, "http_tokens", http_tokens)

    @_builtins.property
    @pulumi.getter(name="httpEndpoint")
    def http_endpoint(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether the metadata service endpoint is enabled.
        """
        return pulumi.get(self, "http_endpoint")

    @http_endpoint.setter
    def http_endpoint(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "http_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="httpTokens")
    def http_tokens(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Whether IMDSv2 tokens are required.
        """
        return pulumi.get(self, "http_tokens")

    @http_tokens.setter
    def http_tokens(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "http_tokens", value)


class PublisherRegistrationMapArgsDict(TypedDict):
    """
    Publisher registrations keyed by publisher name.
    """
    pass

@pulumi.input_type
class PublisherRegistrationMapArgs:
    def __init__(__self__):
        """
        Publisher registrations keyed by publisher name.
        """
        pass


