# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['AwsPublisherArgs', 'AwsPublisher']

@pulumi.input_type
class AwsPublisherArgs:
    def __init__(__self__, *,
                 security_group_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 subnet_id: pulumi.Input[_builtins.str],
                 ami_id: pulumi.Input[Optional[_builtins.str]] = None,
                 api_token: pulumi.Input[Optional[_builtins.str]] = None,
                 associate_public_ip_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 delete_default_user: pulumi.Input[Optional[_builtins.bool]] = None,
                 ebs_optimized: pulumi.Input[Optional[_builtins.bool]] = None,
                 guest_network_interface: pulumi.Input[Optional['GuestNetworkInterfaceArgs']] = None,
                 iam_instance_profile: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password_is_hash: pulumi.Input[Optional[_builtins.bool]] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 instance_type: pulumi.Input[Optional[_builtins.str]] = None,
                 key_name: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata_options: pulumi.Input[Optional['MetadataOptionsArgs']] = None,
                 monitoring: pulumi.Input[Optional[_builtins.bool]] = None,
                 name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 nonat: pulumi.Input[Optional[_builtins.bool]] = None,
                 registrations: pulumi.Input[Optional['PublisherRegistrationMapArgs']] = None,
                 replicas: pulumi.Input[Optional[_builtins.int]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tenant_url: pulumi.Input[Optional[_builtins.str]] = None,
                 wizard_path: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a AwsPublisher resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: AWS security group IDs attached to publisher instances.
        :param pulumi.Input[_builtins.str] subnet_id: AWS subnet ID for publisher network interfaces.
        :param pulumi.Input[_builtins.str] ami_id: Publisher AMI ID.
        :param pulumi.Input[_builtins.str] api_token: Netskope API token used for publisher registration.
        :param pulumi.Input[_builtins.bool] associate_public_ip_address: Whether to associate public IP addresses.
        :param pulumi.Input[_builtins.bool] bootstrap: Run Netskope's generic bootstrap script during cloud-init on a stock Ubuntu image. Defaults to false on AWS.
        :param pulumi.Input[_builtins.str] bootstrap_url: URL to the Netskope generic bootstrap script.
        :param pulumi.Input[_builtins.bool] delete_default_user: When true and installUser is not ubuntu, cloud-init removes the image default ubuntu account.
        :param pulumi.Input[_builtins.bool] ebs_optimized: Whether to enable EBS optimization.
        :param pulumi.Input['GuestNetworkInterfaceArgs'] guest_network_interface: Optional guest OS primary interface override applied with netplan during cloud-init.
        :param pulumi.Input[_builtins.str] iam_instance_profile: Optional IAM instance profile name.
        :param pulumi.Input[_builtins.str] install_user: Linux user that owns the Publisher install. Defaults to ubuntu.
        :param pulumi.Input[_builtins.str] install_user_password: Optional password for installUser. Plain text unless installUserPasswordIsHash is true.
        :param pulumi.Input[_builtins.bool] install_user_password_is_hash: Set true when installUserPassword is already a crypt(3) hash.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] install_user_ssh_authorized_keys: Public SSH keys installed in the install user's authorized_keys file.
        :param pulumi.Input[_builtins.str] instance_type: EC2 instance type.
        :param pulumi.Input[_builtins.str] key_name: Optional EC2 key pair name.
        :param pulumi.Input['MetadataOptionsArgs'] metadata_options: EC2 instance metadata service options.
        :param pulumi.Input[_builtins.bool] monitoring: Whether to enable detailed EC2 monitoring.
        :param pulumi.Input[_builtins.str] name_prefix: Prefix used to derive publisher names when explicit names are not supplied.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] names: Explicit publisher names to create.
        :param pulumi.Input[_builtins.bool] nonat: Whether cloud-init should create the Netskope No-NAT marker file. Defaults to false on AWS.
        :param pulumi.Input['PublisherRegistrationMapArgs'] registrations: Pre-created Netskope publisher registrations keyed by publisher name.
        :param pulumi.Input[_builtins.int] replicas: Number of publishers to create when names are not supplied.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags applied to supported provider resources.
        :param pulumi.Input[_builtins.str] tenant_url: Netskope tenant URL used for publisher registration.
        :param pulumi.Input[_builtins.str] wizard_path: Netskope publisher registration wizard API path.
        """
        pulumi.set(__self__, "security_group_ids", security_group_ids)
        pulumi.set(__self__, "subnet_id", subnet_id)
        if ami_id is not None:
            pulumi.set(__self__, "ami_id", ami_id)
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if associate_public_ip_address is not None:
            pulumi.set(__self__, "associate_public_ip_address", associate_public_ip_address)
        if bootstrap is not None:
            pulumi.set(__self__, "bootstrap", bootstrap)
        if bootstrap_url is not None:
            pulumi.set(__self__, "bootstrap_url", bootstrap_url)
        if delete_default_user is not None:
            pulumi.set(__self__, "delete_default_user", delete_default_user)
        if ebs_optimized is not None:
            pulumi.set(__self__, "ebs_optimized", ebs_optimized)
        if guest_network_interface is not None:
            pulumi.set(__self__, "guest_network_interface", guest_network_interface)
        if iam_instance_profile is not None:
            pulumi.set(__self__, "iam_instance_profile", iam_instance_profile)
        if install_user is not None:
            pulumi.set(__self__, "install_user", install_user)
        if install_user_password is not None:
            pulumi.set(__self__, "install_user_password", install_user_password)
        if install_user_password_is_hash is not None:
            pulumi.set(__self__, "install_user_password_is_hash", install_user_password_is_hash)
        if install_user_ssh_authorized_keys is not None:
            pulumi.set(__self__, "install_user_ssh_authorized_keys", install_user_ssh_authorized_keys)
        if instance_type is not None:
            pulumi.set(__self__, "instance_type", instance_type)
        if key_name is not None:
            pulumi.set(__self__, "key_name", key_name)
        if metadata_options is not None:
            pulumi.set(__self__, "metadata_options", metadata_options)
        if monitoring is not None:
            pulumi.set(__self__, "monitoring", monitoring)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if names is not None:
            pulumi.set(__self__, "names", names)
        if nonat is not None:
            pulumi.set(__self__, "nonat", nonat)
        if registrations is not None:
            pulumi.set(__self__, "registrations", registrations)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_url is not None:
            pulumi.set(__self__, "tenant_url", tenant_url)
        if wizard_path is not None:
            pulumi.set(__self__, "wizard_path", wizard_path)

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        AWS security group IDs attached to publisher instances.
        """
        return pulumi.get(self, "security_group_ids")

    @security_group_ids.setter
    def security_group_ids(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "security_group_ids", value)

    @_builtins.property
    @pulumi.getter(name="subnetId")
    def subnet_id(self) -> pulumi.Input[_builtins.str]:
        """
        AWS subnet ID for publisher network interfaces.
        """
        return pulumi.get(self, "subnet_id")

    @subnet_id.setter
    def subnet_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "subnet_id", value)

    @_builtins.property
    @pulumi.getter(name="amiId")
    def ami_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Publisher AMI ID.
        """
        return pulumi.get(self, "ami_id")

    @ami_id.setter
    def ami_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ami_id", value)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Netskope API token used for publisher registration.
        """
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter(name="associatePublicIpAddress")
    def associate_public_ip_address(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to associate public IP addresses.
        """
        return pulumi.get(self, "associate_public_ip_address")

    @associate_public_ip_address.setter
    def associate_public_ip_address(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "associate_public_ip_address", value)

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Run Netskope's generic bootstrap script during cloud-init on a stock Ubuntu image. Defaults to false on AWS.
        """
        return pulumi.get(self, "bootstrap")

    @bootstrap.setter
    def bootstrap(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "bootstrap", value)

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        URL to the Netskope generic bootstrap script.
        """
        return pulumi.get(self, "bootstrap_url")

    @bootstrap_url.setter
    def bootstrap_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "bootstrap_url", value)

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When true and installUser is not ubuntu, cloud-init removes the image default ubuntu account.
        """
        return pulumi.get(self, "delete_default_user")

    @delete_default_user.setter
    def delete_default_user(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "delete_default_user", value)

    @_builtins.property
    @pulumi.getter(name="ebsOptimized")
    def ebs_optimized(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to enable EBS optimization.
        """
        return pulumi.get(self, "ebs_optimized")

    @ebs_optimized.setter
    def ebs_optimized(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ebs_optimized", value)

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Input[Optional['GuestNetworkInterfaceArgs']]:
        """
        Optional guest OS primary interface override applied with netplan during cloud-init.
        """
        return pulumi.get(self, "guest_network_interface")

    @guest_network_interface.setter
    def guest_network_interface(self, value: pulumi.Input[Optional['GuestNetworkInterfaceArgs']]):
        pulumi.set(self, "guest_network_interface", value)

    @_builtins.property
    @pulumi.getter(name="iamInstanceProfile")
    def iam_instance_profile(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional IAM instance profile name.
        """
        return pulumi.get(self, "iam_instance_profile")

    @iam_instance_profile.setter
    def iam_instance_profile(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "iam_instance_profile", value)

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Linux user that owns the Publisher install. Defaults to ubuntu.
        """
        return pulumi.get(self, "install_user")

    @install_user.setter
    def install_user(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "install_user", value)

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional password for installUser. Plain text unless installUserPasswordIsHash is true.
        """
        return pulumi.get(self, "install_user_password")

    @install_user_password.setter
    def install_user_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "install_user_password", value)

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Set true when installUserPassword is already a crypt(3) hash.
        """
        return pulumi.get(self, "install_user_password_is_hash")

    @install_user_password_is_hash.setter
    def install_user_password_is_hash(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "install_user_password_is_hash", value)

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Public SSH keys installed in the install user's authorized_keys file.
        """
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @install_user_ssh_authorized_keys.setter
    def install_user_ssh_authorized_keys(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "install_user_ssh_authorized_keys", value)

    @_builtins.property
    @pulumi.getter(name="instanceType")
    def instance_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        EC2 instance type.
        """
        return pulumi.get(self, "instance_type")

    @instance_type.setter
    def instance_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "instance_type", value)

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional EC2 key pair name.
        """
        return pulumi.get(self, "key_name")

    @key_name.setter
    def key_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "key_name", value)

    @_builtins.property
    @pulumi.getter(name="metadataOptions")
    def metadata_options(self) -> pulumi.Input[Optional['MetadataOptionsArgs']]:
        """
        EC2 instance metadata service options.
        """
        return pulumi.get(self, "metadata_options")

    @metadata_options.setter
    def metadata_options(self, value: pulumi.Input[Optional['MetadataOptionsArgs']]):
        pulumi.set(self, "metadata_options", value)

    @_builtins.property
    @pulumi.getter
    def monitoring(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to enable detailed EC2 monitoring.
        """
        return pulumi.get(self, "monitoring")

    @monitoring.setter
    def monitoring(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "monitoring", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Prefix used to derive publisher names when explicit names are not supplied.
        """
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Explicit publisher names to create.
        """
        return pulumi.get(self, "names")

    @names.setter
    def names(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "names", value)

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether cloud-init should create the Netskope No-NAT marker file. Defaults to false on AWS.
        """
        return pulumi.get(self, "nonat")

    @nonat.setter
    def nonat(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "nonat", value)

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Input[Optional['PublisherRegistrationMapArgs']]:
        """
        Pre-created Netskope publisher registrations keyed by publisher name.
        """
        return pulumi.get(self, "registrations")

    @registrations.setter
    def registrations(self, value: pulumi.Input[Optional['PublisherRegistrationMapArgs']]):
        pulumi.set(self, "registrations", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Number of publishers to create when names are not supplied.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Tags applied to supported provider resources.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Netskope tenant URL used for publisher registration.
        """
        return pulumi.get(self, "tenant_url")

    @tenant_url.setter
    def tenant_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "tenant_url", value)

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Netskope publisher registration wizard API path.
        """
        return pulumi.get(self, "wizard_path")

    @wizard_path.setter
    def wizard_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "wizard_path", value)


@pulumi.type_token("netskope-publisher:index:AwsPublisher")
class AwsPublisher(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ami_id: pulumi.Input[Optional[_builtins.str]] = None,
                 api_token: pulumi.Input[Optional[_builtins.str]] = None,
                 associate_public_ip_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 delete_default_user: pulumi.Input[Optional[_builtins.bool]] = None,
                 ebs_optimized: pulumi.Input[Optional[_builtins.bool]] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['GuestNetworkInterfaceArgs', 'GuestNetworkInterfaceArgsDict']]] = None,
                 iam_instance_profile: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password_is_hash: pulumi.Input[Optional[_builtins.bool]] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 instance_type: pulumi.Input[Optional[_builtins.str]] = None,
                 key_name: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata_options: pulumi.Input[Optional[Union['MetadataOptionsArgs', 'MetadataOptionsArgsDict']]] = None,
                 monitoring: pulumi.Input[Optional[_builtins.bool]] = None,
                 name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 nonat: pulumi.Input[Optional[_builtins.bool]] = None,
                 registrations: pulumi.Input[Optional[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']]] = None,
                 replicas: pulumi.Input[Optional[_builtins.int]] = None,
                 security_group_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 subnet_id: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tenant_url: pulumi.Input[Optional[_builtins.str]] = None,
                 wizard_path: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Creates one or more Netskope Private Access Publisher EC2 instances and registers them with a Netskope tenant.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] ami_id: Publisher AMI ID.
        :param pulumi.Input[_builtins.str] api_token: Netskope API token used for publisher registration.
        :param pulumi.Input[_builtins.bool] associate_public_ip_address: Whether to associate public IP addresses.
        :param pulumi.Input[_builtins.bool] bootstrap: Run Netskope's generic bootstrap script during cloud-init on a stock Ubuntu image. Defaults to false on AWS.
        :param pulumi.Input[_builtins.str] bootstrap_url: URL to the Netskope generic bootstrap script.
        :param pulumi.Input[_builtins.bool] delete_default_user: When true and installUser is not ubuntu, cloud-init removes the image default ubuntu account.
        :param pulumi.Input[_builtins.bool] ebs_optimized: Whether to enable EBS optimization.
        :param pulumi.Input[Union['GuestNetworkInterfaceArgs', 'GuestNetworkInterfaceArgsDict']] guest_network_interface: Optional guest OS primary interface override applied with netplan during cloud-init.
        :param pulumi.Input[_builtins.str] iam_instance_profile: Optional IAM instance profile name.
        :param pulumi.Input[_builtins.str] install_user: Linux user that owns the Publisher install. Defaults to ubuntu.
        :param pulumi.Input[_builtins.str] install_user_password: Optional password for installUser. Plain text unless installUserPasswordIsHash is true.
        :param pulumi.Input[_builtins.bool] install_user_password_is_hash: Set true when installUserPassword is already a crypt(3) hash.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] install_user_ssh_authorized_keys: Public SSH keys installed in the install user's authorized_keys file.
        :param pulumi.Input[_builtins.str] instance_type: EC2 instance type.
        :param pulumi.Input[_builtins.str] key_name: Optional EC2 key pair name.
        :param pulumi.Input[Union['MetadataOptionsArgs', 'MetadataOptionsArgsDict']] metadata_options: EC2 instance metadata service options.
        :param pulumi.Input[_builtins.bool] monitoring: Whether to enable detailed EC2 monitoring.
        :param pulumi.Input[_builtins.str] name_prefix: Prefix used to derive publisher names when explicit names are not supplied.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] names: Explicit publisher names to create.
        :param pulumi.Input[_builtins.bool] nonat: Whether cloud-init should create the Netskope No-NAT marker file. Defaults to false on AWS.
        :param pulumi.Input[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']] registrations: Pre-created Netskope publisher registrations keyed by publisher name.
        :param pulumi.Input[_builtins.int] replicas: Number of publishers to create when names are not supplied.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] security_group_ids: AWS security group IDs attached to publisher instances.
        :param pulumi.Input[_builtins.str] subnet_id: AWS subnet ID for publisher network interfaces.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags applied to supported provider resources.
        :param pulumi.Input[_builtins.str] tenant_url: Netskope tenant URL used for publisher registration.
        :param pulumi.Input[_builtins.str] wizard_path: Netskope publisher registration wizard API path.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AwsPublisherArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates one or more Netskope Private Access Publisher EC2 instances and registers them with a Netskope tenant.


        :param str resource_name: The name of the resource.
        :param AwsPublisherArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AwsPublisherArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ami_id: pulumi.Input[Optional[_builtins.str]] = None,
                 api_token: pulumi.Input[Optional[_builtins.str]] = None,
                 associate_public_ip_address: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap: pulumi.Input[Optional[_builtins.bool]] = None,
                 bootstrap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 delete_default_user: pulumi.Input[Optional[_builtins.bool]] = None,
                 ebs_optimized: pulumi.Input[Optional[_builtins.bool]] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['GuestNetworkInterfaceArgs', 'GuestNetworkInterfaceArgsDict']]] = None,
                 iam_instance_profile: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password: pulumi.Input[Optional[_builtins.str]] = None,
                 install_user_password_is_hash: pulumi.Input[Optional[_builtins.bool]] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 instance_type: pulumi.Input[Optional[_builtins.str]] = None,
                 key_name: pulumi.Input[Optional[_builtins.str]] = None,
                 metadata_options: pulumi.Input[Optional[Union['MetadataOptionsArgs', 'MetadataOptionsArgsDict']]] = None,
                 monitoring: pulumi.Input[Optional[_builtins.bool]] = None,
                 name_prefix: pulumi.Input[Optional[_builtins.str]] = None,
                 names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 nonat: pulumi.Input[Optional[_builtins.bool]] = None,
                 registrations: pulumi.Input[Optional[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']]] = None,
                 replicas: pulumi.Input[Optional[_builtins.int]] = None,
                 security_group_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 subnet_id: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tenant_url: pulumi.Input[Optional[_builtins.str]] = None,
                 wizard_path: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AwsPublisherArgs.__new__(AwsPublisherArgs)

            __props__.__dict__["ami_id"] = ami_id
            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["associate_public_ip_address"] = associate_public_ip_address
            __props__.__dict__["bootstrap"] = bootstrap
            __props__.__dict__["bootstrap_url"] = bootstrap_url
            __props__.__dict__["delete_default_user"] = delete_default_user
            __props__.__dict__["ebs_optimized"] = ebs_optimized
            __props__.__dict__["guest_network_interface"] = guest_network_interface
            __props__.__dict__["iam_instance_profile"] = iam_instance_profile
            __props__.__dict__["install_user"] = install_user
            __props__.__dict__["install_user_password"] = None if install_user_password is None else pulumi.Output.secret(install_user_password)
            __props__.__dict__["install_user_password_is_hash"] = install_user_password_is_hash
            __props__.__dict__["install_user_ssh_authorized_keys"] = install_user_ssh_authorized_keys
            __props__.__dict__["instance_type"] = instance_type
            __props__.__dict__["key_name"] = key_name
            __props__.__dict__["metadata_options"] = metadata_options
            __props__.__dict__["monitoring"] = monitoring
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["names"] = names
            __props__.__dict__["nonat"] = nonat
            __props__.__dict__["registrations"] = registrations
            __props__.__dict__["replicas"] = replicas
            if security_group_ids is None and not opts.urn:
                raise TypeError("Missing required property 'security_group_ids'")
            __props__.__dict__["security_group_ids"] = security_group_ids
            if subnet_id is None and not opts.urn:
                raise TypeError("Missing required property 'subnet_id'")
            __props__.__dict__["subnet_id"] = subnet_id
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_url"] = tenant_url
            __props__.__dict__["wizard_path"] = wizard_path
            __props__.__dict__["publisher_names"] = None
            __props__.__dict__["publishers"] = None
        super(AwsPublisher, __self__).__init__(
            'netskope-publisher:index:AwsPublisher',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="publisherNames")
    def publisher_names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Created publisher names.
        """
        return pulumi.get(self, "publisher_names")

    @_builtins.property
    @pulumi.getter
    def publishers(self) -> pulumi.Output[Optional['outputs.PublisherOutputMap']]:
        """
        Publisher registration and VM details keyed by name.
        """
        return pulumi.get(self, "publishers")

