# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import provider as _provider

__all__ = ['AwsPublisherArgs', 'AwsPublisher']

@pulumi.input_type
class AwsPublisherArgs:
    def __init__(__self__, *,
                 security_group_ids: pulumi.Input[Sequence[_builtins.str]],
                 subnet_id: _builtins.str,
                 ami_id: Optional[_builtins.str] = None,
                 api_token: Optional[_builtins.str] = None,
                 associate_public_ip_address: Optional[_builtins.bool] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 ebs_optimized: Optional[_builtins.bool] = None,
                 guest_network_interface: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']] = None,
                 iam_instance_profile: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 instance_type: Optional[_builtins.str] = None,
                 key_name: Optional[_builtins.str] = None,
                 metadata_options: pulumi.Input[Optional['_provider.MetadataOptionsArgs']] = None,
                 monitoring: Optional[_builtins.bool] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None):
        """
        The set of arguments for constructing a AwsPublisher resource.
        """
        pulumi.set(__self__, "security_group_ids", security_group_ids)
        pulumi.set(__self__, "subnet_id", subnet_id)
        if ami_id is not None:
            pulumi.set(__self__, "ami_id", ami_id)
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if associate_public_ip_address is not None:
            pulumi.set(__self__, "associate_public_ip_address", associate_public_ip_address)
        if auth_mode is not None:
            pulumi.set(__self__, "auth_mode", auth_mode)
        if bearer_token is not None:
            pulumi.set(__self__, "bearer_token", bearer_token)
        if bootstrap is not None:
            pulumi.set(__self__, "bootstrap", bootstrap)
        if bootstrap_url is not None:
            pulumi.set(__self__, "bootstrap_url", bootstrap_url)
        if delete_default_user is not None:
            pulumi.set(__self__, "delete_default_user", delete_default_user)
        if ebs_optimized is not None:
            pulumi.set(__self__, "ebs_optimized", ebs_optimized)
        if guest_network_interface is not None:
            pulumi.set(__self__, "guest_network_interface", guest_network_interface)
        if iam_instance_profile is not None:
            pulumi.set(__self__, "iam_instance_profile", iam_instance_profile)
        if install_user is not None:
            pulumi.set(__self__, "install_user", install_user)
        if install_user_password is not None:
            pulumi.set(__self__, "install_user_password", install_user_password)
        if install_user_password_is_hash is not None:
            pulumi.set(__self__, "install_user_password_is_hash", install_user_password_is_hash)
        if install_user_ssh_authorized_keys is not None:
            pulumi.set(__self__, "install_user_ssh_authorized_keys", install_user_ssh_authorized_keys)
        if instance_type is not None:
            pulumi.set(__self__, "instance_type", instance_type)
        if key_name is not None:
            pulumi.set(__self__, "key_name", key_name)
        if metadata_options is not None:
            pulumi.set(__self__, "metadata_options", metadata_options)
        if monitoring is not None:
            pulumi.set(__self__, "monitoring", monitoring)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if names is not None:
            pulumi.set(__self__, "names", names)
        if nonat is not None:
            pulumi.set(__self__, "nonat", nonat)
        if oauth2 is not None:
            pulumi.set(__self__, "oauth2", oauth2)
        if registrations is not None:
            pulumi.set(__self__, "registrations", registrations)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_url is not None:
            pulumi.set(__self__, "tenant_url", tenant_url)
        if wizard_path is not None:
            pulumi.set(__self__, "wizard_path", wizard_path)

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(self) -> pulumi.Input[Sequence[_builtins.str]]:
        return pulumi.get(self, "security_group_ids")

    @security_group_ids.setter
    def security_group_ids(self, value: pulumi.Input[Sequence[_builtins.str]]):
        pulumi.set(self, "security_group_ids", value)

    @_builtins.property
    @pulumi.getter(name="subnetId")
    def subnet_id(self) -> _builtins.str:
        return pulumi.get(self, "subnet_id")

    @subnet_id.setter
    def subnet_id(self, value: _builtins.str):
        pulumi.set(self, "subnet_id", value)

    @_builtins.property
    @pulumi.getter(name="amiId")
    def ami_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ami_id")

    @ami_id.setter
    def ami_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "ami_id", value)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter(name="associatePublicIpAddress")
    def associate_public_ip_address(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "associate_public_ip_address")

    @associate_public_ip_address.setter
    def associate_public_ip_address(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "associate_public_ip_address", value)

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "auth_mode")

    @auth_mode.setter
    def auth_mode(self, value: Optional[_builtins.str]):
        pulumi.set(self, "auth_mode", value)

    @_builtins.property
    @pulumi.getter(name="bearerToken")
    def bearer_token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bearer_token")

    @bearer_token.setter
    def bearer_token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "bearer_token", value)

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "bootstrap")

    @bootstrap.setter
    def bootstrap(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "bootstrap", value)

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bootstrap_url")

    @bootstrap_url.setter
    def bootstrap_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "bootstrap_url", value)

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "delete_default_user")

    @delete_default_user.setter
    def delete_default_user(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "delete_default_user", value)

    @_builtins.property
    @pulumi.getter(name="ebsOptimized")
    def ebs_optimized(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "ebs_optimized")

    @ebs_optimized.setter
    def ebs_optimized(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "ebs_optimized", value)

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]:
        return pulumi.get(self, "guest_network_interface")

    @guest_network_interface.setter
    def guest_network_interface(self, value: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]):
        pulumi.set(self, "guest_network_interface", value)

    @_builtins.property
    @pulumi.getter(name="iamInstanceProfile")
    def iam_instance_profile(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "iam_instance_profile")

    @iam_instance_profile.setter
    def iam_instance_profile(self, value: Optional[_builtins.str]):
        pulumi.set(self, "iam_instance_profile", value)

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user")

    @install_user.setter
    def install_user(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user", value)

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user_password")

    @install_user_password.setter
    def install_user_password(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user_password", value)

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "install_user_password_is_hash")

    @install_user_password_is_hash.setter
    def install_user_password_is_hash(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "install_user_password_is_hash", value)

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @install_user_ssh_authorized_keys.setter
    def install_user_ssh_authorized_keys(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "install_user_ssh_authorized_keys", value)

    @_builtins.property
    @pulumi.getter(name="instanceType")
    def instance_type(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "instance_type")

    @instance_type.setter
    def instance_type(self, value: Optional[_builtins.str]):
        pulumi.set(self, "instance_type", value)

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "key_name")

    @key_name.setter
    def key_name(self, value: Optional[_builtins.str]):
        pulumi.set(self, "key_name", value)

    @_builtins.property
    @pulumi.getter(name="metadataOptions")
    def metadata_options(self) -> pulumi.Input[Optional['_provider.MetadataOptionsArgs']]:
        return pulumi.get(self, "metadata_options")

    @metadata_options.setter
    def metadata_options(self, value: pulumi.Input[Optional['_provider.MetadataOptionsArgs']]):
        pulumi.set(self, "metadata_options", value)

    @_builtins.property
    @pulumi.getter
    def monitoring(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "monitoring")

    @monitoring.setter
    def monitoring(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "monitoring", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[_builtins.str]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @names.setter
    def names(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "names", value)

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "nonat")

    @nonat.setter
    def nonat(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "nonat", value)

    @_builtins.property
    @pulumi.getter
    def oauth2(self) -> pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']]:
        return pulumi.get(self, "oauth2")

    @oauth2.setter
    def oauth2(self, value: pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']]):
        pulumi.set(self, "oauth2", value)

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]:
        return pulumi.get(self, "registrations")

    @registrations.setter
    def registrations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]):
        pulumi.set(self, "registrations", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[_builtins.int]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, _builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "tenant_url")

    @tenant_url.setter
    def tenant_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "tenant_url", value)

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "wizard_path")

    @wizard_path.setter
    def wizard_path(self, value: Optional[_builtins.str]):
        pulumi.set(self, "wizard_path", value)


@pulumi.type_token("netskope-publisher:index:AwsPublisher")
class AwsPublisher(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ami_id: Optional[_builtins.str] = None,
                 api_token: Optional[_builtins.str] = None,
                 associate_public_ip_address: Optional[_builtins.bool] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 ebs_optimized: Optional[_builtins.bool] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 iam_instance_profile: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 instance_type: Optional[_builtins.str] = None,
                 key_name: Optional[_builtins.str] = None,
                 metadata_options: pulumi.Input[Optional[Union['_provider.MetadataOptionsArgs', '_provider.MetadataOptionsArgsDict']]] = None,
                 monitoring: Optional[_builtins.bool] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional[Union['_provider.NetskopeOAuth2ArgsArgs', '_provider.NetskopeOAuth2ArgsArgsDict']]] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 security_group_ids: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 subnet_id: Optional[_builtins.str] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        """
        Create a AwsPublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AwsPublisherArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AwsPublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AwsPublisherArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AwsPublisherArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 ami_id: Optional[_builtins.str] = None,
                 api_token: Optional[_builtins.str] = None,
                 associate_public_ip_address: Optional[_builtins.bool] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 ebs_optimized: Optional[_builtins.bool] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 iam_instance_profile: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 instance_type: Optional[_builtins.str] = None,
                 key_name: Optional[_builtins.str] = None,
                 metadata_options: pulumi.Input[Optional[Union['_provider.MetadataOptionsArgs', '_provider.MetadataOptionsArgsDict']]] = None,
                 monitoring: Optional[_builtins.bool] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional[Union['_provider.NetskopeOAuth2ArgsArgs', '_provider.NetskopeOAuth2ArgsArgsDict']]] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 security_group_ids: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 subnet_id: Optional[_builtins.str] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AwsPublisherArgs.__new__(AwsPublisherArgs)

            __props__.__dict__["ami_id"] = ami_id
            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["associate_public_ip_address"] = associate_public_ip_address
            __props__.__dict__["auth_mode"] = auth_mode
            __props__.__dict__["bearer_token"] = None if bearer_token is None else pulumi.Output.secret(bearer_token)
            __props__.__dict__["bootstrap"] = bootstrap
            __props__.__dict__["bootstrap_url"] = bootstrap_url
            __props__.__dict__["delete_default_user"] = delete_default_user
            __props__.__dict__["ebs_optimized"] = ebs_optimized
            __props__.__dict__["guest_network_interface"] = guest_network_interface
            __props__.__dict__["iam_instance_profile"] = iam_instance_profile
            __props__.__dict__["install_user"] = install_user
            __props__.__dict__["install_user_password"] = None if install_user_password is None else pulumi.Output.secret(install_user_password)
            __props__.__dict__["install_user_password_is_hash"] = install_user_password_is_hash
            __props__.__dict__["install_user_ssh_authorized_keys"] = install_user_ssh_authorized_keys
            __props__.__dict__["instance_type"] = instance_type
            __props__.__dict__["key_name"] = key_name
            __props__.__dict__["metadata_options"] = metadata_options
            __props__.__dict__["monitoring"] = monitoring
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["names"] = names
            __props__.__dict__["nonat"] = nonat
            __props__.__dict__["oauth2"] = oauth2
            __props__.__dict__["registrations"] = registrations
            __props__.__dict__["replicas"] = replicas
            if security_group_ids is None and not opts.urn:
                raise TypeError("Missing required property 'security_group_ids'")
            __props__.__dict__["security_group_ids"] = security_group_ids
            if subnet_id is None and not opts.urn:
                raise TypeError("Missing required property 'subnet_id'")
            __props__.__dict__["subnet_id"] = subnet_id
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_url"] = tenant_url
            __props__.__dict__["wizard_path"] = wizard_path
            __props__.__dict__["publisher_names"] = None
            __props__.__dict__["publishers"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiToken", "bearerToken", "installUserPassword", "publishers"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(AwsPublisher, __self__).__init__(
            'netskope-publisher:index:AwsPublisher',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="amiId")
    def ami_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ami_id")

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_token")

    @_builtins.property
    @pulumi.getter(name="associatePublicIpAddress")
    def associate_public_ip_address(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "associate_public_ip_address")

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "auth_mode")

    @_builtins.property
    @pulumi.getter(name="bearerToken")
    def bearer_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bearer_token")

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "bootstrap")

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bootstrap_url")

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "delete_default_user")

    @_builtins.property
    @pulumi.getter(name="ebsOptimized")
    def ebs_optimized(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "ebs_optimized")

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Output[Optional['_provider.outputs.GuestNetworkInterface']]:
        return pulumi.get(self, "guest_network_interface")

    @_builtins.property
    @pulumi.getter(name="iamInstanceProfile")
    def iam_instance_profile(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "iam_instance_profile")

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user")

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user_password")

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "install_user_password_is_hash")

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @_builtins.property
    @pulumi.getter(name="instanceType")
    def instance_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "instance_type")

    @_builtins.property
    @pulumi.getter(name="keyName")
    def key_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "key_name")

    @_builtins.property
    @pulumi.getter(name="metadataOptions")
    def metadata_options(self) -> pulumi.Output[Optional['_provider.outputs.MetadataOptions']]:
        return pulumi.get(self, "metadata_options")

    @_builtins.property
    @pulumi.getter
    def monitoring(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "monitoring")

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "name_prefix")

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "nonat")

    @_builtins.property
    @pulumi.getter
    def oauth2(self) -> pulumi.Output[Optional['_provider.outputs.NetskopeOAuth2Args']]:
        return pulumi.get(self, "oauth2")

    @_builtins.property
    @pulumi.getter(name="publisherNames")
    def publisher_names(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "publisher_names")

    @_builtins.property
    @pulumi.getter
    def publishers(self) -> pulumi.Output[Mapping[str, Any]]:
        return pulumi.get(self, "publishers")

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Output[Optional[Mapping[str, '_provider.outputs.PublisherRegistrationInput']]]:
        return pulumi.get(self, "registrations")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter(name="securityGroupIds")
    def security_group_ids(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "security_group_ids")

    @_builtins.property
    @pulumi.getter(name="subnetId")
    def subnet_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "subnet_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tenant_url")

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "wizard_path")

