# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import provider as _provider

__all__ = ['HcloudPublisherArgs', 'HcloudPublisher']

@pulumi.input_type
class HcloudPublisherArgs:
    def __init__(__self__, *,
                 api_token: Optional[_builtins.str] = None,
                 assign_public_ip: Optional[_builtins.bool] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 datacenter: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 firewall_ids: pulumi.Input[Optional[Sequence[_builtins.int]]] = None,
                 guest_network_interface: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']] = None,
                 image: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 location: Optional[_builtins.str] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_id: Optional[_builtins.int] = None,
                 nonat: Optional[_builtins.bool] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 server_type: Optional[_builtins.str] = None,
                 ssh_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None):
        """
        The set of arguments for constructing a HcloudPublisher resource.
        """
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if assign_public_ip is not None:
            pulumi.set(__self__, "assign_public_ip", assign_public_ip)
        if bootstrap is not None:
            pulumi.set(__self__, "bootstrap", bootstrap)
        if bootstrap_url is not None:
            pulumi.set(__self__, "bootstrap_url", bootstrap_url)
        if datacenter is not None:
            pulumi.set(__self__, "datacenter", datacenter)
        if delete_default_user is not None:
            pulumi.set(__self__, "delete_default_user", delete_default_user)
        if firewall_ids is not None:
            pulumi.set(__self__, "firewall_ids", firewall_ids)
        if guest_network_interface is not None:
            pulumi.set(__self__, "guest_network_interface", guest_network_interface)
        if image is not None:
            pulumi.set(__self__, "image", image)
        if install_user is not None:
            pulumi.set(__self__, "install_user", install_user)
        if install_user_password is not None:
            pulumi.set(__self__, "install_user_password", install_user_password)
        if install_user_password_is_hash is not None:
            pulumi.set(__self__, "install_user_password_is_hash", install_user_password_is_hash)
        if install_user_ssh_authorized_keys is not None:
            pulumi.set(__self__, "install_user_ssh_authorized_keys", install_user_ssh_authorized_keys)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if names is not None:
            pulumi.set(__self__, "names", names)
        if network_id is not None:
            pulumi.set(__self__, "network_id", network_id)
        if nonat is not None:
            pulumi.set(__self__, "nonat", nonat)
        if registrations is not None:
            pulumi.set(__self__, "registrations", registrations)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if server_type is not None:
            pulumi.set(__self__, "server_type", server_type)
        if ssh_keys is not None:
            pulumi.set(__self__, "ssh_keys", ssh_keys)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_url is not None:
            pulumi.set(__self__, "tenant_url", tenant_url)
        if wizard_path is not None:
            pulumi.set(__self__, "wizard_path", wizard_path)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter(name="assignPublicIp")
    def assign_public_ip(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "assign_public_ip")

    @assign_public_ip.setter
    def assign_public_ip(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "assign_public_ip", value)

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "bootstrap")

    @bootstrap.setter
    def bootstrap(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "bootstrap", value)

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bootstrap_url")

    @bootstrap_url.setter
    def bootstrap_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "bootstrap_url", value)

    @_builtins.property
    @pulumi.getter
    def datacenter(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "datacenter")

    @datacenter.setter
    def datacenter(self, value: Optional[_builtins.str]):
        pulumi.set(self, "datacenter", value)

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "delete_default_user")

    @delete_default_user.setter
    def delete_default_user(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "delete_default_user", value)

    @_builtins.property
    @pulumi.getter(name="firewallIds")
    def firewall_ids(self) -> pulumi.Input[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "firewall_ids")

    @firewall_ids.setter
    def firewall_ids(self, value: pulumi.Input[Optional[Sequence[_builtins.int]]]):
        pulumi.set(self, "firewall_ids", value)

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]:
        return pulumi.get(self, "guest_network_interface")

    @guest_network_interface.setter
    def guest_network_interface(self, value: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]):
        pulumi.set(self, "guest_network_interface", value)

    @_builtins.property
    @pulumi.getter
    def image(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: Optional[_builtins.str]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user")

    @install_user.setter
    def install_user(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user", value)

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user_password")

    @install_user_password.setter
    def install_user_password(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user_password", value)

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "install_user_password_is_hash")

    @install_user_password_is_hash.setter
    def install_user_password_is_hash(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "install_user_password_is_hash", value)

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @install_user_ssh_authorized_keys.setter
    def install_user_ssh_authorized_keys(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "install_user_ssh_authorized_keys", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: Optional[_builtins.str]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[_builtins.str]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @names.setter
    def names(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "names", value)

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "network_id")

    @network_id.setter
    def network_id(self, value: Optional[_builtins.int]):
        pulumi.set(self, "network_id", value)

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "nonat")

    @nonat.setter
    def nonat(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "nonat", value)

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]:
        return pulumi.get(self, "registrations")

    @registrations.setter
    def registrations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]):
        pulumi.set(self, "registrations", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[_builtins.int]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter(name="serverType")
    def server_type(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "server_type")

    @server_type.setter
    def server_type(self, value: Optional[_builtins.str]):
        pulumi.set(self, "server_type", value)

    @_builtins.property
    @pulumi.getter(name="sshKeys")
    def ssh_keys(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "ssh_keys")

    @ssh_keys.setter
    def ssh_keys(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "ssh_keys", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, _builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "tenant_url")

    @tenant_url.setter
    def tenant_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "tenant_url", value)

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "wizard_path")

    @wizard_path.setter
    def wizard_path(self, value: Optional[_builtins.str]):
        pulumi.set(self, "wizard_path", value)


@pulumi.type_token("netskope-publisher:index:HcloudPublisher")
class HcloudPublisher(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[_builtins.str] = None,
                 assign_public_ip: Optional[_builtins.bool] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 datacenter: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 firewall_ids: pulumi.Input[Optional[Sequence[_builtins.int]]] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 image: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 location: Optional[_builtins.str] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_id: Optional[_builtins.int] = None,
                 nonat: Optional[_builtins.bool] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 server_type: Optional[_builtins.str] = None,
                 ssh_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        """
        Create a HcloudPublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[HcloudPublisherArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a HcloudPublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param HcloudPublisherArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(HcloudPublisherArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[_builtins.str] = None,
                 assign_public_ip: Optional[_builtins.bool] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 datacenter: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 firewall_ids: pulumi.Input[Optional[Sequence[_builtins.int]]] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 image: Optional[_builtins.str] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 location: Optional[_builtins.str] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_id: Optional[_builtins.int] = None,
                 nonat: Optional[_builtins.bool] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 server_type: Optional[_builtins.str] = None,
                 ssh_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = HcloudPublisherArgs.__new__(HcloudPublisherArgs)

            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["assign_public_ip"] = assign_public_ip
            __props__.__dict__["bootstrap"] = bootstrap
            __props__.__dict__["bootstrap_url"] = bootstrap_url
            __props__.__dict__["datacenter"] = datacenter
            __props__.__dict__["delete_default_user"] = delete_default_user
            __props__.__dict__["firewall_ids"] = firewall_ids
            __props__.__dict__["guest_network_interface"] = guest_network_interface
            __props__.__dict__["image"] = image
            __props__.__dict__["install_user"] = install_user
            __props__.__dict__["install_user_password"] = None if install_user_password is None else pulumi.Output.secret(install_user_password)
            __props__.__dict__["install_user_password_is_hash"] = install_user_password_is_hash
            __props__.__dict__["install_user_ssh_authorized_keys"] = install_user_ssh_authorized_keys
            __props__.__dict__["location"] = location
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["names"] = names
            __props__.__dict__["network_id"] = network_id
            __props__.__dict__["nonat"] = nonat
            __props__.__dict__["registrations"] = registrations
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["server_type"] = server_type
            __props__.__dict__["ssh_keys"] = ssh_keys
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tenant_url"] = tenant_url
            __props__.__dict__["wizard_path"] = wizard_path
            __props__.__dict__["publisher_names"] = None
            __props__.__dict__["publishers"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiToken", "installUserPassword", "publishers"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(HcloudPublisher, __self__).__init__(
            'netskope-publisher:index:HcloudPublisher',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_token")

    @_builtins.property
    @pulumi.getter(name="assignPublicIp")
    def assign_public_ip(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "assign_public_ip")

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "bootstrap")

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bootstrap_url")

    @_builtins.property
    @pulumi.getter
    def datacenter(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "datacenter")

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "delete_default_user")

    @_builtins.property
    @pulumi.getter(name="firewallIds")
    def firewall_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.int]]]:
        return pulumi.get(self, "firewall_ids")

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Output[Optional['_provider.outputs.GuestNetworkInterface']]:
        return pulumi.get(self, "guest_network_interface")

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "image")

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user")

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user_password")

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "install_user_password_is_hash")

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "name_prefix")

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @_builtins.property
    @pulumi.getter(name="networkId")
    def network_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "network_id")

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "nonat")

    @_builtins.property
    @pulumi.getter(name="publisherNames")
    def publisher_names(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "publisher_names")

    @_builtins.property
    @pulumi.getter
    def publishers(self) -> pulumi.Output[Mapping[str, Any]]:
        return pulumi.get(self, "publishers")

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Output[Optional[Mapping[str, '_provider.outputs.PublisherRegistrationInput']]]:
        return pulumi.get(self, "registrations")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter(name="serverType")
    def server_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "server_type")

    @_builtins.property
    @pulumi.getter(name="sshKeys")
    def ssh_keys(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "ssh_keys")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tenant_url")

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "wizard_path")

