# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'KubernetesPublisherOutputMap',
    'PublisherOutputMap',
    'PublisherRegistrationMap',
]

@pulumi.output_type
class KubernetesPublisherOutputMap(dict):
    """
    Kubernetes publisher outputs keyed by publisher name in token mode or release name in api mode.
    """
    def __init__(__self__):
        """
        Kubernetes publisher outputs keyed by publisher name in token mode or release name in api mode.
        """
        pass


@pulumi.output_type
class PublisherOutputMap(dict):
    """
    Publisher outputs keyed by publisher name.
    """
    def __init__(__self__):
        """
        Publisher outputs keyed by publisher name.
        """
        pass


@pulumi.output_type
class PublisherRegistrationMap(dict):
    """
    Publisher registrations keyed by publisher name.
    """
    def __init__(__self__):
        """
        Publisher registrations keyed by publisher name.
        """
        pass


