# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import provider as _provider

__all__ = ['ProxmoxvePublisherArgs', 'ProxmoxvePublisher']

@pulumi.input_type
class ProxmoxvePublisherArgs:
    def __init__(__self__, *,
                 datastore_id: _builtins.str,
                 node_name: _builtins.str,
                 template_vm_id: _builtins.int,
                 api_token: Optional[_builtins.str] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 clone_node_name: Optional[_builtins.str] = None,
                 cpu_cores: Optional[_builtins.int] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 disk_size: Optional[_builtins.int] = None,
                 full_clone: Optional[_builtins.bool] = None,
                 gateway: Optional[_builtins.str] = None,
                 guest_network_interface: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 ip_address: Optional[_builtins.str] = None,
                 memory: Optional[_builtins.int] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nameservers: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_bridge: Optional[_builtins.str] = None,
                 network_model: Optional[_builtins.str] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']] = None,
                 on_boot: Optional[_builtins.bool] = None,
                 pool_id: Optional[_builtins.str] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 started: Optional[_builtins.bool] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 vlan_id: Optional[_builtins.int] = None,
                 vm_id: Optional[_builtins.int] = None,
                 wizard_path: Optional[_builtins.str] = None):
        """
        The set of arguments for constructing a ProxmoxvePublisher resource.
        """
        pulumi.set(__self__, "datastore_id", datastore_id)
        pulumi.set(__self__, "node_name", node_name)
        pulumi.set(__self__, "template_vm_id", template_vm_id)
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if auth_mode is not None:
            pulumi.set(__self__, "auth_mode", auth_mode)
        if bearer_token is not None:
            pulumi.set(__self__, "bearer_token", bearer_token)
        if bootstrap is not None:
            pulumi.set(__self__, "bootstrap", bootstrap)
        if bootstrap_url is not None:
            pulumi.set(__self__, "bootstrap_url", bootstrap_url)
        if clone_node_name is not None:
            pulumi.set(__self__, "clone_node_name", clone_node_name)
        if cpu_cores is not None:
            pulumi.set(__self__, "cpu_cores", cpu_cores)
        if delete_default_user is not None:
            pulumi.set(__self__, "delete_default_user", delete_default_user)
        if disk_size is not None:
            pulumi.set(__self__, "disk_size", disk_size)
        if full_clone is not None:
            pulumi.set(__self__, "full_clone", full_clone)
        if gateway is not None:
            pulumi.set(__self__, "gateway", gateway)
        if guest_network_interface is not None:
            pulumi.set(__self__, "guest_network_interface", guest_network_interface)
        if install_user is not None:
            pulumi.set(__self__, "install_user", install_user)
        if install_user_password is not None:
            pulumi.set(__self__, "install_user_password", install_user_password)
        if install_user_password_is_hash is not None:
            pulumi.set(__self__, "install_user_password_is_hash", install_user_password_is_hash)
        if install_user_ssh_authorized_keys is not None:
            pulumi.set(__self__, "install_user_ssh_authorized_keys", install_user_ssh_authorized_keys)
        if ip_address is not None:
            pulumi.set(__self__, "ip_address", ip_address)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if names is not None:
            pulumi.set(__self__, "names", names)
        if nameservers is not None:
            pulumi.set(__self__, "nameservers", nameservers)
        if network_bridge is not None:
            pulumi.set(__self__, "network_bridge", network_bridge)
        if network_model is not None:
            pulumi.set(__self__, "network_model", network_model)
        if nonat is not None:
            pulumi.set(__self__, "nonat", nonat)
        if oauth2 is not None:
            pulumi.set(__self__, "oauth2", oauth2)
        if on_boot is not None:
            pulumi.set(__self__, "on_boot", on_boot)
        if pool_id is not None:
            pulumi.set(__self__, "pool_id", pool_id)
        if registrations is not None:
            pulumi.set(__self__, "registrations", registrations)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if started is not None:
            pulumi.set(__self__, "started", started)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_url is not None:
            pulumi.set(__self__, "tenant_url", tenant_url)
        if vlan_id is not None:
            pulumi.set(__self__, "vlan_id", vlan_id)
        if vm_id is not None:
            pulumi.set(__self__, "vm_id", vm_id)
        if wizard_path is not None:
            pulumi.set(__self__, "wizard_path", wizard_path)

    @_builtins.property
    @pulumi.getter(name="datastoreId")
    def datastore_id(self) -> _builtins.str:
        return pulumi.get(self, "datastore_id")

    @datastore_id.setter
    def datastore_id(self, value: _builtins.str):
        pulumi.set(self, "datastore_id", value)

    @_builtins.property
    @pulumi.getter(name="nodeName")
    def node_name(self) -> _builtins.str:
        return pulumi.get(self, "node_name")

    @node_name.setter
    def node_name(self, value: _builtins.str):
        pulumi.set(self, "node_name", value)

    @_builtins.property
    @pulumi.getter(name="templateVmId")
    def template_vm_id(self) -> _builtins.int:
        return pulumi.get(self, "template_vm_id")

    @template_vm_id.setter
    def template_vm_id(self, value: _builtins.int):
        pulumi.set(self, "template_vm_id", value)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "auth_mode")

    @auth_mode.setter
    def auth_mode(self, value: Optional[_builtins.str]):
        pulumi.set(self, "auth_mode", value)

    @_builtins.property
    @pulumi.getter(name="bearerToken")
    def bearer_token(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bearer_token")

    @bearer_token.setter
    def bearer_token(self, value: Optional[_builtins.str]):
        pulumi.set(self, "bearer_token", value)

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "bootstrap")

    @bootstrap.setter
    def bootstrap(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "bootstrap", value)

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "bootstrap_url")

    @bootstrap_url.setter
    def bootstrap_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "bootstrap_url", value)

    @_builtins.property
    @pulumi.getter(name="cloneNodeName")
    def clone_node_name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "clone_node_name")

    @clone_node_name.setter
    def clone_node_name(self, value: Optional[_builtins.str]):
        pulumi.set(self, "clone_node_name", value)

    @_builtins.property
    @pulumi.getter(name="cpuCores")
    def cpu_cores(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "cpu_cores")

    @cpu_cores.setter
    def cpu_cores(self, value: Optional[_builtins.int]):
        pulumi.set(self, "cpu_cores", value)

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "delete_default_user")

    @delete_default_user.setter
    def delete_default_user(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "delete_default_user", value)

    @_builtins.property
    @pulumi.getter(name="diskSize")
    def disk_size(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "disk_size")

    @disk_size.setter
    def disk_size(self, value: Optional[_builtins.int]):
        pulumi.set(self, "disk_size", value)

    @_builtins.property
    @pulumi.getter(name="fullClone")
    def full_clone(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "full_clone")

    @full_clone.setter
    def full_clone(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "full_clone", value)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "gateway")

    @gateway.setter
    def gateway(self, value: Optional[_builtins.str]):
        pulumi.set(self, "gateway", value)

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]:
        return pulumi.get(self, "guest_network_interface")

    @guest_network_interface.setter
    def guest_network_interface(self, value: pulumi.Input[Optional['_provider.GuestNetworkInterfaceArgs']]):
        pulumi.set(self, "guest_network_interface", value)

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user")

    @install_user.setter
    def install_user(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user", value)

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "install_user_password")

    @install_user_password.setter
    def install_user_password(self, value: Optional[_builtins.str]):
        pulumi.set(self, "install_user_password", value)

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "install_user_password_is_hash")

    @install_user_password_is_hash.setter
    def install_user_password_is_hash(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "install_user_password_is_hash", value)

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @install_user_ssh_authorized_keys.setter
    def install_user_ssh_authorized_keys(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "install_user_ssh_authorized_keys", value)

    @_builtins.property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "ip_address")

    @ip_address.setter
    def ip_address(self, value: Optional[_builtins.str]):
        pulumi.set(self, "ip_address", value)

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "memory")

    @memory.setter
    def memory(self, value: Optional[_builtins.int]):
        pulumi.set(self, "memory", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[_builtins.str]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @names.setter
    def names(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "names", value)

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> pulumi.Input[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "nameservers")

    @nameservers.setter
    def nameservers(self, value: pulumi.Input[Optional[Sequence[_builtins.str]]]):
        pulumi.set(self, "nameservers", value)

    @_builtins.property
    @pulumi.getter(name="networkBridge")
    def network_bridge(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "network_bridge")

    @network_bridge.setter
    def network_bridge(self, value: Optional[_builtins.str]):
        pulumi.set(self, "network_bridge", value)

    @_builtins.property
    @pulumi.getter(name="networkModel")
    def network_model(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "network_model")

    @network_model.setter
    def network_model(self, value: Optional[_builtins.str]):
        pulumi.set(self, "network_model", value)

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "nonat")

    @nonat.setter
    def nonat(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "nonat", value)

    @_builtins.property
    @pulumi.getter
    def oauth2(self) -> pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']]:
        return pulumi.get(self, "oauth2")

    @oauth2.setter
    def oauth2(self, value: pulumi.Input[Optional['_provider.NetskopeOAuth2ArgsArgs']]):
        pulumi.set(self, "oauth2", value)

    @_builtins.property
    @pulumi.getter(name="onBoot")
    def on_boot(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "on_boot")

    @on_boot.setter
    def on_boot(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "on_boot", value)

    @_builtins.property
    @pulumi.getter(name="poolId")
    def pool_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "pool_id")

    @pool_id.setter
    def pool_id(self, value: Optional[_builtins.str]):
        pulumi.set(self, "pool_id", value)

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]:
        return pulumi.get(self, "registrations")

    @registrations.setter
    def registrations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input['_provider.PublisherRegistrationInputArgs']]]]):
        pulumi.set(self, "registrations", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[_builtins.int]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter
    def started(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "started")

    @started.setter
    def started(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "started", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Mapping[str, _builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "tenant_url")

    @tenant_url.setter
    def tenant_url(self, value: Optional[_builtins.str]):
        pulumi.set(self, "tenant_url", value)

    @_builtins.property
    @pulumi.getter(name="vlanId")
    def vlan_id(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "vlan_id")

    @vlan_id.setter
    def vlan_id(self, value: Optional[_builtins.int]):
        pulumi.set(self, "vlan_id", value)

    @_builtins.property
    @pulumi.getter(name="vmId")
    def vm_id(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "vm_id")

    @vm_id.setter
    def vm_id(self, value: Optional[_builtins.int]):
        pulumi.set(self, "vm_id", value)

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "wizard_path")

    @wizard_path.setter
    def wizard_path(self, value: Optional[_builtins.str]):
        pulumi.set(self, "wizard_path", value)


@pulumi.type_token("netskope-publisher:index:ProxmoxvePublisher")
class ProxmoxvePublisher(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[_builtins.str] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 clone_node_name: Optional[_builtins.str] = None,
                 cpu_cores: Optional[_builtins.int] = None,
                 datastore_id: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 disk_size: Optional[_builtins.int] = None,
                 full_clone: Optional[_builtins.bool] = None,
                 gateway: Optional[_builtins.str] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 ip_address: Optional[_builtins.str] = None,
                 memory: Optional[_builtins.int] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nameservers: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_bridge: Optional[_builtins.str] = None,
                 network_model: Optional[_builtins.str] = None,
                 node_name: Optional[_builtins.str] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional[Union['_provider.NetskopeOAuth2ArgsArgs', '_provider.NetskopeOAuth2ArgsArgsDict']]] = None,
                 on_boot: Optional[_builtins.bool] = None,
                 pool_id: Optional[_builtins.str] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 started: Optional[_builtins.bool] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 template_vm_id: Optional[_builtins.int] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 vlan_id: Optional[_builtins.int] = None,
                 vm_id: Optional[_builtins.int] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        """
        Create a ProxmoxvePublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProxmoxvePublisherArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ProxmoxvePublisher resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProxmoxvePublisherArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProxmoxvePublisherArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[_builtins.str] = None,
                 auth_mode: Optional[_builtins.str] = None,
                 bearer_token: Optional[_builtins.str] = None,
                 bootstrap: Optional[_builtins.bool] = None,
                 bootstrap_url: Optional[_builtins.str] = None,
                 clone_node_name: Optional[_builtins.str] = None,
                 cpu_cores: Optional[_builtins.int] = None,
                 datastore_id: Optional[_builtins.str] = None,
                 delete_default_user: Optional[_builtins.bool] = None,
                 disk_size: Optional[_builtins.int] = None,
                 full_clone: Optional[_builtins.bool] = None,
                 gateway: Optional[_builtins.str] = None,
                 guest_network_interface: pulumi.Input[Optional[Union['_provider.GuestNetworkInterfaceArgs', '_provider.GuestNetworkInterfaceArgsDict']]] = None,
                 install_user: Optional[_builtins.str] = None,
                 install_user_password: Optional[_builtins.str] = None,
                 install_user_password_is_hash: Optional[_builtins.bool] = None,
                 install_user_ssh_authorized_keys: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 ip_address: Optional[_builtins.str] = None,
                 memory: Optional[_builtins.int] = None,
                 name_prefix: Optional[_builtins.str] = None,
                 names: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 nameservers: pulumi.Input[Optional[Sequence[_builtins.str]]] = None,
                 network_bridge: Optional[_builtins.str] = None,
                 network_model: Optional[_builtins.str] = None,
                 node_name: Optional[_builtins.str] = None,
                 nonat: Optional[_builtins.bool] = None,
                 oauth2: pulumi.Input[Optional[Union['_provider.NetskopeOAuth2ArgsArgs', '_provider.NetskopeOAuth2ArgsArgsDict']]] = None,
                 on_boot: Optional[_builtins.bool] = None,
                 pool_id: Optional[_builtins.str] = None,
                 registrations: pulumi.Input[Optional[Mapping[str, pulumi.Input[Union['_provider.PublisherRegistrationInputArgs', '_provider.PublisherRegistrationInputArgsDict']]]]] = None,
                 replicas: Optional[_builtins.int] = None,
                 started: Optional[_builtins.bool] = None,
                 tags: pulumi.Input[Optional[Mapping[str, _builtins.str]]] = None,
                 template_vm_id: Optional[_builtins.int] = None,
                 tenant_url: Optional[_builtins.str] = None,
                 vlan_id: Optional[_builtins.int] = None,
                 vm_id: Optional[_builtins.int] = None,
                 wizard_path: Optional[_builtins.str] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProxmoxvePublisherArgs.__new__(ProxmoxvePublisherArgs)

            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["auth_mode"] = auth_mode
            __props__.__dict__["bearer_token"] = None if bearer_token is None else pulumi.Output.secret(bearer_token)
            __props__.__dict__["bootstrap"] = bootstrap
            __props__.__dict__["bootstrap_url"] = bootstrap_url
            __props__.__dict__["clone_node_name"] = clone_node_name
            __props__.__dict__["cpu_cores"] = cpu_cores
            if datastore_id is None and not opts.urn:
                raise TypeError("Missing required property 'datastore_id'")
            __props__.__dict__["datastore_id"] = datastore_id
            __props__.__dict__["delete_default_user"] = delete_default_user
            __props__.__dict__["disk_size"] = disk_size
            __props__.__dict__["full_clone"] = full_clone
            __props__.__dict__["gateway"] = gateway
            __props__.__dict__["guest_network_interface"] = guest_network_interface
            __props__.__dict__["install_user"] = install_user
            __props__.__dict__["install_user_password"] = None if install_user_password is None else pulumi.Output.secret(install_user_password)
            __props__.__dict__["install_user_password_is_hash"] = install_user_password_is_hash
            __props__.__dict__["install_user_ssh_authorized_keys"] = install_user_ssh_authorized_keys
            __props__.__dict__["ip_address"] = ip_address
            __props__.__dict__["memory"] = memory
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["names"] = names
            __props__.__dict__["nameservers"] = nameservers
            __props__.__dict__["network_bridge"] = network_bridge
            __props__.__dict__["network_model"] = network_model
            if node_name is None and not opts.urn:
                raise TypeError("Missing required property 'node_name'")
            __props__.__dict__["node_name"] = node_name
            __props__.__dict__["nonat"] = nonat
            __props__.__dict__["oauth2"] = oauth2
            __props__.__dict__["on_boot"] = on_boot
            __props__.__dict__["pool_id"] = pool_id
            __props__.__dict__["registrations"] = registrations
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["started"] = started
            __props__.__dict__["tags"] = tags
            if template_vm_id is None and not opts.urn:
                raise TypeError("Missing required property 'template_vm_id'")
            __props__.__dict__["template_vm_id"] = template_vm_id
            __props__.__dict__["tenant_url"] = tenant_url
            __props__.__dict__["vlan_id"] = vlan_id
            __props__.__dict__["vm_id"] = vm_id
            __props__.__dict__["wizard_path"] = wizard_path
            __props__.__dict__["publisher_names"] = None
            __props__.__dict__["publishers"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiToken", "bearerToken", "installUserPassword", "publishers"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ProxmoxvePublisher, __self__).__init__(
            'netskope-publisher:index:ProxmoxvePublisher',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "api_token")

    @_builtins.property
    @pulumi.getter(name="authMode")
    def auth_mode(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "auth_mode")

    @_builtins.property
    @pulumi.getter(name="bearerToken")
    def bearer_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bearer_token")

    @_builtins.property
    @pulumi.getter
    def bootstrap(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "bootstrap")

    @_builtins.property
    @pulumi.getter(name="bootstrapUrl")
    def bootstrap_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "bootstrap_url")

    @_builtins.property
    @pulumi.getter(name="cloneNodeName")
    def clone_node_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "clone_node_name")

    @_builtins.property
    @pulumi.getter(name="cpuCores")
    def cpu_cores(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "cpu_cores")

    @_builtins.property
    @pulumi.getter(name="datastoreId")
    def datastore_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "datastore_id")

    @_builtins.property
    @pulumi.getter(name="deleteDefaultUser")
    def delete_default_user(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "delete_default_user")

    @_builtins.property
    @pulumi.getter(name="diskSize")
    def disk_size(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "disk_size")

    @_builtins.property
    @pulumi.getter(name="fullClone")
    def full_clone(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "full_clone")

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "gateway")

    @_builtins.property
    @pulumi.getter(name="guestNetworkInterface")
    def guest_network_interface(self) -> pulumi.Output[Optional['_provider.outputs.GuestNetworkInterface']]:
        return pulumi.get(self, "guest_network_interface")

    @_builtins.property
    @pulumi.getter(name="installUser")
    def install_user(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user")

    @_builtins.property
    @pulumi.getter(name="installUserPassword")
    def install_user_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "install_user_password")

    @_builtins.property
    @pulumi.getter(name="installUserPasswordIsHash")
    def install_user_password_is_hash(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "install_user_password_is_hash")

    @_builtins.property
    @pulumi.getter(name="installUserSshAuthorizedKeys")
    def install_user_ssh_authorized_keys(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "install_user_ssh_authorized_keys")

    @_builtins.property
    @pulumi.getter(name="ipAddress")
    def ip_address(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ip_address")

    @_builtins.property
    @pulumi.getter
    def memory(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "memory")

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "name_prefix")

    @_builtins.property
    @pulumi.getter
    def names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "names")

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "nameservers")

    @_builtins.property
    @pulumi.getter(name="networkBridge")
    def network_bridge(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "network_bridge")

    @_builtins.property
    @pulumi.getter(name="networkModel")
    def network_model(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "network_model")

    @_builtins.property
    @pulumi.getter(name="nodeName")
    def node_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "node_name")

    @_builtins.property
    @pulumi.getter
    def nonat(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "nonat")

    @_builtins.property
    @pulumi.getter
    def oauth2(self) -> pulumi.Output[Optional['_provider.outputs.NetskopeOAuth2Args']]:
        return pulumi.get(self, "oauth2")

    @_builtins.property
    @pulumi.getter(name="onBoot")
    def on_boot(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "on_boot")

    @_builtins.property
    @pulumi.getter(name="poolId")
    def pool_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "pool_id")

    @_builtins.property
    @pulumi.getter(name="publisherNames")
    def publisher_names(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "publisher_names")

    @_builtins.property
    @pulumi.getter
    def publishers(self) -> pulumi.Output[Mapping[str, Any]]:
        return pulumi.get(self, "publishers")

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> pulumi.Output[Optional[Mapping[str, '_provider.outputs.PublisherRegistrationInput']]]:
        return pulumi.get(self, "registrations")

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "replicas")

    @_builtins.property
    @pulumi.getter
    def started(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "started")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="templateVmId")
    def template_vm_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "template_vm_id")

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "tenant_url")

    @_builtins.property
    @pulumi.getter(name="vlanId")
    def vlan_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "vlan_id")

    @_builtins.property
    @pulumi.getter(name="vmId")
    def vm_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "vm_id")

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "wizard_path")

