# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['VspherePublisherArgs', 'VspherePublisher']

@pulumi.input_type
class VspherePublisherArgs:
    def __init__(__self__, *,
                 datacenter: pulumi.Input[_builtins.str],
                 datastore: pulumi.Input[_builtins.str],
                 network_name: pulumi.Input[_builtins.str],
                 template_name: pulumi.Input[_builtins.str],
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 num_cpus: Optional[pulumi.Input[_builtins.int]] = None,
                 registrations: Optional[pulumi.Input['PublisherRegistrationMapArgs']] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tenant_url: Optional[pulumi.Input[_builtins.str]] = None,
                 wizard_path: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a VspherePublisher resource.

        :param pulumi.Input[_builtins.str] datacenter: vSphere datacenter name.
        :param pulumi.Input[_builtins.str] datastore: vSphere datastore name.
        :param pulumi.Input[_builtins.str] network_name: vSphere network name.
        :param pulumi.Input[_builtins.str] template_name: vSphere template VM name.
        :param pulumi.Input[_builtins.str] api_token: Netskope API token used for publisher registration.
        :param pulumi.Input[_builtins.str] cluster: vSphere cluster name.
        :param pulumi.Input[_builtins.str] folder: Optional VM folder.
        :param pulumi.Input[_builtins.str] host: vSphere host name.
        :param pulumi.Input[_builtins.int] memory: Memory in MB.
        :param pulumi.Input[_builtins.str] name_prefix: Prefix used to derive publisher names when explicit names are not supplied.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] names: Explicit publisher names to create.
        :param pulumi.Input[_builtins.int] num_cpus: Number of virtual CPUs.
        :param pulumi.Input['PublisherRegistrationMapArgs'] registrations: Pre-created Netskope publisher registrations keyed by publisher name.
        :param pulumi.Input[_builtins.int] replicas: Number of publishers to create when names are not supplied.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags applied to supported provider resources.
        :param pulumi.Input[_builtins.str] tenant_url: Netskope tenant URL used for publisher registration.
        :param pulumi.Input[_builtins.str] wizard_path: Netskope publisher registration wizard API path.
        """
        pulumi.set(__self__, "datacenter", datacenter)
        pulumi.set(__self__, "datastore", datastore)
        pulumi.set(__self__, "network_name", network_name)
        pulumi.set(__self__, "template_name", template_name)
        if api_token is not None:
            pulumi.set(__self__, "api_token", api_token)
        if cluster is not None:
            pulumi.set(__self__, "cluster", cluster)
        if folder is not None:
            pulumi.set(__self__, "folder", folder)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)
        if name_prefix is not None:
            pulumi.set(__self__, "name_prefix", name_prefix)
        if names is not None:
            pulumi.set(__self__, "names", names)
        if num_cpus is not None:
            pulumi.set(__self__, "num_cpus", num_cpus)
        if registrations is not None:
            pulumi.set(__self__, "registrations", registrations)
        if replicas is not None:
            pulumi.set(__self__, "replicas", replicas)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tenant_url is not None:
            pulumi.set(__self__, "tenant_url", tenant_url)
        if wizard_path is not None:
            pulumi.set(__self__, "wizard_path", wizard_path)

    @_builtins.property
    @pulumi.getter
    def datacenter(self) -> pulumi.Input[_builtins.str]:
        """
        vSphere datacenter name.
        """
        return pulumi.get(self, "datacenter")

    @datacenter.setter
    def datacenter(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "datacenter", value)

    @_builtins.property
    @pulumi.getter
    def datastore(self) -> pulumi.Input[_builtins.str]:
        """
        vSphere datastore name.
        """
        return pulumi.get(self, "datastore")

    @datastore.setter
    def datastore(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "datastore", value)

    @_builtins.property
    @pulumi.getter(name="networkName")
    def network_name(self) -> pulumi.Input[_builtins.str]:
        """
        vSphere network name.
        """
        return pulumi.get(self, "network_name")

    @network_name.setter
    def network_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "network_name", value)

    @_builtins.property
    @pulumi.getter(name="templateName")
    def template_name(self) -> pulumi.Input[_builtins.str]:
        """
        vSphere template VM name.
        """
        return pulumi.get(self, "template_name")

    @template_name.setter
    def template_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "template_name", value)

    @_builtins.property
    @pulumi.getter(name="apiToken")
    def api_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Netskope API token used for publisher registration.
        """
        return pulumi.get(self, "api_token")

    @api_token.setter
    def api_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_token", value)

    @_builtins.property
    @pulumi.getter
    def cluster(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        vSphere cluster name.
        """
        return pulumi.get(self, "cluster")

    @cluster.setter
    def cluster(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster", value)

    @_builtins.property
    @pulumi.getter
    def folder(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional VM folder.
        """
        return pulumi.get(self, "folder")

    @folder.setter
    def folder(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "folder", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        vSphere host name.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Memory in MB.
        """
        return pulumi.get(self, "memory")

    @memory.setter
    def memory(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "memory", value)

    @_builtins.property
    @pulumi.getter(name="namePrefix")
    def name_prefix(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Prefix used to derive publisher names when explicit names are not supplied.
        """
        return pulumi.get(self, "name_prefix")

    @name_prefix.setter
    def name_prefix(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name_prefix", value)

    @_builtins.property
    @pulumi.getter
    def names(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Explicit publisher names to create.
        """
        return pulumi.get(self, "names")

    @names.setter
    def names(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "names", value)

    @_builtins.property
    @pulumi.getter(name="numCpus")
    def num_cpus(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of virtual CPUs.
        """
        return pulumi.get(self, "num_cpus")

    @num_cpus.setter
    def num_cpus(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "num_cpus", value)

    @_builtins.property
    @pulumi.getter
    def registrations(self) -> Optional[pulumi.Input['PublisherRegistrationMapArgs']]:
        """
        Pre-created Netskope publisher registrations keyed by publisher name.
        """
        return pulumi.get(self, "registrations")

    @registrations.setter
    def registrations(self, value: Optional[pulumi.Input['PublisherRegistrationMapArgs']]):
        pulumi.set(self, "registrations", value)

    @_builtins.property
    @pulumi.getter
    def replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of publishers to create when names are not supplied.
        """
        return pulumi.get(self, "replicas")

    @replicas.setter
    def replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "replicas", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Tags applied to supported provider resources.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="tenantUrl")
    def tenant_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Netskope tenant URL used for publisher registration.
        """
        return pulumi.get(self, "tenant_url")

    @tenant_url.setter
    def tenant_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tenant_url", value)

    @_builtins.property
    @pulumi.getter(name="wizardPath")
    def wizard_path(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Netskope publisher registration wizard API path.
        """
        return pulumi.get(self, "wizard_path")

    @wizard_path.setter
    def wizard_path(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "wizard_path", value)


@pulumi.type_token("netskope-publisher:index:VspherePublisher")
class VspherePublisher(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 datacenter: Optional[pulumi.Input[_builtins.str]] = None,
                 datastore: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 network_name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_cpus: Optional[pulumi.Input[_builtins.int]] = None,
                 registrations: Optional[pulumi.Input[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 template_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tenant_url: Optional[pulumi.Input[_builtins.str]] = None,
                 wizard_path: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Creates one or more Netskope Private Access Publisher vSphere virtual machines and registers them with a Netskope tenant.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_token: Netskope API token used for publisher registration.
        :param pulumi.Input[_builtins.str] cluster: vSphere cluster name.
        :param pulumi.Input[_builtins.str] datacenter: vSphere datacenter name.
        :param pulumi.Input[_builtins.str] datastore: vSphere datastore name.
        :param pulumi.Input[_builtins.str] folder: Optional VM folder.
        :param pulumi.Input[_builtins.str] host: vSphere host name.
        :param pulumi.Input[_builtins.int] memory: Memory in MB.
        :param pulumi.Input[_builtins.str] name_prefix: Prefix used to derive publisher names when explicit names are not supplied.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] names: Explicit publisher names to create.
        :param pulumi.Input[_builtins.str] network_name: vSphere network name.
        :param pulumi.Input[_builtins.int] num_cpus: Number of virtual CPUs.
        :param pulumi.Input[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']] registrations: Pre-created Netskope publisher registrations keyed by publisher name.
        :param pulumi.Input[_builtins.int] replicas: Number of publishers to create when names are not supplied.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags applied to supported provider resources.
        :param pulumi.Input[_builtins.str] template_name: vSphere template VM name.
        :param pulumi.Input[_builtins.str] tenant_url: Netskope tenant URL used for publisher registration.
        :param pulumi.Input[_builtins.str] wizard_path: Netskope publisher registration wizard API path.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VspherePublisherArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates one or more Netskope Private Access Publisher vSphere virtual machines and registers them with a Netskope tenant.


        :param str resource_name: The name of the resource.
        :param VspherePublisherArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VspherePublisherArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_token: Optional[pulumi.Input[_builtins.str]] = None,
                 cluster: Optional[pulumi.Input[_builtins.str]] = None,
                 datacenter: Optional[pulumi.Input[_builtins.str]] = None,
                 datastore: Optional[pulumi.Input[_builtins.str]] = None,
                 folder: Optional[pulumi.Input[_builtins.str]] = None,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 name_prefix: Optional[pulumi.Input[_builtins.str]] = None,
                 names: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 network_name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_cpus: Optional[pulumi.Input[_builtins.int]] = None,
                 registrations: Optional[pulumi.Input[Union['PublisherRegistrationMapArgs', 'PublisherRegistrationMapArgsDict']]] = None,
                 replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 template_name: Optional[pulumi.Input[_builtins.str]] = None,
                 tenant_url: Optional[pulumi.Input[_builtins.str]] = None,
                 wizard_path: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VspherePublisherArgs.__new__(VspherePublisherArgs)

            __props__.__dict__["api_token"] = None if api_token is None else pulumi.Output.secret(api_token)
            __props__.__dict__["cluster"] = cluster
            if datacenter is None and not opts.urn:
                raise TypeError("Missing required property 'datacenter'")
            __props__.__dict__["datacenter"] = datacenter
            if datastore is None and not opts.urn:
                raise TypeError("Missing required property 'datastore'")
            __props__.__dict__["datastore"] = datastore
            __props__.__dict__["folder"] = folder
            __props__.__dict__["host"] = host
            __props__.__dict__["memory"] = memory
            __props__.__dict__["name_prefix"] = name_prefix
            __props__.__dict__["names"] = names
            if network_name is None and not opts.urn:
                raise TypeError("Missing required property 'network_name'")
            __props__.__dict__["network_name"] = network_name
            __props__.__dict__["num_cpus"] = num_cpus
            __props__.__dict__["registrations"] = registrations
            __props__.__dict__["replicas"] = replicas
            __props__.__dict__["tags"] = tags
            if template_name is None and not opts.urn:
                raise TypeError("Missing required property 'template_name'")
            __props__.__dict__["template_name"] = template_name
            __props__.__dict__["tenant_url"] = tenant_url
            __props__.__dict__["wizard_path"] = wizard_path
            __props__.__dict__["publisher_names"] = None
            __props__.__dict__["publishers"] = None
        super(VspherePublisher, __self__).__init__(
            'netskope-publisher:index:VspherePublisher',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="publisherNames")
    def publisher_names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Created publisher names.
        """
        return pulumi.get(self, "publisher_names")

    @_builtins.property
    @pulumi.getter
    def publishers(self) -> pulumi.Output[Optional['outputs.PublisherOutputMap']]:
        """
        Publisher registration and VM details keyed by name.
        """
        return pulumi.get(self, "publishers")

