// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.provider.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GcpServiceAccountArgs extends com.pulumi.resources.ResourceArgs {

    public static final GcpServiceAccountArgs Empty = new GcpServiceAccountArgs();

    @Import(name="email", required=true)
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }

    @Import(name="scopes")
    private @Nullable Output<List<String>> scopes;

    public Optional<Output<List<String>>> scopes() {
        return Optional.ofNullable(this.scopes);
    }

    private GcpServiceAccountArgs() {}

    private GcpServiceAccountArgs(GcpServiceAccountArgs $) {
        this.email = $.email;
        this.scopes = $.scopes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GcpServiceAccountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GcpServiceAccountArgs $;

        public Builder() {
            $ = new GcpServiceAccountArgs();
        }

        public Builder(GcpServiceAccountArgs defaults) {
            $ = new GcpServiceAccountArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder scopes(@Nullable Output<List<String>> scopes) {
            $.scopes = scopes;
            return this;
        }

        public Builder scopes(List<String> scopes) {
            return scopes(Output.of(scopes));
        }

        public Builder scopes(String... scopes) {
            return scopes(List.of(scopes));
        }

        public GcpServiceAccountArgs build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("GcpServiceAccountArgs", "email");
            }
            return $;
        }
    }

}
