// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.netskopepublisher.provider.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PublisherAssignmentInputArgs extends com.pulumi.resources.ResourceArgs {

    public static final PublisherAssignmentInputArgs Empty = new PublisherAssignmentInputArgs();

    @Import(name="placementLabels")
    private @Nullable Output<List<String>> placementLabels;

    public Optional<Output<List<String>>> placementLabels() {
        return Optional.ofNullable(this.placementLabels);
    }

    @Import(name="publisherId", required=true)
    private Output<Integer> publisherId;

    public Output<Integer> publisherId() {
        return this.publisherId;
    }

    private PublisherAssignmentInputArgs() {}

    private PublisherAssignmentInputArgs(PublisherAssignmentInputArgs $) {
        this.placementLabels = $.placementLabels;
        this.publisherId = $.publisherId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PublisherAssignmentInputArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PublisherAssignmentInputArgs $;

        public Builder() {
            $ = new PublisherAssignmentInputArgs();
        }

        public Builder(PublisherAssignmentInputArgs defaults) {
            $ = new PublisherAssignmentInputArgs(Objects.requireNonNull(defaults));
        }

        public Builder placementLabels(@Nullable Output<List<String>> placementLabels) {
            $.placementLabels = placementLabels;
            return this;
        }

        public Builder placementLabels(List<String> placementLabels) {
            return placementLabels(Output.of(placementLabels));
        }

        public Builder placementLabels(String... placementLabels) {
            return placementLabels(List.of(placementLabels));
        }

        public Builder publisherId(Output<Integer> publisherId) {
            $.publisherId = publisherId;
            return this;
        }

        public Builder publisherId(Integer publisherId) {
            return publisherId(Output.of(publisherId));
        }

        public PublisherAssignmentInputArgs build() {
            if ($.publisherId == null) {
                throw new MissingRequiredPropertyException("PublisherAssignmentInputArgs", "publisherId");
            }
            return $;
        }
    }

}
