// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher.Types.Outputs
{

    [OutputType]
    public sealed class PrivateAppProtocol
    {
        public readonly string Ports;
        public readonly string Type;

        [OutputConstructor]
        private PrivateAppProtocol(
            string ports,

            string type)
        {
            Ports = ports;
            Type = type;
        }
    }
}
