// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NetskopePublisher.Types.Outputs
{

    [OutputType]
    public sealed class PublisherAssignmentInput
    {
        public readonly ImmutableArray<string> PlacementLabels;
        public readonly int PublisherId;

        [OutputConstructor]
        private PublisherAssignmentInput(
            ImmutableArray<string> placementLabels,

            int publisherId)
        {
            PlacementLabels = placementLabels;
            PublisherId = publisherId;
        }
    }
}
